incognitoman-3px-dither: ## Template: Retro dither with Cover artwork card
	php bin/console build --package-name="incognitoman-3px-dither" --artwork="incognitoman-3px-dither:artwork.xml"
incognitoman-3px-dither-inner: ## Template: Retro dither with Cover artwork card (inner height)
	php bin/console build --package-name="incognitoman-3px-dither-inner" --artwork="incognitoman-3px-dither:artwork-inner.xml"