# TBS Config
#'mame': 'ARCADE'
#'atari2600': 'ATARI'
#'nes': 'FC'
#'gb': 'GB'
#'gba': 'GBA'
#'gbc': 'GBC'
#'gamegear': 'GG'
#'megadrive': 'MD'
#'mastersystem': 'MS'
#'neogeo': 'NEOGEO'
#'pcengine': 'PCE'
#'pcenginecd': 'PCECD'
#'segacd': 'SEGACD'
#'snes': 'SFC'
#'psx': 'PS'

'psx': 'PSX'
'nds': 'DS'
'mame': 'ARCADE'
'gb': 'GB'
'gba': 'GBA'
'nes': 'NES'
'n64': 'NINTENDO 64'
'snes': 'SUPER NES'
