simple-examples-gradient-screenshot-with-game-logo: ## Template: A simple gradient mask w/ screenshot & game logo (with portmaster)
	php bin/console build  --artwork='simple-examples:simple_gradient_with_game_logo.xml' --portmaster='simple-examples:simple_gradient_with_game_logo.xml' --package-name='gradient-screenshot-with-game-logo'

simple-examples-system-and-game-logos: ## Template: System Logo + Game Logo. Folder art w/ simple platform logos.
	php bin/console build  --artwork='simple-examples:system_logo_with_game_logo.xml' --folder='simple-examples:system_logo.xml' --package-name='system-and-game-logos'
