tokumeino-gradients-simple-box-cart: ## Template: Game box with game cart in front
	php bin/console build --artwork='tokumeino-gradients:simple-box-cart.xml' --package-name='tokumeino-gradients-simple-box-cart'
tokumeino-gradients-simple-box-shadow: ## Template: Game box with shadow
	php bin/console build --artwork='tokumeino-gradients:simple-box-shadow.xml' --package-name='tokumeino-gradients-simple-box-shadow'
tokumeino-gradients-full-height-gradient-with-game-logo: ## Template: Full height gradient with game logo
	php bin/console build --artwork='tokumeino-gradients:full-gradient-screen-wheel.xml' --package-name='tokumeino-gradients-full-height-gradient-with-game-logo'
tokumeino-gradients-full-height-gradient-with-game-logo-halftone: ## Template: Full height gradient with game logo, using 'halftone dots' mask
	php bin/console build --artwork='tokumeino-gradients:full-gradient-screen-wheel.xml'  --token='mask:muos-halftone-dots.png' --package-name='tokumeino-gradients-full-height-gradient-with-game-logo-halftone'
tokumeino-gradients-inner-height-gradient-with-game-logo: ## Template: Inner height gradient with game logo and 'high grain' mask
	php bin/console build --artwork='tokumeino-gradients:inner-gradient-screen-wheel.xml' --token='mask:muos-grain-high.png' --package-name='tokumeino-gradients-inner-height-gradient-with-game-logo'
tokumeino-gradients-inner-height-gradient-with-game-logo-and-box: ## Template: Inner height gradient with game logo and box using 'gray' mask
	php bin/console build --artwork='tokumeino-gradients:inner-gradient-screen-wheel-box.xml' --token='mask:muos-dithering-gray.png' --package-name='tokumeino-gradients-inner-height-gradient-with-game-logo-and-box'
