return {
  "Named_Snaps/101 Starships (World) (Erwin's Collection).png",
  "Named_Snaps/1010 (World) (v0.96) (Erwin's Collection).png",
  "Named_Snaps/1010 (World) (v0.96).png",
  "Named_Snaps/1943 (World) (Erwin's Collection).png",
  "Named_Snaps/1943 (World) (v1.0.3) (Alt).png",
  "Named_Snaps/1943 (World) (v1.0.3).png",
  "Named_Snaps/1944 (World) (Erwin's Collection).png",
  "Named_Snaps/1944 (World) (v1.0.3).png",
  "Named_Snaps/1nvader (World) (Erwin's Collection).png",
  "Named_Snaps/1nvader (World) (v1.0) (Alt).png",
  "Named_Snaps/1nvader (World) (v1.0).png",
  "Named_Snaps/1nvader (World) (v1.1).png",
  "Named_Snaps/2048 (World) (v0.5) (Erwin's Collection).png",
  "Named_Snaps/2048 (World) (v0.5).png",
  "Named_Snaps/2PlayersPack (World) (Erwin's Collection).png",
  "Named_Snaps/3in1A (World) (v3.1) (Erwin's Collection).png",
  "Named_Snaps/3in1B (World) (v2) (Erwin's Collection).png",
  "Named_Snaps/3in1C (World) (Erwin's Collection).png",
  "Named_Snaps/3in1E (World) (Erwin's Collection).png",
  "Named_Snaps/ABAsm DP1 (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/APara (World) (Erwin's Collection).png",
  "Named_Snaps/ARDUBULLETs (World) (v0.10).png",
  "Named_Snaps/ARDUBULLETs (World) (v0.11) (Erwin's Collection).png",
  "Named_Snaps/ARDUBULLETs (World) (v0.11).png",
  "Named_Snaps/ARtillery (World) (Erwin's Collection).png",
  "Named_Snaps/ARtillery (World) (v1).png",
  "Named_Snaps/ASTEROIDS (World) (Erwin's Collection).png",
  "Named_Snaps/ASTEROIDS (World) (FP).png",
  "Named_Snaps/ASTEROIDS (World) (ST).png",
  "Named_Snaps/AbSynth FM (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/AbSynth FM (World) (v2.0) (Program).png",
  "Named_Snaps/Abshell (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Arcodia (World) (Erwin's Collection).png",
  "Named_Snaps/Arcodia (World) (v1.0).png",
  "Named_Snaps/Ard-Drivin (World) (Erwin's Collection).png",
  "Named_Snaps/Ardletics (World) (Erwin's Collection).png",
  "Named_Snaps/Ardu Buggy (World) (v1.0) (Erwin's Collection).png",
  "Named_Snaps/Ardu Turf Masters (World) (Erwin's Collection).png",
  "Named_Snaps/Ardu-Racer (World) (Erwin's Collection).png",
  "Named_Snaps/Ardu-Racer (World) (v1.0).png",
  "Named_Snaps/Ardu-Racer (World) (v1.1).png",
  "Named_Snaps/Ardu-Racer (World) (v1.2).png",
  "Named_Snaps/Ardu-Racer (World) (v1.3).png",
  "Named_Snaps/Ardu-Whack (World) (Erwin's Collection).png",
  "Named_Snaps/Ardu-Whack (World) (v1.2).png",
  "Named_Snaps/Ardu-man (World) (Erwin's Collection).png",
  "Named_Snaps/ArduBOYNG (World) (Erwin's Collection).png",
  "Named_Snaps/ArduBall (World) (Erwin's Collection).png",
  "Named_Snaps/ArduBall (World) (v1.0).png",
  "Named_Snaps/ArduBrain (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/ArduBrain (World) (Program).png",
  "Named_Snaps/ArduCC (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/ArduCC (World) (v1.0) (Program).png",
  "Named_Snaps/ArduGods (World).png",
  "Named_Snaps/ArduIndy (World) (Erwin's Collection).png",
  "Named_Snaps/ArduIndy (World) (v2.50).png",
  "Named_Snaps/ArduLO (World) (Erwin's Collection).png",
  "Named_Snaps/ArduLO (World) (v1.0).png",
  "Named_Snaps/ArduMetronome (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/ArduMetronome (World) (v1.0.0) (Program).png",
  "Named_Snaps/ArduRemote (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/ArduRemote (World) (v0.1) (Program).png",
  "Named_Snaps/ArduSaver (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/ArduSaver (World) (Program).png",
  "Named_Snaps/ArduTosh (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/ArduTosh (World) (v1.0) (Program).png",
  "Named_Snaps/ArduTosh (World) (v1.0.1) (Program).png",
  "Named_Snaps/ArduTosh (World) (v1.0.2) (Program).png",
  "Named_Snaps/Arduboy Assistant (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Arduboy Assistant (World) (v2.0) (Program).png",
  "Named_Snaps/Arduboy Gamepad (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Arduboy Says (World) (Erwin's Collection).png",
  "Named_Snaps/Arduboy Says (World) (Update 2).png",
  "Named_Snaps/Arduboy Sprite Editor (World) (v0.3) (Program) (Erwin's Collection).png",
  "Named_Snaps/Arduboy Sprite Editor (World) (v0.3) (Program).png",
  "Named_Snaps/ArduboyLife (World) (Erwin's Collection).png",
  "Named_Snaps/ArduboyLife (World) (v2.0).png",
  "Named_Snaps/Arducross (World) (Erwin's Collection).png",
  "Named_Snaps/Ardulem (World) (Erwin's Collection).png",
  "Named_Snaps/Ardulem (World) (v1.0).png",
  "Named_Snaps/Arduloop (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Arduminer (World) (Erwin's Collection).png",
  "Named_Snaps/Arduminer (World) (v1.0).png",
  "Named_Snaps/Arduminer (World) (v1.1).png",
  "Named_Snaps/Arduslide (World) (Erwin's Collection).png",
  "Named_Snaps/Ardynia (World) (Erwin's Collection).png",
  "Named_Snaps/Ardynia (World).png",
  "Named_Snaps/Armageddon (World) (Erwin's Collection).png",
  "Named_Snaps/Atomic Puzzle Pack (World) (Erwin's Collection).png",
  "Named_Snaps/Back to the Jungle (World) (Erwin's Collection).png",
  "Named_Snaps/Bang! Bang! (World) (Erwin's Collection).png",
  "Named_Snaps/Bangi (World) (Erwin's Collection).png",
  "Named_Snaps/Battle for Zuthsrah (World) (Erwin's Collection).png",
  "Named_Snaps/Beam 'Em Up (World) (Erwin's Collection).png",
  "Named_Snaps/Biddy Watering (World) (Demo) (Erwin's Collection).png",
  "Named_Snaps/BigBlackBox (World) (Erwin's Collection).png",
  "Named_Snaps/BiriBiriBeat (World) (Erwin's Collection).png",
  "Named_Snaps/Blackjack (World) (Erwin's Collection).png",
  "Named_Snaps/Blackjack (World) (v1.0).png",
  "Named_Snaps/Blackjack (World).png",
  "Named_Snaps/Blocks (World) (Erwin's Collection).png",
  "Named_Snaps/Boids (World) (Erwin's Collection).png",
  "Named_Snaps/Bombzzle (World) (Erwin's Collection).png",
  "Named_Snaps/Boris Goes Skiing (World) (Erwin's Collection).png",
  "Named_Snaps/Boris Goes Skiing (World) (v1.0).png",
  "Named_Snaps/Bounce! (World) (Erwin's Collection).png",
  "Named_Snaps/Bounce (World) (v1.0).png",
  "Named_Snaps/Bounce (World) (v1.1).png",
  "Named_Snaps/Box Stacker (World) (Erwin's Collection).png",
  "Named_Snaps/Breakout-V (World) (Erwin's Collection).png",
  "Named_Snaps/BurgardTime (World) (Erwin's Collection).png",
  "Named_Snaps/BurgardTime (World).png",
  "Named_Snaps/CastleBoy (World) (Erwin's Collection).png",
  "Named_Snaps/Catacombs of the Damned (World) (Erwin's Collection).png",
  "Named_Snaps/Catacombs of the Damned (World) (v0.1) (Demo).png",
  "Named_Snaps/Catacombs of the Damned (World) (v1.0).png",
  "Named_Snaps/Chicken Launcher (World) (Erwin's Collection).png",
  "Named_Snaps/Chicken Launcher (World) (v1.1).png",
  "Named_Snaps/Chirp (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Chirp (World) (Program).png",
  "Named_Snaps/Choplifter (World) (Erwin's Collection).png",
  "Named_Snaps/Choplifter (World) (FX Enhanced).png",
  "Named_Snaps/Choplifter (World) (v1.1.1).png",
  "Named_Snaps/Chri-Bocchi Cat (World) (v0.03) (Erwin's Collection).png",
  "Named_Snaps/Chri-Bocchi Cat (World) (v0.04).png",
  "Named_Snaps/Chrome Dino (World) (Erwin's Collection).png",
  "Named_Snaps/Chrome Dino (World).png",
  "Named_Snaps/Chrome Dino - Halloween (World) (Erwin's Collection).png",
  "Named_Snaps/Cistercia (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Coder's Toolbox (World) (FX Enhanced) (Program).png",
  "Named_Snaps/Coder's Toolbox (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/CosmicPods (World) (Erwin's Collection).png",
  "Named_Snaps/CowBro (World) (Erwin's Collection).png",
  "Named_Snaps/CowBro (World).png",
  "Named_Snaps/Crabator (World) (Erwin's Collection).png",
  "Named_Snaps/Crate Confusion (World) (Erwin's Collection).png",
  "Named_Snaps/Crate Confusion (World).png",
  "Named_Snaps/Crates 3D (World) (Erwin's Collection).png",
  "Named_Snaps/Crates 3D (World) (v1.0).png",
  "Named_Snaps/Crawl, The (World) (v1.01).png",
  "Named_Snaps/CrazyKart (World) (Erwin's Collection).png",
  "Named_Snaps/Cribbage (World) (Erwin's Collection).png",
  "Named_Snaps/Cribbage (World) (v1.02).png",
  "Named_Snaps/Cripple Mr Onion (World) (Erwin's Collection).png",
  "Named_Snaps/Cripple Mr Onion (World) (v1.0).png",
  "Named_Snaps/CyberHack (World) (Erwin's Collection).png",
  "Named_Snaps/DanceRow (World) (Erwin's Collection).png",
  "Named_Snaps/Deep Dish Nine (World) (Erwin's Collection).png",
  "Named_Snaps/Defenduino (World) (v1.0).png",
  "Named_Snaps/Defenduino (World) (v1.1).png",
  "Named_Snaps/Defenduino (World) (v1.2) (Erwin's Collection).png",
  "Named_Snaps/Defenduino (World) (v1.2).png",
  "Named_Snaps/Diamonds (World) (Erwin's Collection).png",
  "Named_Snaps/Dice of Fate (World) (Program).png",
  "Named_Snaps/Dice of Fate (World) (v1.7.2) (Program).png",
  "Named_Snaps/Digger (World) (Erwin's Collection).png",
  "Named_Snaps/Do You Remember Love (World) (Erwin's Collection).png",
  "Named_Snaps/Dominoes 'All Fives' (World) (Erwin's Collection).png",
  "Named_Snaps/Electronic Quarterback (World) (Erwin's Collection).png",
  "Named_Snaps/Epic Mini Games (World) (Erwin's Collection).png",
  "Named_Snaps/Evade (World) (Erwin's Collection).png",
  "Named_Snaps/Evade 2 (World) (Erwin's Collection).png",
  "Named_Snaps/Fanboat (World) (Erwin's Collection).png",
  "Named_Snaps/Farkle (World) (Erwin's Collection).png",
  "Named_Snaps/Fatsche (World) (Erwin's Collection).png",
  "Named_Snaps/Fire Panic (World) (Alt).png",
  "Named_Snaps/Fire Panic (World) (Erwin's Collection).png",
  "Named_Snaps/Flappy Ball (World) (Erwin's Collection).png",
  "Named_Snaps/Flappy Birdie (World) (Erwin's Collection).png",
  "Named_Snaps/Flood Fill (World) (Erwin's Collection).png",
  "Named_Snaps/Fluffle's Rainy Day (World).png",
  "Named_Snaps/Galaxion (World) (Erwin's Collection).png",
  "Named_Snaps/Games'N Goblins - The Game (World) (Erwin's Collection).png",
  "Named_Snaps/German Whist (World) (Erwin's Collection).png",
  "Named_Snaps/Glove (World) (Erwin's Collection).png",
  "Named_Snaps/Graph (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Graph 2 (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Hangman! (World) (Erwin's Collection).png",
  "Named_Snaps/Harambe's Revenge (World) (Erwin's Collection).png",
  "Named_Snaps/Helii (World) (Erwin's Collection).png",
  "Named_Snaps/Hello, Commander (World) (Erwin's Collection).png",
  "Named_Snaps/Hollow Seeker (World) (v0.31) (Erwin's Collection).png",
  "Named_Snaps/Hollow Seeker (World) (v0.32).png",
  "Named_Snaps/Hopper (World) (v0.21) (Erwin's Collection).png",
  "Named_Snaps/Hopper (World) (v0.22).png",
  "Named_Snaps/Humanity Revenge DC (World) (Erwin's Collection).png",
  "Named_Snaps/IDOUDO (World) (Erwin's Collection).png",
  "Named_Snaps/Invaders (World) (Erwin's Collection).png",
  "Named_Snaps/Is This Loss - The Game (World) (Erwin's Collection).png",
  "Named_Snaps/Jet Pac (World) (Erwin's Collection).png",
  "Named_Snaps/Jezzball (World) (Erwin's Collection).png",
  "Named_Snaps/Joustish (World) (Erwin's Collection).png",
  "Named_Snaps/JumpBoy (World) (Erwin's Collection).png",
  "Named_Snaps/Juno First (World) (v1.00) (Erwin's Collection).png",
  "Named_Snaps/Juno First (World) (v1.01).png",
  "Named_Snaps/Karateka (World) (Erwin's Collection).png",
  "Named_Snaps/Karateka (World) (FX Enhanced).png",
  "Named_Snaps/Karateka (World) (v0.9) (Alt).png",
  "Named_Snaps/Karateka (World) (v0.9).png",
  "Named_Snaps/Kemono Patrol (World) (Erwin's Collection).png",
  "Named_Snaps/KeyKat - I.T. (World) (Erwin's Collection).png",
  "Named_Snaps/Knight Move (World) (v0.10).png",
  "Named_Snaps/Knight Move (World) (v0.11) (Alt).png",
  "Named_Snaps/Knight Move (World) (v0.11) (Erwin's Collection).png",
  "Named_Snaps/Knight Move (World) (v0.11).png",
  "Named_Snaps/Kong (World) (Erwin's Collection).png",
  "Named_Snaps/Kong (World) (v1.0.4).png",
  "Named_Snaps/Kooky Kookies (World) (v1.1) (Erwin's Collection).png",
  "Named_Snaps/Kooky Kookies (World) (v1.2).png",
  "Named_Snaps/Kung Fu Escape (World) (Erwin's Collection).png",
  "Named_Snaps/Lagunita (World).png",
  "Named_Snaps/Lasers (World) (v0.11) (Alt).png",
  "Named_Snaps/Lasers (World) (v0.11) (Erwin's Collection).png",
  "Named_Snaps/Lasers (World) (v0.11).png",
  "Named_Snaps/Lasers (World) (v0.12).png",
  "Named_Snaps/Leanna the Lion (World) (v1.1) (Erwin's Collection).png",
  "Named_Snaps/Leanna the Lion (World) (v1.2).png",
  "Named_Snaps/Light Meter (World) (Erwin's Collection).png",
  "Named_Snaps/Lite Out (World) (Erwin's Collection).png",
  "Named_Snaps/Little Rook Chess (World) (Erwin's Collection).png",
  "Named_Snaps/Lode Runner (World) (v1.04) (Levels 1 to 40) (Erwin's Collection).png",
  "Named_Snaps/Lode Runner (World) (v1.04) (Levels 121 to 154) (Erwin's Collection).png",
  "Named_Snaps/Lode Runner (World) (v1.04) (Levels 41 to 80) (Erwin's Collection).png",
  "Named_Snaps/Lode Runner (World) (v1.04) (Levels 81 to 120) (Erwin's Collection).png",
  "Named_Snaps/Love Tester (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/LoveRush (World) (v1.1.1) (Erwin's Collection).png",
  "Named_Snaps/LoveRush (World) (v1.1.2).png",
  "Named_Snaps/MallARD Hunt (World).png",
  "Named_Snaps/MayQ (World) (Erwin's Collection).png",
  "Named_Snaps/MazezaM (World) (Erwin's Collection).png",
  "Named_Snaps/Mazogs (World) (Erwin's Collection).png",
  "Named_Snaps/MicroCity (World) (Erwin's Collection).png",
  "Named_Snaps/MicroTD (World) (v1.01) (Erwin's Collection).png",
  "Named_Snaps/MicroTank (World) (Erwin's Collection).png",
  "Named_Snaps/Millipe (World) (Erwin's Collection).png",
  "Named_Snaps/Minesweeper (World) (Erwin's Collection).png",
  "Named_Snaps/Monpals (World).png",
  "Named_Snaps/Nanoseq (World) (Erwin's Collection).png",
  "Named_Snaps/Night Raid (World) (Erwin's Collection).png",
  "Named_Snaps/Ninja Fuzzgrawth (World) (Erwin's Collection).png",
  "Named_Snaps/Nomis (World) (Erwin's Collection).png",
  "Named_Snaps/Not Just a Hat Rack (World) (Erwin's Collection).png",
  "Named_Snaps/NumberMind (World) (Erwin's Collection).png",
  "Named_Snaps/Oh Mummy (World) (Erwin's Collection).png",
  "Named_Snaps/Oh, You're Gunna Die (World) (Erwin's Collection).png",
  "Named_Snaps/Oil Panic (World) (Erwin's Collection).png",
  "Named_Snaps/OktaArduToken (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Omega Horizon (World) (Erwin's Collection).png",
  "Named_Snaps/Orbs (World) (Erwin's Collection).png",
  "Named_Snaps/PAC-Tastic (World) (Erwin's Collection).png",
  "Named_Snaps/PI 24k (World) (v0.03) (Program) (Alt).png",
  "Named_Snaps/PI 24k (World) (v0.03) (Program) (Erwin's Collection).png",
  "Named_Snaps/PI 24k (World) (v0.03) (Program).png",
  "Named_Snaps/Paqman (World) (Erwin's Collection).png",
  "Named_Snaps/Petit of the Dead (World) (Erwin's Collection).png",
  "Named_Snaps/Petitseq (World) (Erwin's Collection).png",
  "Named_Snaps/PiCross (World) (Erwin's Collection).png",
  "Named_Snaps/Picovaders (World) (Erwin's Collection).png",
  "Named_Snaps/Pipes (World) (Erwin's Collection).png",
  "Named_Snaps/Pocket Fighter (World) (Erwin's Collection).png",
  "Named_Snaps/Pocket Othello (World) (Erwin's Collection).png",
  "Named_Snaps/Pocket PDA (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Poitto (World) (Erwin's Collection).png",
  "Named_Snaps/Pong (World) (Erwin's Collection).png",
  "Named_Snaps/Poop Panic! (World) (Erwin's Collection).png",
  "Named_Snaps/Psi Colo (World) (v0.11).png",
  "Named_Snaps/Quadrastic (World) (Erwin's Collection).png",
  "Named_Snaps/Quarto! (World) (v0.10) (Alt).png",
  "Named_Snaps/Quarto! (World) (v0.10) (Erwin's Collection).png",
  "Named_Snaps/Quarto! (World) (v0.10).png",
  "Named_Snaps/Randocity (World) (Erwin's Collection).png",
  "Named_Snaps/Ravine Despoiler (World) (Erwin's Collection).png",
  "Named_Snaps/Rayne the Rogue (World) (Erwin's Collection).png",
  "Named_Snaps/Rayne the Rogue (World) (No QR Code).png",
  "Named_Snaps/Rayne the Rogue (World) (v2.9).png",
  "Named_Snaps/Reversi (World) (v0.10) (Erwin's Collection).png",
  "Named_Snaps/Reversi (World) (v0.11).png",
  "Named_Snaps/Rick and Morty Game (World) (Erwin's Collection).png",
  "Named_Snaps/Ring Puzzle (World) (Erwin's Collection).png",
  "Named_Snaps/RoboDodge (World) (Erwin's Collection).png",
  "Named_Snaps/Rogue (World) (v1.21) (Erwin's Collection).png",
  "Named_Snaps/Roo Run (World) (Erwin's Collection).png",
  "Named_Snaps/Rooftop Rescue (World) (Erwin's Collection).png",
  "Named_Snaps/Roshambo (World) (Erwin's Collection).png",
  "Named_Snaps/SFCave (World) (Erwin's Collection).png",
  "Named_Snaps/SIEGE (World) (v1.1).png",
  "Named_Snaps/SNAKE (World) (CDRXavier) (Erwin's Collection).png",
  "Named_Snaps/SNAKE (World) (CDRXavier).png",
  "Named_Snaps/SameGame (World) (v0.10) (Alt).png",
  "Named_Snaps/SameGame (World) (v0.10) (Erwin's Collection).png",
  "Named_Snaps/SameGame (World) (v0.10).png",
  "Named_Snaps/Santa's Happy Little Packer (World) (Erwin's Collection).png",
  "Named_Snaps/Sensitive (World) (Erwin's Collection).png",
  "Named_Snaps/SetSystemEEPROM (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Siege (World) (Erwin's Collection).png",
  "Named_Snaps/SnELk (World) (Erwin's Collection).png",
  "Named_Snaps/Snake (World) (Stu) (Erwin's Collection).png",
  "Named_Snaps/Solitaire (World) (Erwin's Collection).png",
  "Named_Snaps/Space Battle - Trench Run (World) (v1.1) (Erwin's Collection).png",
  "Named_Snaps/Space Cab (World) (v1.0) (Erwin's Collection).png",
  "Named_Snaps/Space Fighter (World) (Erwin's Collection).png",
  "Named_Snaps/Space Invaders (World) (Erwin's Collection).png",
  "Named_Snaps/Space Knife (World) (Erwin's Collection).png",
  "Named_Snaps/Space Quarth (World) (Erwin's Collection).png",
  "Named_Snaps/Square Nose (World) (Erwin's Collection).png",
  "Named_Snaps/Squario (World) (Erwin's Collection).png",
  "Named_Snaps/Stairs Sweep (World) (v0.10) (Erwin's Collection).png",
  "Named_Snaps/Stairs Sweep (World) (v0.10).png",
  "Named_Snaps/Starduino Turbo (World) (Erwin's Collection).png",
  "Named_Snaps/Stellar Impact (World) (Erwin's Collection).png",
  "Named_Snaps/Sudoku-NBP (World) (Erwin's Collection).png",
  "Named_Snaps/Super Crate Buino (World) (Erwin's Collection).png",
  "Named_Snaps/TV Tuner (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/Tackle Box (World) (v1.2.0) (Erwin's Collection).png",
  "Named_Snaps/Tamaguino-AB (World) (Erwin's Collection).png",
  "Named_Snaps/Techno Monkey (World) (Erwin's Collection).png",
  "Named_Snaps/Techno Monkey (World) (v1.0).png",
  "Named_Snaps/Tetris (World) (Erwin's Collection).png",
  "Named_Snaps/TicTacCurly (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny Asteroids (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny Depth (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny Digital Invader (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny Lander (World) (v1.0) (Erwin's Collection).png",
  "Named_Snaps/Tiny NS-Tower (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny Sokoban (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Bert (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Bike (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-DDug (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Missile (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Morpion (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Pipe (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Plaque (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Trick (World) (Erwin's Collection).png",
  "Named_Snaps/Tiny-Tris (World) (Erwin's Collection).png",
  "Named_Snaps/To (World) (Erwin's Collection).png",
  "Named_Snaps/Tower of Pain (World) (v1.2.2).png",
  "Named_Snaps/Train Dodge (World) (Erwin's Collection).png",
  "Named_Snaps/Tris (World) (Erwin's Collection).png",
  "Named_Snaps/Turtle Bridge (World) (v1.0) (Erwin's Collection).png",
  "Named_Snaps/Turtle Bridge (World) (v1.3).png",
  "Named_Snaps/Twotris (World) (Erwin's Collection).png",
  "Named_Snaps/Ufo-Race (World) (Erwin's Collection).png",
  "Named_Snaps/Umeroose (World) (Erwin's Collection).png",
  "Named_Snaps/Under the Tower (World) (Erwin's Collection).png",
  "Named_Snaps/Virtual Gamepad (World) (Program) (Erwin's Collection).png",
  "Named_Snaps/WHG (World) (Erwin's Collection).png",
  "Named_Snaps/Waternet (World) (Erwin's Collection).png",
  "Named_Snaps/Yatzy (World) (Erwin's Collection).png",
  "Named_Snaps/Yatzy (World) (v1.3).png",
  "Named_Snaps/You Won't Survive (World) (Erwin's Collection).png",
  "Named_Snaps/Zoo (World) (Erwin's Collection).png",
  "Named_Snaps/Zoo at Midnight (World) (Erwin's Collection).png",
  "Named_Snaps/ZooEscape (World) (Erwin's Collection).png",
  "Named_Titles/101 Starships (World) (Erwin's Collection).png",
  "Named_Titles/1010 (World) (v0.96) (Erwin's Collection).png",
  "Named_Titles/1010 (World) (v0.96).png",
  "Named_Titles/1943 (World) (Erwin's Collection).png",
  "Named_Titles/1943 (World) (v1.0.3) (Alt).png",
  "Named_Titles/1943 (World) (v1.0.3).png",
  "Named_Titles/1944 (World) (Erwin's Collection).png",
  "Named_Titles/1944 (World) (v1.0.3).png",
  "Named_Titles/1nvader (World) (Erwin's Collection).png",
  "Named_Titles/1nvader (World) (v1.0) (Alt).png",
  "Named_Titles/1nvader (World) (v1.0).png",
  "Named_Titles/1nvader (World) (v1.1).png",
  "Named_Titles/2048 (World) (v0.5) (Erwin's Collection).png",
  "Named_Titles/2048 (World) (v0.5).png",
  "Named_Titles/2PlayersPack (World) (Erwin's Collection).png",
  "Named_Titles/3in1A (World) (v3.1) (Erwin's Collection).png",
  "Named_Titles/3in1B (World) (v2) (Erwin's Collection).png",
  "Named_Titles/3in1C (World) (Erwin's Collection).png",
  "Named_Titles/3in1D (World) (Erwin's Collection).png",
  "Named_Titles/3in1E (World) (Erwin's Collection).png",
  "Named_Titles/ABAsm DP1 (World) (Program) (Erwin's Collection).png",
  "Named_Titles/APara (World) (Erwin's Collection).png",
  "Named_Titles/ARDUBULLETs (World) (v0.10).png",
  "Named_Titles/ARDUBULLETs (World) (v0.11) (Alt).png",
  "Named_Titles/ARDUBULLETs (World) (v0.11) (Erwin's Collection).png",
  "Named_Titles/ARDUBULLETs (World) (v0.11).png",
  "Named_Titles/ARtillery (World) (Erwin's Collection).png",
  "Named_Titles/ARtillery (World) (v1).png",
  "Named_Titles/ASTEROIDS (World) (Erwin's Collection).png",
  "Named_Titles/ASTEROIDS (World) (FP).png",
  "Named_Titles/ASTEROIDS (World) (ST).png",
  "Named_Titles/AbSynth FM (World) (Program) (Erwin's Collection).png",
  "Named_Titles/AbSynth FM (World) (v2.0) (Program).png",
  "Named_Titles/Abshell (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Arcodia (World) (Erwin's Collection).png",
  "Named_Titles/Arcodia (World) (v1.0).png",
  "Named_Titles/Ard-Drivin (World) (Erwin's Collection).png",
  "Named_Titles/Ardletics (World) (Erwin's Collection).png",
  "Named_Titles/Ardu Buggy (World) (v1.0) (Erwin's Collection).png",
  "Named_Titles/Ardu Turf Masters (World) (Erwin's Collection).png",
  "Named_Titles/Ardu-Racer (World) (Erwin's Collection).png",
  "Named_Titles/Ardu-Racer (World) (v1.0).png",
  "Named_Titles/Ardu-Racer (World) (v1.1).png",
  "Named_Titles/Ardu-Racer (World) (v1.2).png",
  "Named_Titles/Ardu-Racer (World) (v1.3).png",
  "Named_Titles/Ardu-Whack (World) (Erwin's Collection).png",
  "Named_Titles/Ardu-Whack (World) (v1.1).png",
  "Named_Titles/Ardu-Whack (World) (v1.2).png",
  "Named_Titles/Ardu-man (World) (Erwin's Collection).png",
  "Named_Titles/ArduBOYNG (World) (Erwin's Collection).png",
  "Named_Titles/ArduBall (World) (Erwin's Collection).png",
  "Named_Titles/ArduBall (World) (v1.0).png",
  "Named_Titles/ArduBrain (World) (Program) (Erwin's Collection).png",
  "Named_Titles/ArduBrain (World) (Program).png",
  "Named_Titles/ArduCC (World) (Program) (Erwin's Collection).png",
  "Named_Titles/ArduCC (World) (v1.0) (Program).png",
  "Named_Titles/ArduGods (World).png",
  "Named_Titles/ArduIndy (World) (Erwin's Collection).png",
  "Named_Titles/ArduIndy (World) (v2.50).png",
  "Named_Titles/ArduLO (World) (Erwin's Collection).png",
  "Named_Titles/ArduLO (World) (v1.0).png",
  "Named_Titles/ArduMetronome (World) (Program) (Erwin's Collection).png",
  "Named_Titles/ArduMetronome (World) (v1.0.0) (Program).png",
  "Named_Titles/ArduMetronome (World) (v1.1.0) (Program).png",
  "Named_Titles/ArduRemote (World) (Program) (Erwin's Collection).png",
  "Named_Titles/ArduRemote (World) (v0.1) (Program).png",
  "Named_Titles/ArduSaver (World) (Program) (Erwin's Collection).png",
  "Named_Titles/ArduSaver (World) (Program).png",
  "Named_Titles/ArduTosh (World) (Program) (Erwin's Collection).png",
  "Named_Titles/ArduTosh (World) (v1.0) (Program).png",
  "Named_Titles/ArduTosh (World) (v1.0.1) (Program).png",
  "Named_Titles/ArduTosh (World) (v1.0.2) (Program).png",
  "Named_Titles/Arduboy Assistant (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Arduboy Assistant (World) (v2.0) (Program).png",
  "Named_Titles/Arduboy Gamepad (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Arduboy Says (World) (Erwin's Collection).png",
  "Named_Titles/Arduboy Says (World) (Update 2).png",
  "Named_Titles/Arduboy Sprite Editor (World) (v0.3) (Program) (Erwin's Collection).png",
  "Named_Titles/Arduboy Sprite Editor (World) (v0.3) (Program).png",
  "Named_Titles/ArduboyLife (World) (Erwin's Collection).png",
  "Named_Titles/ArduboyLife (World) (v2.0).png",
  "Named_Titles/Arducross (World) (Erwin's Collection).png",
  "Named_Titles/Ardulem (World) (Erwin's Collection).png",
  "Named_Titles/Ardulem (World) (v1.0).png",
  "Named_Titles/Arduloop (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Arduminer (World) (Erwin's Collection).png",
  "Named_Titles/Arduminer (World) (v1.0).png",
  "Named_Titles/Arduminer (World) (v1.1).png",
  "Named_Titles/Arduslide (World) (Erwin's Collection).png",
  "Named_Titles/Ardusweeper (World) (Erwin's Collection).png",
  "Named_Titles/Ardynia (World) (Erwin's Collection).png",
  "Named_Titles/Ardynia (World).png",
  "Named_Titles/Armageddon (World) (Erwin's Collection).png",
  "Named_Titles/Atomic Puzzle Pack (World) (Erwin's Collection).png",
  "Named_Titles/Back to the Jungle (World) (Erwin's Collection).png",
  "Named_Titles/Bang! Bang! (World) (Erwin's Collection).png",
  "Named_Titles/Bangi (World) (Erwin's Collection).png",
  "Named_Titles/Battle for Zuthsrah (World) (Erwin's Collection).png",
  "Named_Titles/Beam 'Em Up (World) (Erwin's Collection).png",
  "Named_Titles/Biddy Watering (World) (Demo) (Erwin's Collection).png",
  "Named_Titles/BigBlackBox (World) (Erwin's Collection).png",
  "Named_Titles/BiriBiriBeat (World) (Erwin's Collection).png",
  "Named_Titles/Blackjack (World) (Erwin's Collection).png",
  "Named_Titles/Blackjack (World) (v1.0).png",
  "Named_Titles/Blackjack (World).png",
  "Named_Titles/Blocks (World) (Erwin's Collection).png",
  "Named_Titles/Boids (World) (Erwin's Collection).png",
  "Named_Titles/Bombzzle (World) (Erwin's Collection).png",
  "Named_Titles/Boris Goes Skiing (World) (Erwin's Collection).png",
  "Named_Titles/Boris Goes Skiing (World) (v1.0).png",
  "Named_Titles/Bounce! (World) (Erwin's Collection).png",
  "Named_Titles/Bounce (World) (v1.0).png",
  "Named_Titles/Bounce (World) (v1.1).png",
  "Named_Titles/Box Stacker (World) (Erwin's Collection).png",
  "Named_Titles/Breakout-V (World) (Erwin's Collection).png",
  "Named_Titles/Breakout-V (World).png",
  "Named_Titles/BurgardTime (World) (Erwin's Collection).png",
  "Named_Titles/BurgardTime (World).png",
  "Named_Titles/CastleBoy (World) (Erwin's Collection).png",
  "Named_Titles/Catacombs of the Damned (World) (Erwin's Collection).png",
  "Named_Titles/Catacombs of the Damned (World) (v0.1) (Demo).png",
  "Named_Titles/Catacombs of the Damned (World) (v1.0).png",
  "Named_Titles/Chicken Launcher (World) (Erwin's Collection).png",
  "Named_Titles/Chicken Launcher (World) (v1.1).png",
  "Named_Titles/Chirp (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Chirp (World) (Program).png",
  "Named_Titles/Choplifter (World) (Erwin's Collection).png",
  "Named_Titles/Choplifter (World) (FX Enhanced).png",
  "Named_Titles/Choplifter (World) (v1.1.1).png",
  "Named_Titles/Chri-Bocchi Cat (World) (v0.03) (Erwin's Collection).png",
  "Named_Titles/Chri-Bocchi Cat (World) (v0.04).png",
  "Named_Titles/Chrome Dino (World) (Erwin's Collection).png",
  "Named_Titles/Chrome Dino (World).png",
  "Named_Titles/Chrome Dino - Halloween (World) (Erwin's Collection).png",
  "Named_Titles/Cistercia (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Coder's Toolbox (World) (FX Enhanced) (Program).png",
  "Named_Titles/Coder's Toolbox (World) (Program) (Erwin's Collection).png",
  "Named_Titles/CosmicPods (World) (Erwin's Collection).png",
  "Named_Titles/CowBro (World) (Erwin's Collection).png",
  "Named_Titles/CowBro (World).png",
  "Named_Titles/Crabator (World) (Erwin's Collection).png",
  "Named_Titles/Crate Confusion (World) (Erwin's Collection).png",
  "Named_Titles/Crate Confusion (World).png",
  "Named_Titles/Crates 3D (World) (Erwin's Collection).png",
  "Named_Titles/Crates 3D (World) (v1.0).png",
  "Named_Titles/Crawl, The (World) (v1.01).png",
  "Named_Titles/CrazyKart (World) (Erwin's Collection).png",
  "Named_Titles/Cribbage (World) (Erwin's Collection).png",
  "Named_Titles/Cribbage (World) (v1.02).png",
  "Named_Titles/Cripple Mr Onion (World) (Erwin's Collection).png",
  "Named_Titles/Cripple Mr Onion (World) (v1.0).png",
  "Named_Titles/CyberHack (World) (Erwin's Collection).png",
  "Named_Titles/DanceRow (World) (Erwin's Collection).png",
  "Named_Titles/Deep Dish Nine (World) (Erwin's Collection).png",
  "Named_Titles/Defenduino (World) (v1.0).png",
  "Named_Titles/Defenduino (World) (v1.1).png",
  "Named_Titles/Defenduino (World) (v1.2) (Erwin's Collection).png",
  "Named_Titles/Defenduino (World) (v1.2).png",
  "Named_Titles/Diamonds (World) (Erwin's Collection).png",
  "Named_Titles/Dice of Fate (World) (No QR Code) (Program).png",
  "Named_Titles/Dice of Fate (World) (Program).png",
  "Named_Titles/Dice of Fate (World) (v1.7.2) (Program).png",
  "Named_Titles/Digger (World) (Erwin's Collection).png",
  "Named_Titles/Do You Remember Love (World) (Erwin's Collection).png",
  "Named_Titles/Dominoes 'All Fives' (World) (Erwin's Collection).png",
  "Named_Titles/Electronic Quarterback (World) (Erwin's Collection).png",
  "Named_Titles/Epic Mini Games (World) (Erwin's Collection).png",
  "Named_Titles/Evade (World) (Erwin's Collection).png",
  "Named_Titles/Evade 2 (World) (Erwin's Collection).png",
  "Named_Titles/Fanboat (World) (Erwin's Collection).png",
  "Named_Titles/Farkle (World) (Erwin's Collection).png",
  "Named_Titles/Fatsche (World) (Erwin's Collection).png",
  "Named_Titles/Fire Panic (World) (Alt).png",
  "Named_Titles/Fire Panic (World) (Erwin's Collection).png",
  "Named_Titles/Flappy Ball (World) (Erwin's Collection).png",
  "Named_Titles/Flappy Birdie (World) (Erwin's Collection).png",
  "Named_Titles/Flood Fill (World) (Erwin's Collection).png",
  "Named_Titles/Fluffle's Rainy Day (World).png",
  "Named_Titles/Galaxion (World) (Erwin's Collection).png",
  "Named_Titles/Game of Life (World) (Erwin's Collection).png",
  "Named_Titles/Games'N Goblins - The Game (World) (Erwin's Collection).png",
  "Named_Titles/German Whist (World) (Erwin's Collection).png",
  "Named_Titles/Glove (World) (Erwin's Collection).png",
  "Named_Titles/Graph (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Graph 2 (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Hangman! (World) (Erwin's Collection).png",
  "Named_Titles/Harambe's Revenge (World) (Erwin's Collection).png",
  "Named_Titles/Helii (World) (Erwin's Collection).png",
  "Named_Titles/Hello, Commander (World) (Erwin's Collection).png",
  "Named_Titles/Hollow Seeker (World) (v0.31) (Erwin's Collection).png",
  "Named_Titles/Hollow Seeker (World) (v0.32).png",
  "Named_Titles/Hopper (World) (v0.21) (Erwin's Collection).png",
  "Named_Titles/Hopper (World) (v0.22).png",
  "Named_Titles/Humanity Revenge DC (World) (Erwin's Collection).png",
  "Named_Titles/IDOUDO (World) (Erwin's Collection).png",
  "Named_Titles/Invaders (World) (Erwin's Collection).png",
  "Named_Titles/Is This Loss - The Game (World) (Erwin's Collection).png",
  "Named_Titles/Jet Pac (World) (Erwin's Collection).png",
  "Named_Titles/Jezzball (World) (Erwin's Collection).png",
  "Named_Titles/Joustish (World) (Erwin's Collection).png",
  "Named_Titles/JumpBoy (World) (Erwin's Collection).png",
  "Named_Titles/Juno First (World) (v1.00) (Erwin's Collection).png",
  "Named_Titles/Juno First (World) (v1.01).png",
  "Named_Titles/Karateka (World) (Erwin's Collection).png",
  "Named_Titles/Karateka (World) (FX Enhanced).png",
  "Named_Titles/Karateka (World) (v0.9) (Alt).png",
  "Named_Titles/Karateka (World) (v0.9).png",
  "Named_Titles/Kemono Patrol (World) (Erwin's Collection).png",
  "Named_Titles/KeyKat - I.T. (World) (Erwin's Collection).png",
  "Named_Titles/Knight Move (World) (v0.10).png",
  "Named_Titles/Knight Move (World) (v0.11) (Alt).png",
  "Named_Titles/Knight Move (World) (v0.11) (Erwin's Collection).png",
  "Named_Titles/Knight Move (World) (v0.11).png",
  "Named_Titles/Kong (World) (Erwin's Collection).png",
  "Named_Titles/Kong (World) (v1.0.4).png",
  "Named_Titles/Kong II (World) (v1.0.0) (Erwin's Collection).png",
  "Named_Titles/Kooky Kookies (World) (v1.1) (Erwin's Collection).png",
  "Named_Titles/Kooky Kookies (World) (v1.2).png",
  "Named_Titles/Kung Fu Escape (World) (Erwin's Collection).png",
  "Named_Titles/LATE (World) (Erwin's Collection).png",
  "Named_Titles/Lagunita (World).png",
  "Named_Titles/Lasers (World) (v0.11) (Alt).png",
  "Named_Titles/Lasers (World) (v0.11) (Erwin's Collection).png",
  "Named_Titles/Lasers (World) (v0.11).png",
  "Named_Titles/Lasers (World) (v0.12).png",
  "Named_Titles/Leanna the Lion (World) (v1.1) (Erwin's Collection).png",
  "Named_Titles/Leanna the Lion (World) (v1.2).png",
  "Named_Titles/Light Meter (World) (Erwin's Collection).png",
  "Named_Titles/Lite Out (World) (Erwin's Collection).png",
  "Named_Titles/Little Rook Chess (World) (Erwin's Collection).png",
  "Named_Titles/Lode Runner (World) (v1.04) (Levels 1 to 40) (Erwin's Collection).png",
  "Named_Titles/Lode Runner (World) (v1.04) (Levels 121 to 154) (Erwin's Collection).png",
  "Named_Titles/Lode Runner (World) (v1.04) (Levels 41 to 80) (Erwin's Collection).png",
  "Named_Titles/Lode Runner (World) (v1.04) (Levels 81 to 120) (Erwin's Collection).png",
  "Named_Titles/Love Tester (World) (Program) (Erwin's Collection).png",
  "Named_Titles/LoveRush (World) (v1.1.1) (Erwin's Collection).png",
  "Named_Titles/LoveRush (World) (v1.1.2).png",
  "Named_Titles/MallARD Hunt (World).png",
  "Named_Titles/MayQ (World) (Erwin's Collection).png",
  "Named_Titles/MazezaM (World) (Erwin's Collection).png",
  "Named_Titles/Mazogs (World) (Erwin's Collection).png",
  "Named_Titles/MicroCheckers (World) (Erwin's Collection).png",
  "Named_Titles/MicroCity (World) (Erwin's Collection).png",
  "Named_Titles/MicroTD (World) (v1.01) (Erwin's Collection).png",
  "Named_Titles/MicroTank (World) (Erwin's Collection).png",
  "Named_Titles/Millipe (World) (Erwin's Collection).png",
  "Named_Titles/Minesweeper (World) (Erwin's Collection).png",
  "Named_Titles/Miss Snake (World) (Erwin's Collection).png",
  "Named_Titles/Monpals (World).png",
  "Named_Titles/Nanoseq (World) (Erwin's Collection).png",
  "Named_Titles/Night Raid (World) (Erwin's Collection).png",
  "Named_Titles/Ninja Fuzzgrawth (World) (Erwin's Collection).png",
  "Named_Titles/Nomis (World) (Erwin's Collection).png",
  "Named_Titles/Not Just a Hat Rack (World) (Erwin's Collection).png",
  "Named_Titles/NumberMind (World) (Erwin's Collection).png",
  "Named_Titles/Oh Mummy (World) (Erwin's Collection).png",
  "Named_Titles/Oh, You're Gunna Die (World) (Erwin's Collection).png",
  "Named_Titles/Oil Panic (World) (Erwin's Collection).png",
  "Named_Titles/OktaArduToken (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Omega Horizon (World) (Erwin's Collection).png",
  "Named_Titles/Omega Horizon (World) (v1.3).png",
  "Named_Titles/Orbs (World) (Erwin's Collection).png",
  "Named_Titles/PAC-Tastic (World) (Erwin's Collection).png",
  "Named_Titles/PI 24k (World) (v0.03) (Program) (Alt).png",
  "Named_Titles/PI 24k (World) (v0.03) (Program) (Erwin's Collection).png",
  "Named_Titles/PI 24k (World) (v0.03) (Program).png",
  "Named_Titles/Paqman (World) (Erwin's Collection).png",
  "Named_Titles/Petit of the Dead (World) (Erwin's Collection).png",
  "Named_Titles/Petitseq (World) (Erwin's Collection).png",
  "Named_Titles/PiCross (World) (Erwin's Collection).png",
  "Named_Titles/Picovaders (World) (Erwin's Collection).png",
  "Named_Titles/Pipes (World) (Erwin's Collection).png",
  "Named_Titles/Pocket Fighter (World) (Erwin's Collection).png",
  "Named_Titles/Pocket Othello (World) (Erwin's Collection).png",
  "Named_Titles/Pocket PDA (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Poitto (World) (Erwin's Collection).png",
  "Named_Titles/Pong (World) (Erwin's Collection).png",
  "Named_Titles/Poop Panic! (World) (Erwin's Collection).png",
  "Named_Titles/Psi Colo (World) (v0.11).png",
  "Named_Titles/Quadrastic (World) (Erwin's Collection).png",
  "Named_Titles/Quarto! (World) (v0.10) (Alt).png",
  "Named_Titles/Quarto! (World) (v0.10) (Erwin's Collection).png",
  "Named_Titles/Quarto! (World) (v0.10).png",
  "Named_Titles/Randocity (World) (Erwin's Collection).png",
  "Named_Titles/Ravine Despoiler (World) (Erwin's Collection).png",
  "Named_Titles/Rayne the Rogue (World) (Erwin's Collection).png",
  "Named_Titles/Rayne the Rogue (World) (No QR Code).png",
  "Named_Titles/Rayne the Rogue (World) (v2.9).png",
  "Named_Titles/Reversi (World) (v0.10) (Erwin's Collection).png",
  "Named_Titles/Reversi (World) (v0.11).png",
  "Named_Titles/Rick and Morty Game (World) (Erwin's Collection).png",
  "Named_Titles/Ring Puzzle (World) (Erwin's Collection).png",
  "Named_Titles/Road Trip (World) (Erwin's Collection).png",
  "Named_Titles/RoboDodge (World) (Erwin's Collection).png",
  "Named_Titles/Rogue (World) (v1.21) (Erwin's Collection).png",
  "Named_Titles/Roo Run (World) (Erwin's Collection).png",
  "Named_Titles/Rooftop Rescue (World) (Erwin's Collection).png",
  "Named_Titles/Roshambo (World) (Erwin's Collection).png",
  "Named_Titles/SFCave (World) (Erwin's Collection).png",
  "Named_Titles/SFZ (World) (Erwin's Collection).png",
  "Named_Titles/SIEGE (World) (v1.1).png",
  "Named_Titles/SNAKE (World) (CDRXavier) (Erwin's Collection).png",
  "Named_Titles/SNAKE (World) (CDRXavier).png",
  "Named_Titles/SameGame (World) (v0.10) (Alt).png",
  "Named_Titles/SameGame (World) (v0.10) (Erwin's Collection).png",
  "Named_Titles/SameGame (World) (v0.10).png",
  "Named_Titles/SanSan (World) (Erwin's Collection).png",
  "Named_Titles/Santa's Happy Little Packer (World) (Erwin's Collection).png",
  "Named_Titles/Sensitive (World) (Erwin's Collection).png",
  "Named_Titles/SetSystemEEPROM (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Siege (World) (Erwin's Collection).png",
  "Named_Titles/SnELk (World) (Erwin's Collection).png",
  "Named_Titles/Snake (World) (Stu) (Erwin's Collection).png",
  "Named_Titles/Solitaire (World) (Erwin's Collection).png",
  "Named_Titles/Space Battle - Trench Run (World) (v1.1) (Erwin's Collection).png",
  "Named_Titles/Space Cab (World) (v1.0) (Erwin's Collection).png",
  "Named_Titles/Space Fighter (World) (Erwin's Collection).png",
  "Named_Titles/Space Invaders (World) (Erwin's Collection).png",
  "Named_Titles/Space Knife (World) (Erwin's Collection).png",
  "Named_Titles/Space Quarth (World) (Erwin's Collection).png",
  "Named_Titles/Square Nose (World) (Erwin's Collection).png",
  "Named_Titles/Squario (World) (Erwin's Collection).png",
  "Named_Titles/Stairs Sweep (World) (v0.10) (Alt).png",
  "Named_Titles/Stairs Sweep (World) (v0.10) (Erwin's Collection).png",
  "Named_Titles/Stairs Sweep (World) (v0.10).png",
  "Named_Titles/Star Honor (World) (Erwin's Collection).png",
  "Named_Titles/Starduino Turbo (World) (Erwin's Collection).png",
  "Named_Titles/Stellar Impact (World) (Erwin's Collection).png",
  "Named_Titles/Sudoku-NBP (World) (Erwin's Collection).png",
  "Named_Titles/Super Crate Buino (World) (Erwin's Collection).png",
  "Named_Titles/TV Tuner (World) (Program) (Erwin's Collection).png",
  "Named_Titles/Tackle Box (World) (v1.2.0) (Erwin's Collection).png",
  "Named_Titles/Tamaguino-AB (World) (Erwin's Collection).png",
  "Named_Titles/Techno Monkey (World) (Erwin's Collection).png",
  "Named_Titles/Techno Monkey (World) (v1.0).png",
  "Named_Titles/Tetris (World) (Erwin's Collection).png",
  "Named_Titles/TicTacCurly (World) (Erwin's Collection).png",
  "Named_Titles/Tiny Asteroids (World) (Erwin's Collection).png",
  "Named_Titles/Tiny Depth (World) (Erwin's Collection).png",
  "Named_Titles/Tiny Digital Invader (World) (Erwin's Collection).png",
  "Named_Titles/Tiny Lander (World) (v1.0) (Erwin's Collection).png",
  "Named_Titles/Tiny NS-Tower (World) (Erwin's Collection).png",
  "Named_Titles/Tiny Sokoban (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Bert (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Bike (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-DDug (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Missile (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Morpion (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Pipe (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Plaque (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Trick (World) (Erwin's Collection).png",
  "Named_Titles/Tiny-Tris (World) (Erwin's Collection).png",
  "Named_Titles/To (World) (Erwin's Collection).png",
  "Named_Titles/Tower of Pain (World) (v1.2.2).png",
  "Named_Titles/Train Dodge (World) (Erwin's Collection).png",
  "Named_Titles/Tres (World) (Erwin's Collection).png",
  "Named_Titles/Tris (World) (Erwin's Collection).png",
  "Named_Titles/Turtle Bridge (World) (v1.0) (Erwin's Collection).png",
  "Named_Titles/Turtle Bridge (World) (v1.3).png",
  "Named_Titles/Twotris (World) (Erwin's Collection).png",
  "Named_Titles/Ufo-Race (World) (Erwin's Collection).png",
  "Named_Titles/Umeroose (World) (Erwin's Collection).png",
  "Named_Titles/Under the Tower (World) (Erwin's Collection).png",
  "Named_Titles/Unicorn Dash (World) (Erwin's Collection).png",
  "Named_Titles/Virtual Gamepad (World) (Program) (Erwin's Collection).png",
  "Named_Titles/WHG (World) (Erwin's Collection).png",
  "Named_Titles/Waternet (World) (Erwin's Collection).png",
  "Named_Titles/Yatzy (World) (Erwin's Collection).png",
  "Named_Titles/Yatzy (World) (v1.3).png",
  "Named_Titles/You Won't Survive (World) (Erwin's Collection).png",
  "Named_Titles/Zoo (World) (Erwin's Collection).png",
  "Named_Titles/Zoo at Midnight (World) (Erwin's Collection).png",
  "Named_Titles/ZooEscape (World) (Erwin's Collection).png",
}
