return {
  "Named_Boxarts/Floppy Bird.png",
  "Named_Snaps/Bunnymark.png",
  "Named_Snaps/Floppy Bird.png",
  "Named_Snaps/FloppyBird.png",
  "Named_Snaps/Game of Life.png",
  "Named_Snaps/GameOfLife.png",
  "Named_Snaps/JSTest.png",
  "Named_Snaps/Launcher.png",
  "Named_Snaps/Nyan Cat.png",
  "Named_Snaps/NyanCat.png",
  "Named_Snaps/Snake.png",
  "Named_Titles/Bunnymark.png",
  "Named_Titles/Floppy Bird.png",
  "Named_Titles/FloppyBird.png",
  "Named_Titles/GameOfLife.png",
  "Named_Titles/JSTest.png",
  "Named_Titles/Launcher.png",
  "Named_Titles/NyanCat.png",
  "Named_Titles/Snake.png",
}
