return {
  "Named_Snaps/17 und 4 (1978)(-)(DE).png",
  "Named_Snaps/ASCII Chase (2017-06-01)(Caruso, Fabrizio).png",
  "Named_Snaps/Abacus Competition (19xx)(-).png",
  "Named_Snaps/Acey Deucy (1980)(-).png",
  "Named_Snaps/Acigol (1980)(-).png",
  "Named_Snaps/Adventure (1979-05-15)(Jessee, Jeff - Adams, Scott).png",
  "Named_Snaps/Arrow (1980)(Butterfield, Jim).png",
  "Named_Snaps/Artillery (1979)(Creative Computing Software).png",
  "Named_Snaps/Atlantic Patrol (1978)(-).png",
  "Named_Snaps/Battleship (1978)(Richter, M.).png",
  "Named_Snaps/Blockade Special (1981)(Winkler, Gil).png",
  "Named_Snaps/Bomber (1979-07-06)(Gleason, Arne).png",
  "Named_Snaps/Bomber (19xx)(-)(DE).png",
  "Named_Snaps/Breakout (1980)(-).png",
  "Named_Snaps/Brick Wall (1980)(Dawson).png",
  "Named_Snaps/Buggy (1979)(Finzer, Bill).png",
  "Named_Snaps/Carrace II (19xx)(PUG).png",
  "Named_Snaps/Casino Blackjack 5.7 (1979)(CMS Software).png",
  "Named_Snaps/Chess Game (19xx)(-).png",
  "Named_Snaps/Civil War (19xx)(Creative Computing Morristown).png",
  "Named_Snaps/Concord Landing Simulation (1980)(-).png",
  "Named_Snaps/Cosmic Cosmiads (1981)(-).png",
  "Named_Snaps/Cosmic Fighter (1982)(MS Software).png",
  "Named_Snaps/Crazy Balloon (1980)(-).png",
  "Named_Snaps/Dam Buster (1980)(Williams, Evan).png",
  "Named_Snaps/Draw Poker 1 (1978)(Commodore).png",
  "Named_Snaps/Fluglandung (19xx)(-)(DE).png",
  "Named_Snaps/Microchess 2.0 (1978)(Jennings, Peter).png",
  "Named_Snaps/PET Checkers (19xx)(CMS Software).png",
  "Named_Snaps/PET Super Baseball v7.4 (1983-07-13)(Suzuki, J. - Bradley, D.).png",
  "Named_Snaps/Schlange (19xx)(-)(DE).png",
  "Named_Snaps/Space Invaders (19xx)(-).png",
  "Named_Snaps/Space War (19xx)(-).png",
  "Named_Snaps/Sternenfalle (19xx)(-)(DE).png",
  "Named_Snaps/Vier op een rij (19xx)(Nuland, T. van)(nl).png",
  "Named_Titles/17 und 4 (1978)(-)(DE).png",
  "Named_Titles/ASCII Chase (2017-06-01)(Caruso, Fabrizio).png",
  "Named_Titles/Abacus Competition (19xx)(-).png",
  "Named_Titles/Acey Deucy (1980)(-).png",
  "Named_Titles/Acigol (1980)(-).png",
  "Named_Titles/Adventure (1979-05-15)(Jessee, Jeff - Adams, Scott).png",
  "Named_Titles/Arrow (1980)(Butterfield, Jim).png",
  "Named_Titles/Artillery (1979)(Creative Computing Software).png",
  "Named_Titles/Atlantic Patrol (1978)(-).png",
  "Named_Titles/Battleship (1978)(Richter, M.).png",
  "Named_Titles/Blockade Special (1981)(Winkler, Gil).png",
  "Named_Titles/Bomber (1979-07-06)(Gleason, Arne).png",
  "Named_Titles/Bomber (19xx)(-)(DE).png",
  "Named_Titles/Breakout (1980)(-).png",
  "Named_Titles/Brick Wall (1980)(Dawson).png",
  "Named_Titles/Buggy (1979)(Finzer, Bill).png",
  "Named_Titles/Carrace II (19xx)(PUG).png",
  "Named_Titles/Casino Blackjack 5.7 (1979)(CMS Software).png",
  "Named_Titles/Chess Game (19xx)(-).png",
  "Named_Titles/Civil War (19xx)(Creative Computing Morristown).png",
  "Named_Titles/Concord Landing Simulation (1980)(-).png",
  "Named_Titles/Cosmic Cosmiads (1981)(-).png",
  "Named_Titles/Cosmic Fighter (1982)(MS Software).png",
  "Named_Titles/Crazy Balloon (1980)(-).png",
  "Named_Titles/Dam Buster (1980)(Williams, Evan).png",
  "Named_Titles/Draw Poker 1 (1978)(Commodore).png",
  "Named_Titles/Fluglandung (19xx)(-)(DE).png",
  "Named_Titles/Microchess 2.0 (1978)(Jennings, Peter).png",
  "Named_Titles/PET Checkers (19xx)(CMS Software).png",
  "Named_Titles/PET Super Baseball v7.4 (1983-07-13)(Suzuki, J. - Bradley, D.).png",
  "Named_Titles/Schlange (19xx)(-)(DE).png",
  "Named_Titles/Space Invaders (19xx)(-).png",
  "Named_Titles/Space War (19xx)(-).png",
  "Named_Titles/Sternenfalle (19xx)(-)(DE).png",
  "Named_Titles/Vier op een rij (19xx)(Nuland, T. van)(nl).png",
}
