return {
  "Named_Boxarts/ATR - All Terrain Racing (1995)(Team 17)[!].png",
  "Named_Boxarts/ATR - All Terrain Racing (Europe) (jewel).png",
  "Named_Boxarts/ATR - All Terrain Racing (Europe).png",
  "Named_Boxarts/Akira (1994)(ICE)[!].png",
  "Named_Boxarts/Akira (Europe).png",
  "Named_Boxarts/Alfred Chicken (1993)(Mindscape)[!].png",
  "Named_Boxarts/Alfred Chicken (Europe).png",
  "Named_Boxarts/Alien Breed - Tower Assault (1994)(Team 17)[!].png",
  "Named_Boxarts/Alien Breed - Tower Assault (Europe) (jewel).png",
  "Named_Boxarts/Alien Breed - Tower Assault (Europe).png",
  "Named_Boxarts/Alien Breed 3D (1995)(Ocean - Team 17)[!][cp code].png",
  "Named_Boxarts/Alien Breed 3D (Europe).png",
  "Named_Boxarts/Alien Breed Special Edition _ Qwak (1994)(Team 17)[!][compilation].png",
  "Named_Boxarts/Alien Breed Special Edition _ Qwak (Europe) (En,Fr,De,It,Da).png",
  "Named_Boxarts/Amiga CD! Magazine No. 1 (UK).png",
  "Named_Boxarts/Amiga CD! Magazine No. 2 (UK).png",
  "Named_Boxarts/Amiga CD! Magazine No. 3 (UK).png",
  "Named_Boxarts/Amiga CD32 - Issue 1 (Spring) (UK).png",
  "Named_Boxarts/Amiga CD32 - Issue 2 (Winter) (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 01 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 02 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 03 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 04 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 05 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 06 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 07 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 08 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 09 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 10 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 11 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 12 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 13 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 14 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 15 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 16 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 17 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 18 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 19 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 20 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 21 (UK).png",
  "Named_Boxarts/Amiga CD32 Gamer Vol. 22 (UK).png",
  "Named_Boxarts/Amiga CD32 Special 1 (1994-12-08)(Paragon Publishing)(GB)[!][Lamborghini American Challenge].png",
  "Named_Boxarts/Amiga CD32 Special 2 (1995-01-12)(Paragon Publishing)(GB)[!][Quik The Thunder Rabbit].png",
  "Named_Boxarts/Amiga CD32 Special 3 (1995-04)(Paragon Publishing)(GB)[!][Vital Light].png",
  "Named_Boxarts/Amiga Christmas Crackers (AmigaJay).png",
  "Named_Boxarts/Amiga Power - Games Massive Volume 1 (UK).png",
  "Named_Boxarts/Amiga Workbench 3.0 (Europe).png",
  "Named_Boxarts/Apidya (Europe).png",
  "Named_Boxarts/Arabian Nights (1993)(Buzz)(M4)[!].png",
  "Named_Boxarts/Arabian Nights (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Arcade Pool (1994)(Team 17)[!][CDD4978].png",
  "Named_Boxarts/Arcade Pool (1994)(Team 17)[!][CDR00281].png",
  "Named_Boxarts/Arcade Pool (Europe) (En,Fr,De,It) (Alt).png",
  "Named_Boxarts/Arcade Pool (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Assassins - Ultimate Games Compact Disc (Europe) (v2.0).png",
  "Named_Boxarts/Banshee (1994)(Core)(M4)[!].png",
  "Named_Boxarts/Banshee (Europe) (En,Fr,De,Da).png",
  "Named_Boxarts/Base Jumpers (1995)(Rasputin)[!].png",
  "Named_Boxarts/Base Jumpers (Europe).png",
  "Named_Boxarts/Battle Chess (1994)(Interplay)[!].png",
  "Named_Boxarts/Battle Chess (Europe).png",
  "Named_Boxarts/Battletoads (1994)(Mindscape)[!].png",
  "Named_Boxarts/Battletoads (Europe).png",
  "Named_Boxarts/Beavers (1994)(Unique)[!].png",
  "Named_Boxarts/Beavers (Europe).png",
  "Named_Boxarts/Beneath a Steel Sky (1994)(Virgin)(M4)[!].png",
  "Named_Boxarts/Beneath a Steel Sky (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Benefactor (1994)(Psygnosis)[!].png",
  "Named_Boxarts/Benefactor (Europe) (fake jewel).png",
  "Named_Boxarts/Benefactor (Europe).png",
  "Named_Boxarts/Big 6, The (Europe).png",
  "Named_Boxarts/Big 6, The - Original Dizzy Adventure Games (1994)(Codemasters)[!][compilation].png",
  "Named_Boxarts/Bitmap Brothers Collection, The (AGA) (AmigaJay).png",
  "Named_Boxarts/Bitmap Brothers Collection, The (OCS) (AmigaJay).png",
  "Named_Boxarts/Black Viper (1996)(NEO)(M3)[!][Amiga-CD32].png",
  "Named_Boxarts/Black Viper (1996)(Neo)(M3).png",
  "Named_Boxarts/Black Viper (Europe) (En,De,It) (fake jewel).png",
  "Named_Boxarts/Black Viper (Europe) (En,De,It).png",
  "Named_Boxarts/Brian the Lion (Europe) (En,Fr,De,It) (Gameplay CD-ROM).png",
  "Named_Boxarts/Brian the Lion (Europe) (En,Fr,De,It) (fake jewel).png",
  "Named_Boxarts/Brian the Lion Starring in Rumble in the Jungle (1994)(Psygnosis)(M4)[!].png",
  "Named_Boxarts/Brutal - Paws of Fury (1995)(Gametek)(M3)[!].png",
  "Named_Boxarts/Brutal - Paws of Fury (Europe) (fake jewel).png",
  "Named_Boxarts/Brutal - Paws of Fury (Europe).png",
  "Named_Boxarts/Brutal Football (1994)(Millennium)[!].png",
  "Named_Boxarts/Brutal Football (Europe).png",
  "Named_Boxarts/Bubba 'N' Stix (1994)(Core)[!].png",
  "Named_Boxarts/Bubba 'n' Stix (Europe).png",
  "Named_Boxarts/Bubble Bobble Trilogy (AmigaJay).png",
  "Named_Boxarts/Bubble and Squeak (1994)(Audiogenic)[!].png",
  "Named_Boxarts/Bubble and Squeak (Europe) (fake jewel).png",
  "Named_Boxarts/Bubble and Squeak (Europe).png",
  "Named_Boxarts/Bump 'N' Burn (1994)(Grandslam)[!].png",
  "Named_Boxarts/Bump 'n' Burn (Europe).png",
  "Named_Boxarts/CD Exchange - Volume 1 (UK).png",
  "Named_Boxarts/Candy Puzzle (1996)(Gevin)[CUBO].png",
  "Named_Boxarts/Cannon Fodder (1993)(Virgin)[!][Amiga-CD32].png",
  "Named_Boxarts/Cannon Fodder (1993)(Virgin)[Amiga-CD32][a].png",
  "Named_Boxarts/Cannon Fodder (Europe).png",
  "Named_Boxarts/Castles II - Siege _ Conquest (1993)(Interplay)[!].png",
  "Named_Boxarts/Castles II - Siege _ Conquest (Europe).png",
  "Named_Boxarts/Cedric and the Lost Sceptre (Europe) (fake jewel).png",
  "Named_Boxarts/Cedric and the Lost Sceptre (Europe).png",
  "Named_Boxarts/Cedric and the lost sceptre (1996)(NEO)(de-en)[!][AGA-CD32].png",
  "Named_Boxarts/Center Court Tennis 2 (2016-07-21)(Fritsche, Gernot)(FW)[!].png",
  "Named_Boxarts/Chambers of Shaolin (1993)(Unique)[!].png",
  "Named_Boxarts/Chambers of Shaolin (Europe).png",
  "Named_Boxarts/Chaos Engine, The (1994)(Renegade)[!][CDD3445].png",
  "Named_Boxarts/Chaos Engine, The (1994)(Renegade)[!][Spectacular Voyage][CDD3446].png",
  "Named_Boxarts/Chaos Engine, The (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Chaos Engine, The (Europe) (Spectacular Voyage).png",
  "Named_Boxarts/Chuck Rock (1994)(Core)[!].png",
  "Named_Boxarts/Chuck Rock (Europe).png",
  "Named_Boxarts/Chuck Rock II - Son of Chuck (1994)(Core)[!].png",
  "Named_Boxarts/Chuck Rock II - Son of Chuck (Europe).png",
  "Named_Boxarts/Classic Lotus Trilogy, The (1994)(Gremlin)(PAL)[!][compilation].png",
  "Named_Boxarts/Classic Lotus Trilogy, The (Europe).png",
  "Named_Boxarts/Clockwiser (1994)(Rasputin)[!].png",
  "Named_Boxarts/Clockwiser (Europe).png",
  "Named_Boxarts/Clou!, Der (Germany).png",
  "Named_Boxarts/Clue!, The (1994)(Kompart)[!].png",
  "Named_Boxarts/Communicator (Germany) (En,De).png",
  "Named_Boxarts/D-Generation (Europe).png",
  "Named_Boxarts/D-Generation v1.0 (1993)(Mindscape)[!].png",
  "Named_Boxarts/D-Generation v1.0 (1993)(Mindscape)[b].png",
  "Named_Boxarts/Dangerous Streets (1993)(Flair Software)[!].png",
  "Named_Boxarts/Dangerous Streets (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Dangerous Streets _ Wing Commander (1993)(Commodore)[!][compilation].png",
  "Named_Boxarts/Dangerous Streets _ Wing Commander (Europe) (En,Fr,De,It) (alt jewel).png",
  "Named_Boxarts/Dangerous Streets _ Wing Commander (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Darkseed (Europe).png",
  "Named_Boxarts/Darkseed v1.1 (1994)(Cyberdreams)[!].png",
  "Named_Boxarts/Death Mask (1994)(Alternative Software)[!].png",
  "Named_Boxarts/Death Mask (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Deep Core (Europe) (v1.00).png",
  "Named_Boxarts/Deep Core (Europe) (v1.01).png",
  "Named_Boxarts/Deep Core v1.00 (1993)(ICE)[!][CDD2840].png",
  "Named_Boxarts/Deep Core v1.01 (1993)(ICE)[!][CDD2998].png",
  "Named_Boxarts/Defender of the Crown II (Europe).png",
  "Named_Boxarts/Defender of the Crown II (USA).png",
  "Named_Boxarts/Demo Disc, The - Commodore Amiga CD32 Demonstration Disc 2.0 (Europe).png",
  "Named_Boxarts/Dennis (1993)(Ocean)[!].png",
  "Named_Boxarts/Dennis (Europe) (jewel).png",
  "Named_Boxarts/Dennis (Europe).png",
  "Named_Boxarts/Diggers (1993)(Millennium)(NTSC)[!].png",
  "Named_Boxarts/Diggers (Europe).png",
  "Named_Boxarts/Diggers _ Oscar (1993)(Commodore)[!][compilation][AMIGA-CD 31, 54].png",
  "Named_Boxarts/Diggers _ Oscar (1993)(Commodore)[!][compilation][AMIGA-CD-V2].png",
  "Named_Boxarts/Diggers _ Oscar (Europe) (Rev 1) (Alt).png",
  "Named_Boxarts/Diggers _ Oscar (Europe) (Rev 1).png",
  "Named_Boxarts/Diggers _ Oscar (Europe).png",
  "Named_Boxarts/Disposable Hero (1994)(Gremlin)(PAL)[!].png",
  "Named_Boxarts/Disposable Hero (Europe).png",
  "Named_Boxarts/Donk! The Samurai Duck! (1994)(Supervision)[!].png",
  "Named_Boxarts/Donk! The Samurai Duck! (1994)(Supervision)[a].png",
  "Named_Boxarts/Donk! The Samurai Duck! (Europe).png",
  "Named_Boxarts/Dragonstone (1995)(Core)(M3)[!].png",
  "Named_Boxarts/Dragonstone (Europe) (En,Fr,De).png",
  "Named_Boxarts/Emerald Mines (1994)(Almathera)[!][compilation][CDD4410].png",
  "Named_Boxarts/Emerald Mines (Europe).png",
  "Named_Boxarts/Erben der Erde (Europe).png",
  "Named_Boxarts/Erben der Erde - Die grosse Suche (1995)(Softgold)(DE)[!][Amiga-CD32-CDTV].png",
  "Named_Boxarts/Erben der Erde - Die grosse Suche (1995)(Softgold)(DE)[AGA-CD32].png",
  "Named_Boxarts/Exile (1995)(Audiogenic)[!].png",
  "Named_Boxarts/Exile (Europe) (fake jewel).png",
  "Named_Boxarts/Exile (Europe).png",
  "Named_Boxarts/F1 Collection (AmigaJay).png",
  "Named_Boxarts/Factor 5 Collection (AmigaJay).png",
  "Named_Boxarts/Fears (1995)(Guildhall Leisure Services)[!].png",
  "Named_Boxarts/Fears (1995)(attic)(DE)(en)[!].png",
  "Named_Boxarts/Fears (Europe).png",
  "Named_Boxarts/Fields of Glory (1994)(MicroProse)(M3)[!].png",
  "Named_Boxarts/Fields of Glory (Europe) (En,Fr,De).png",
  "Named_Boxarts/Fightin' Spirit (1996)(NEO)(M3)[!][Amiga-CD32].png",
  "Named_Boxarts/Fightin' Spirit (Europe) (En,De,It) (fake jewel).png",
  "Named_Boxarts/Fightin' Spirit (Europe) (En,De,It).png",
  "Named_Boxarts/Final Gate, The (1997)(Alternative Software - Bigg Wolf).png",
  "Named_Boxarts/Final Gate, The (Europe).png",
  "Named_Boxarts/Fire Force (1993)(Buzz)[!].png",
  "Named_Boxarts/Fire Force (Europe).png",
  "Named_Boxarts/Fire _ Ice - The Daring Adventures of Cool Coyote (1994)(Renegade)[!].png",
  "Named_Boxarts/Fire _ Ice - The Daring Adventures of Cool Coyote (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Flink (1994)(Psygnosis)[!].png",
  "Named_Boxarts/Flink (Europe) (fake jewel).png",
  "Named_Boxarts/Flink (Europe).png",
  "Named_Boxarts/Fly Harder (1993)(Buzz)[!].png",
  "Named_Boxarts/Fly Harder (Europe).png",
  "Named_Boxarts/Football Fever (AmigaJay).png",
  "Named_Boxarts/Frog Feast (2007)(Oldergames)[!].png",
  "Named_Boxarts/Frontier - Elite II (Europe).png",
  "Named_Boxarts/Frontier - Elite II v1.10 (1994)(Gametek - Konami)[!].png",
  "Named_Boxarts/Fury of the Furries (1994)(Kalisto - Mindscape)[!].png",
  "Named_Boxarts/Fury of the Furries (Europe).png",
  "Named_Boxarts/Gamers' Delight (Europe) (En,De).png",
  "Named_Boxarts/Global Effect (1994)(Millennium)[!].png",
  "Named_Boxarts/Global Effect (Europe).png",
  "Named_Boxarts/Gloom (1995)(Guildhall Leisure Services)[!].png",
  "Named_Boxarts/Gloom (Europe).png",
  "Named_Boxarts/Grandslam Gamer Gold Collection (1995)(Grandslam)[!][compilation].png",
  "Named_Boxarts/Grandslam Gamer Gold Collection (Europe).png",
  "Named_Boxarts/Guardian (1994)(Acid Software)[!][10325611].png",
  "Named_Boxarts/Guardian (1994)(Acid Software)[!][BR00424].png",
  "Named_Boxarts/Guardian (1994)(Acid Software)[!][BR00424-01].png",
  "Named_Boxarts/Guardian (1995)(Acid Software)[!][GH33].png",
  "Named_Boxarts/Guardian (Europe) (Alt).png",
  "Named_Boxarts/Guardian (Europe).png",
  "Named_Boxarts/Guinness Disc of Records, The - Second Edition (UK).png",
  "Named_Boxarts/Gulp! (1994)(ICE)(M5)[!].png",
  "Named_Boxarts/Gulp! (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Gunship 2000 (1994)(MicroProse)[!].png",
  "Named_Boxarts/Gunship 2000 (Europe) (fake jewel).png",
  "Named_Boxarts/Gunship 2000 (Europe).png",
  "Named_Boxarts/Heimdall 2 (1994)(Core)[!].png",
  "Named_Boxarts/Heimdall 2 - Into the Hall of Worlds (Europe).png",
  "Named_Boxarts/HeroQuest II - Legacy of Sorasil (1994)(Gremlin).png",
  "Named_Boxarts/HeroQuest II - Legacy of Sorasil (Europe) (En,Fr,De).png",
  "Named_Boxarts/Humans (1994)(Gametek - Imagitec Design)(M5)[!].png",
  "Named_Boxarts/Humans (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Humans 3 - Evolution - Lost in Time... (Europe).png",
  "Named_Boxarts/Hunter (AmigaJay).png",
  "Named_Boxarts/Impossible Mission 2025 - The Special Edition (1994)(MicroProse)[!].png",
  "Named_Boxarts/Impossible Mission 2025 - The Special Edition (Europe) (fake jewel).png",
  "Named_Boxarts/Impossible Mission 2025 - The Special Edition (Europe).png",
  "Named_Boxarts/Indy Heat _ Super Off Road (AmigaJay).png",
  "Named_Boxarts/International Karate + (1994)(System 3)[!].png",
  "Named_Boxarts/International Karate + (Europe).png",
  "Named_Boxarts/International Open Golf Championship (1993)(Ocean).png",
  "Named_Boxarts/International Open Golf Championship (Europe).png",
  "Named_Boxarts/International Sensible Soccer - World Champions (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/International Sensible Soccer - World Champions v1.2 (1994)(Renegade)(M4)[!].png",
  "Named_Boxarts/Isometric Racer Collection (AmigaJay).png",
  "Named_Boxarts/James Pond 2 - Robocod (1993)(Millennium)[!].png",
  "Named_Boxarts/James Pond 2 - Robocod (Europe).png",
  "Named_Boxarts/James Pond 3 - Operation Starfi5h (1994)(Kixx)[budget].png",
  "Named_Boxarts/James Pond 3 - Operation Starfi5h (1994)(Millennium)[!].png",
  "Named_Boxarts/James Pond 3 - Operation Starfi5h (Europe) (Kixx).png",
  "Named_Boxarts/James Pond 3 - Operation Starfi5h (Europe) (jewel).png",
  "Named_Boxarts/James Pond 3 - Operation Starfi5h (Europe).png",
  "Named_Boxarts/Jetstrike (1995)(Rasputin)[!].png",
  "Named_Boxarts/Jetstrike CD32 (Europe).png",
  "Named_Boxarts/Jim Power in Mutant Planet (Europe).png",
  "Named_Boxarts/John Barnes European Football (1993)(Buzz)(M5)[!].png",
  "Named_Boxarts/John Barnes European Football (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Jungle Strike - The Sequel to Desert Strike (1994)(Ocean)[!].png",
  "Named_Boxarts/Jungle Strike - The Sequel to Desert Strike (Europe).png",
  "Named_Boxarts/Kang Fu (1996)(ALTER interservice - Greed)[!][Amiga-CD32].png",
  "Named_Boxarts/Kang Fu (Europe).png",
  "Named_Boxarts/Kid Chaos (1994)(Ocean)[!].png",
  "Named_Boxarts/Kid Chaos (Europe) (jewel).png",
  "Named_Boxarts/Kid Chaos (Europe).png",
  "Named_Boxarts/Kingpin - Arcade Sports Bowling (1995)(Team 17)[!].png",
  "Named_Boxarts/Kingpin - Arcade Sports Bowling (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Labyrinth of Time, The (1994)(Electronic Arts)[!][Amiga-CD32-CDTV].png",
  "Named_Boxarts/Labyrinth of Time, The (Europe) (fake jewel).png",
  "Named_Boxarts/Labyrinth of Time, The (Europe).png",
  "Named_Boxarts/Lamborghini - American Challenge (Europe).png",
  "Named_Boxarts/Lamborghini American Challenge (1994)(Titus)[CDR000363].png",
  "Named_Boxarts/Last Ninja 3 (1994)(System 3)[!].png",
  "Named_Boxarts/Last Ninja 3 (Europe).png",
  "Named_Boxarts/Legends (1996)(Guildhall Leisure Services)(M3)[!].png",
  "Named_Boxarts/Legends (Europe) (En,Fr,De) (jewel).png",
  "Named_Boxarts/Legends (Europe) (En,Fr,De).png",
  "Named_Boxarts/Lemmings (1994)(Psygnosis)[!].png",
  "Named_Boxarts/Lemmings (Europe).png",
  "Named_Boxarts/Liberation - Captive II (Europe) (Rev 1).png",
  "Named_Boxarts/Liberation - Captive II (Europe) (Rev 2).png",
  "Named_Boxarts/Liberation - Captive II (Europe) (Rev 3).png",
  "Named_Boxarts/Liberation - Captive II (Europe).png",
  "Named_Boxarts/Liberation - Captive II v2.00-1.92 (1993-11-25)(Mindscape)[!][CDD2904].png",
  "Named_Boxarts/Liberation - Captive II v2.00b-2.00 (1993-12-08)(Mindscape)[!][CDD2955].png",
  "Named_Boxarts/Liberation - Captive II v2.00c-2.00c (1994-01-26)(Mindscape)[!][CDD3218].png",
  "Named_Boxarts/Liberation - Captive II v2.02-2.00c (1994-04-08)(Mindscape)[!][CDD3716].png",
  "Named_Boxarts/Liquid Kids _ Snow Bros (AmigaJay).png",
  "Named_Boxarts/Litil Divil (1994)(Gremlin)[!].png",
  "Named_Boxarts/Litil Divil (Europe).png",
  "Named_Boxarts/Lost Vikings, The (1993)(Interplay)[!].png",
  "Named_Boxarts/Lost Vikings, The (Europe).png",
  "Named_Boxarts/Mag!!! (1996)(Greenwood)(DE)[!][Amiga-CD32][M R-0568 A].png",
  "Named_Boxarts/Magic Island (Czech).png",
  "Named_Boxarts/Manchester United - Premier League Champions (Europe) (En,Fr,De,It) (Rev 1).png",
  "Named_Boxarts/Manchester United - Premier League Champions (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Manchester United - Premier League Champions v1.0CD (1994)(Krisalis)(M4)[!][CDD4783].png",
  "Named_Boxarts/Manchester United - Premier League Champions v1.0CD (1994)(Krisalis)(M4)[!][CDD5049].png",
  "Named_Boxarts/Marvin's Marvellous Adventure (1995)(21st Century Entertainment)(M4)[!].png",
  "Named_Boxarts/Marvin's Marvellous Adventure (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Mean Arenas (1993)(ICE)[!].png",
  "Named_Boxarts/Mean Arenas (Europe).png",
  "Named_Boxarts/Microcosm (1994)(Psygnosis)[!][MCD32-1 11].png",
  "Named_Boxarts/Microcosm (1994)(Psygnosis)[!][Spectacular Voyage][MICROCOSM-CD32].png",
  "Named_Boxarts/Microcosm (Europe) (Alt).png",
  "Named_Boxarts/Microcosm (Europe).png",
  "Named_Boxarts/Morph (1993)(Millennium)[!].png",
  "Named_Boxarts/Morph (Europe).png",
  "Named_Boxarts/Mutation Gold Compilation (1998)(Mutation)[Amiga-CD32].png",
  "Named_Boxarts/Myst (1997)(PXL computers)[!][Amiga-CD32].png",
  "Named_Boxarts/Myth - History in the Making (1994)(System 3)[!].png",
  "Named_Boxarts/Myth - History in the Making (Europe).png",
  "Named_Boxarts/Naughty Ones (1994)(Interactivision)[!].png",
  "Named_Boxarts/Naughty Ones (Europe).png",
  "Named_Boxarts/Nick Faldos Championship Golf (1994)(Grandslam)[!].png",
  "Named_Boxarts/Nick Faldos Championship Golf (Europe).png",
  "Named_Boxarts/Nigel Mansell's World Championship (1993)(Gremlin)(PAL)[!][CDD4197].png",
  "Named_Boxarts/Nigel Mansell's World Championship (1993)(Gremlin)(PAL)[!][S NIGEL 1 02].png",
  "Named_Boxarts/Nigel Mansell's World Championship (Europe) (Alt).png",
  "Named_Boxarts/Nigel Mansell's World Championship (Europe).png",
  "Named_Boxarts/Now That's What I Call Games (Europe).png",
  "Named_Boxarts/Now That's What I Call Games 2 (Europe).png",
  "Named_Boxarts/Now That's What I Call Games 3 - Games &amp; Goodies (Europe).png",
  "Named_Boxarts/Oscar (1993)(Flair).png",
  "Named_Boxarts/Oscar (Europe).png",
  "Named_Boxarts/Overhead Racer Collection (AmigaJay).png",
  "Named_Boxarts/Overkill _ Lunar-C (1993)(Mindscape)[!][compilation].png",
  "Named_Boxarts/Overkill _ Lunar-C (Europe).png",
  "Named_Boxarts/PGA European Tour (1994)(Ocean)[!].png",
  "Named_Boxarts/PGA European Tour (Europe).png",
  "Named_Boxarts/Pierre Le Chef Is ... Out to Lunch (Europe).png",
  "Named_Boxarts/Pierre le Chef is... Out to Lunch (1994)(Mindscape)[!].png",
  "Named_Boxarts/Pinball Fantasies (1993)(21st Century Entertainment)[!].png",
  "Named_Boxarts/Pinball Fantasies (Europe).png",
  "Named_Boxarts/Pinball Illusions (1995)(21st Century Entertainment)[!].png",
  "Named_Boxarts/Pinball Illusions (Europe) (fake jewel).png",
  "Named_Boxarts/Pinball Illusions (Europe).png",
  "Named_Boxarts/Pinball Prelude (1996)(Effigy Software)[!][Amiga-CD32-PC].png",
  "Named_Boxarts/Pinball Prelude (Europe).png",
  "Named_Boxarts/Pinocchio (Europe).png",
  "Named_Boxarts/Pirates! Gold (1993)(MicroProse)[!].png",
  "Named_Boxarts/Pirates! Gold (Europe) (En,De).png",
  "Named_Boxarts/Power Drive (1994)(U.S. Gold)(M5)[!].png",
  "Named_Boxarts/Power Drive (Europe) (En,Fr,De,Es,It) (fake jewel).png",
  "Named_Boxarts/Power Drive (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Power-Games (Europe) (En,De).png",
  "Named_Boxarts/Premiere (1994)(Core)[!].png",
  "Named_Boxarts/Premiere (Europe).png",
  "Named_Boxarts/Prey - An Alien Encounter (1993)(Almathera)[!].png",
  "Named_Boxarts/Prey - An Alien Encounter (Europe).png",
  "Named_Boxarts/Project-X _ F17 Challenge (1993)(Team 17)[!][compilation][CDD3187].png",
  "Named_Boxarts/Project-X _ F17 Challenge (Europe) (En,Fr,De,It,Da) (v2.0).png",
  "Named_Boxarts/Project-X _ F17 Challenge (Europe) (En,Fr,De,It,Da).png",
  "Named_Boxarts/Project-X _ F17 Challenge v2.0 (1993)(Team 17)[!][compilation][CDD3499].png",
  "Named_Boxarts/Project-X _ Ultimate Body Blows (1994)(Team 17)[!][compilation].png",
  "Named_Boxarts/Project-X _ Ultimate Body Blows (Europe).png",
  "Named_Boxarts/Projekt - Lila (Germany) (Rev 1).png",
  "Named_Boxarts/Projekt - Lila (Germany).png",
  "Named_Boxarts/Psygnosis Collection (AmigaJay).png",
  "Named_Boxarts/Quik the Thunder Rabbit (Europe).png",
  "Named_Boxarts/Rise of the Robots (1994)(Time Warner Interactive)[!].png",
  "Named_Boxarts/Rise of the Robots (Europe).png",
  "Named_Boxarts/Roadkill (1994)(Acid Software)[!][CDD4971].png",
  "Named_Boxarts/Roadkill (1995)(Acid Software)[!][GH 32].png",
  "Named_Boxarts/Roadkill (Europe) (Alt).png",
  "Named_Boxarts/Roadkill (Europe).png",
  "Named_Boxarts/Run 'n Gun Collection (AmigaJay).png",
  "Named_Boxarts/Ryder Cup - Johnnie Walker (Europe).png",
  "Named_Boxarts/Ryder Cup by Johnnie Walker, The (1993)(Ocean)[!].png",
  "Named_Boxarts/Sabre Team (1994)(Krisalis)(M5)[!].png",
  "Named_Boxarts/Sabre Team (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Seek _ Destroy (1993)(Mindscape)[!].png",
  "Named_Boxarts/Seek and Destroy (Europe).png",
  "Named_Boxarts/Sensible Soccer - European Champions (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Sensible Soccer - European Champions v1.1 (1993)(Renegade)(M4)[!].png",
  "Named_Boxarts/Seven Gates of Jambala, The (1993)(Unique)[!].png",
  "Named_Boxarts/Seven Gates of Jambala, The (Europe).png",
  "Named_Boxarts/Seven Over Par (AmigaJay).png",
  "Named_Boxarts/Shadow Fighter (1995)(Gremlin)[!].png",
  "Named_Boxarts/Shadow Fighter (Europe).png",
  "Named_Boxarts/Sheer Delight (USA, Europe).png",
  "Named_Boxarts/Simon the Sorcerer (1994)(Adventure Soft)[!].png",
  "Named_Boxarts/Simon the Sorcerer (Europe).png",
  "Named_Boxarts/Skeleton Krew (1995)(Core)[!].png",
  "Named_Boxarts/Skeleton Krew (Europe).png",
  "Named_Boxarts/Sleepwalker (1993)(Ocean)[!].png",
  "Named_Boxarts/Sleepwalker (Europe) (fake jewel).png",
  "Named_Boxarts/Sleepwalker (Europe).png",
  "Named_Boxarts/Sleepwalker _ Pinball Fantasies (1993)(Commodore)[!][compilation][CDAC-055300 2].png",
  "Named_Boxarts/Sleepwalker _ Pinball Fantasies (1993)(Commodore)[!][compilation][PFANTASCD32].png",
  "Named_Boxarts/Sleepwalker _ Pinball Fantasies (USA).png",
  "Named_Boxarts/Soccer Kid (1994)(Krisalis)(M5)[!].png",
  "Named_Boxarts/Soccer Kid (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Soccer Superstars (1995)(Flair Software)(M5)[!].png",
  "Named_Boxarts/Soccer Superstars (Europe) (fake jewel).png",
  "Named_Boxarts/Soccer Superstars (Europe).png",
  "Named_Boxarts/Speedball 2 (1995)(Renegade)[!].png",
  "Named_Boxarts/Speedball 2 (Europe).png",
  "Named_Boxarts/Speris Legacy, The (1995)(Ocean - Team 17)[!][cp code].png",
  "Named_Boxarts/Speris Legacy, The (Europe).png",
  "Named_Boxarts/Sports - Football (USA).png",
  "Named_Boxarts/Sports Football (1993)(Commodore)[!].png",
  "Named_Boxarts/Star Crusader (1994)(Gametek - Take 2)[!][Amiga-CD32].png",
  "Named_Boxarts/Star Crusader (Europe) (jewel).png",
  "Named_Boxarts/Star Crusader (Europe).png",
  "Named_Boxarts/Star Wars Trilogy, The (AmigaJay).png",
  "Named_Boxarts/Striker (1994)(Gremlin)[!].png",
  "Named_Boxarts/Striker (Europe).png",
  "Named_Boxarts/Strip Pot (1994)(Pixel Blue)[!].png",
  "Named_Boxarts/Strip Pot (Europe).png",
  "Named_Boxarts/Subwar 2050 (1994)(MicroProse)(M3)[!].png",
  "Named_Boxarts/Subwar 2050 (Europe) (En,Fr,De).png",
  "Named_Boxarts/Subwar 2050 (Europe) (fake jewel).png",
  "Named_Boxarts/Summer Olympix (1994)(Flair Software)[!].png",
  "Named_Boxarts/Summer Olympix (Europe).png",
  "Named_Boxarts/Super League Manager (1995)(Audiogenic)[!].png",
  "Named_Boxarts/Super League Manager (Europe).png",
  "Named_Boxarts/Super Methane Bros (1994)(Apache)[!][10329011 01].png",
  "Named_Boxarts/Super Methane Bros (1994)(Apache)[!][BR00245-01].png",
  "Named_Boxarts/Super Methane Bros. (Europe) (Alt).png",
  "Named_Boxarts/Super Methane Bros. (Europe).png",
  "Named_Boxarts/Super Putty (1994)(System 3)[!].png",
  "Named_Boxarts/Super Putty (Europe).png",
  "Named_Boxarts/Super Skidmarks (Europe) (Alt).png",
  "Named_Boxarts/Super Skidmarks (Europe).png",
  "Named_Boxarts/Super Skidmarks v2.2 (1995)(Acid Software)[!][GH 1 10 AUG 95].png",
  "Named_Boxarts/Super Skidmarks v2.2 (1995)(Acid Software)[!][GH1 21 APR 95].png",
  "Named_Boxarts/Super Stardust (1994)(Team 17)[!].png",
  "Named_Boxarts/Super Stardust (Europe).png",
  "Named_Boxarts/Super Street Fighter II Turbo (1995)(Gametek)[!].png",
  "Named_Boxarts/Super Street Fighter II Turbo (Europe) (fake jewel).png",
  "Named_Boxarts/Super Street Fighter II Turbo (Europe).png",
  "Named_Boxarts/Superfrog (1994)(Team 17)[!].png",
  "Named_Boxarts/Superfrog (Europe) (jewel).png",
  "Named_Boxarts/Superfrog (Europe).png",
  "Named_Boxarts/Surf Ninjas (1993)(Microvalue)[!].png",
  "Named_Boxarts/Surf Ninjas (Europe).png",
  "Named_Boxarts/Syndicate (1995)(Mindscape)(M3)[!].png",
  "Named_Boxarts/Syndicate (Europe) (En,Fr,It).png",
  "Named_Boxarts/Team 17 Collection (AmigaJay).png",
  "Named_Boxarts/Tennis Tossers (AmigaJay).png",
  "Named_Boxarts/Theme Park (1995)(Mindscape)[!].png",
  "Named_Boxarts/Theme Park (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Thomas The Tank Engine _ Friends Pinball (1995)(Alternative Software).png",
  "Named_Boxarts/Thomas the Tank Engine's Pinball (Europe).png",
  "Named_Boxarts/Top Gear 2 (1994)(Gremlin)[!].png",
  "Named_Boxarts/Top Gear 2 (Europe).png",
  "Named_Boxarts/Total Carnage (1994)(ICE)[!].png",
  "Named_Boxarts/Total Carnage (Europe).png",
  "Named_Boxarts/Trivial Pursuit - The CD32 Edition (Europe).png",
  "Named_Boxarts/Trivial Pursuit - The CD32 Edition v1.0C (1994)(Domark)[!].png",
  "Named_Boxarts/Trolls (1993)(Flair Software)(PAL)[!].png",
  "Named_Boxarts/Trolls (Europe).png",
  "Named_Boxarts/UFO - Enemy Unknown (1994)(MicroProse)(M3)[!].png",
  "Named_Boxarts/UFO - Enemy Unknown (Europe) (En,Fr,De) (fake jewel).png",
  "Named_Boxarts/UFO - Enemy Unknown (Europe) (En,Fr,De).png",
  "Named_Boxarts/Ultimate Body Blows (1994)(Team 17)[!].png",
  "Named_Boxarts/Ultimate Body Blows (Europe).png",
  "Named_Boxarts/Ultimate Dizzy Collection, The (AmigaJay).png",
  "Named_Boxarts/Ultimate Super SkidMarks (1997)(Guildhall Leisure Services)[!][Amiga-CD32].png",
  "Named_Boxarts/Ultimate Super Skidmarks (Europe).png",
  "Named_Boxarts/Universe (1994)(Core)(M4)[!].png",
  "Named_Boxarts/Universe (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Unreleased Amiga Game Collection (AmigaJay).png",
  "Named_Boxarts/Vertical S.E.U Collection (AmigaJay).png",
  "Named_Boxarts/Video Creator (Europe).png",
  "Named_Boxarts/Vital Light (1994)(Millennium)[!].png",
  "Named_Boxarts/Vital Light (Europe) (Alt).png",
  "Named_Boxarts/Vital Light (Europe).png",
  "Named_Boxarts/Wembley International Soccer (1994)(Audiogenic)[!][10292711 01].png",
  "Named_Boxarts/Wembley International Soccer (1994)(Audiogenic)[!][10292711 02].png",
  "Named_Boxarts/Wembley International Soccer (Europe) (jewel).png",
  "Named_Boxarts/Wembley International Soccer (Europe).png",
  "Named_Boxarts/Wendetta 2175 (1996)(Skills)[!][Amiga-CD32].png",
  "Named_Boxarts/Wendetta 2175 (1996)(Skills)[AGA][Amiga-CD32].png",
  "Named_Boxarts/Wendetta 2175 (Europe).png",
  "Named_Boxarts/Whale's Voyage (1994)(Flair Software)[!][CDD2736].png",
  "Named_Boxarts/Whale's Voyage (1994)(Flair Software)[!][CDD3080].png",
  "Named_Boxarts/Whale's Voyage (Europe) (Rev 1).png",
  "Named_Boxarts/Whale's Voyage (Europe).png",
  "Named_Boxarts/Whale's Voyage (Germany).png",
  "Named_Boxarts/Whizz (1994)(Flair Software).png",
  "Named_Boxarts/Whizz (Europe).png",
  "Named_Boxarts/Wild Cup Soccer (1994)(Millennium)[!].png",
  "Named_Boxarts/Wild Cup Soccer (Europe) (fake jewel).png",
  "Named_Boxarts/Wild Cup Soccer (Europe).png",
  "Named_Boxarts/Will Bridge - Initiation Junior (Europe).png",
  "Named_Boxarts/Will Bridge - Practice 1 - Initiation - Junior (1991)(Will Bridge)(FR)(en).png",
  "Named_Boxarts/Wing Commander (1994)(Origin).png",
  "Named_Boxarts/Worms (1995)(Ocean - Team 17)(M3)[!][cp code].png",
  "Named_Boxarts/Worms (Europe) (En,Fr,De).png",
  "Named_Boxarts/Ye Old Pirates Collection (AmigaJay).png",
  "Named_Boxarts/Zool - Ninja of the 'Nth' Dimension (1993)(Gremlin)(PAL)[!].png",
  "Named_Boxarts/Zool - Ninja of the Nth Dimension (Europe).png",
  "Named_Boxarts/Zool 2 (1994)(Gremlin)[!].png",
  "Named_Boxarts/Zool 2 (Europe) (Alt).png",
  "Named_Boxarts/Zool 2 (Europe).png",
  "Named_Snaps/ATR - All Terrain Racing (1995)(Team 17)[!].png",
  "Named_Snaps/ATR - All Terrain Racing (Europe).png",
  "Named_Snaps/Akira (1994)(ICE)[!].png",
  "Named_Snaps/Akira (Europe).png",
  "Named_Snaps/Alfred Chicken (1993)(Mindscape)[!].png",
  "Named_Snaps/Alfred Chicken (Europe).png",
  "Named_Snaps/Alien Breed - Tower Assault (1994)(Team 17)[!].png",
  "Named_Snaps/Alien Breed - Tower Assault (Europe).png",
  "Named_Snaps/Alien Breed 3D (1995)(Ocean - Team 17)[!][cp code].png",
  "Named_Snaps/Alien Breed 3D (Europe).png",
  "Named_Snaps/Alien Breed Special Edition _ Qwak (1994)(Team 17)[!][compilation].png",
  "Named_Snaps/Alien Breed Special Edition _ Qwak (Europe) (En,Fr,De,It,Da).png",
  "Named_Snaps/Amiga CD! Magazine No. 1 (UK).png",
  "Named_Snaps/Amiga CD! Magazine No. 2 (UK).png",
  "Named_Snaps/Amiga CD! Magazine No. 3 (UK).png",
  "Named_Snaps/Amiga CD32 - Issue 1 (Spring) (UK).png",
  "Named_Snaps/Amiga CD32 - Issue 2 (Winter) (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 01 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 02 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 03 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 04 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 05 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 06 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 07 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 08 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 09 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 10 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 11 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 12 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 13 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 14 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 15 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 16 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 17 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 18 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 19 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 20 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 21 (UK).png",
  "Named_Snaps/Amiga CD32 Gamer Vol. 22 (UK).png",
  "Named_Snaps/Amiga CD32 Special 1 (1994-12-08)(Paragon Publishing)(GB)[!][Lamborghini American Challenge].png",
  "Named_Snaps/Amiga CD32 Special 2 (1995-01-12)(Paragon Publishing)(GB)[!][Quik The Thunder Rabbit].png",
  "Named_Snaps/Amiga CD32 Special 3 (1995-04)(Paragon Publishing)(GB)[!][Vital Light].png",
  "Named_Snaps/Amiga Christmas Crackers (AmigaJay).png",
  "Named_Snaps/Amiga Power - Games Massive Volume 1 (UK).png",
  "Named_Snaps/Arabian Nights (1993)(Buzz)(M4)[!].png",
  "Named_Snaps/Arabian Nights (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Arcade Pool (1994)(Team 17)[!][CDD4978].png",
  "Named_Snaps/Arcade Pool (1994)(Team 17)[!][CDR00281].png",
  "Named_Snaps/Arcade Pool (Europe) (En,Fr,De,It) (Alt).png",
  "Named_Snaps/Arcade Pool (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Assassins - Ultimate Games Compact Disc (Europe) (v2.0).png",
  "Named_Snaps/Banshee (1994)(Core)(M4)[!].png",
  "Named_Snaps/Banshee (Europe) (En,Fr,De,Da).png",
  "Named_Snaps/Base Jumpers (1995)(Rasputin)[!].png",
  "Named_Snaps/Base Jumpers (Europe).png",
  "Named_Snaps/Battle Chess (1994)(Interplay)[!].png",
  "Named_Snaps/Battle Chess (Europe).png",
  "Named_Snaps/Battletoads (1994)(Mindscape)[!].png",
  "Named_Snaps/Battletoads (Europe).png",
  "Named_Snaps/Beavers (1994)(Unique)[!].png",
  "Named_Snaps/Beavers (Europe).png",
  "Named_Snaps/Beneath a Steel Sky (1994)(Virgin)(M4)[!].png",
  "Named_Snaps/Beneath a Steel Sky (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Benefactor (1994)(Psygnosis)[!].png",
  "Named_Snaps/Benefactor (Europe).png",
  "Named_Snaps/Big 6, The (Europe).png",
  "Named_Snaps/Big 6, The - Original Dizzy Adventure Games (1994)(Codemasters)[!][compilation].png",
  "Named_Snaps/Bitmap Brothers Collection, The (AGA) (AmigaJay).png",
  "Named_Snaps/Bitmap Brothers Collection, The (OCS) (AmigaJay).png",
  "Named_Snaps/Black Viper (1996)(NEO)(M3)[!][Amiga-CD32].png",
  "Named_Snaps/Black Viper (1996)(Neo)(M3).png",
  "Named_Snaps/Black Viper (Europe) (En,De,It).png",
  "Named_Snaps/Brian the Lion (Europe) (En,Fr,De,It) (Gameplay CD-ROM).png",
  "Named_Snaps/Brian the Lion Starring in Rumble in the Jungle (1994)(Psygnosis)(M4)[!].png",
  "Named_Snaps/Brutal - Paws of Fury (1995)(Gametek)(M3)[!].png",
  "Named_Snaps/Brutal - Paws of Fury (Europe).png",
  "Named_Snaps/Brutal Football (1994)(Millennium)[!].png",
  "Named_Snaps/Brutal Football (Europe).png",
  "Named_Snaps/Bubba 'N' Stix (1994)(Core)[!].png",
  "Named_Snaps/Bubba 'n' Stix (Europe).png",
  "Named_Snaps/Bubble Bobble Trilogy (AmigaJay).png",
  "Named_Snaps/Bubble and Squeak (1994)(Audiogenic)[!].png",
  "Named_Snaps/Bubble and Squeak (Europe).png",
  "Named_Snaps/Bump 'N' Burn (1994)(Grandslam)[!].png",
  "Named_Snaps/Bump 'n' Burn (Europe).png",
  "Named_Snaps/CD Exchange - Volume 1 (UK).png",
  "Named_Snaps/Candy Puzzle (1996)(Gevin)[CUBO].png",
  "Named_Snaps/Cannon Fodder (1993)(Virgin)[!][Amiga-CD32].png",
  "Named_Snaps/Cannon Fodder (1993)(Virgin)[Amiga-CD32][a].png",
  "Named_Snaps/Cannon Fodder (Europe).png",
  "Named_Snaps/Castles II - Siege _ Conquest (1993)(Interplay)[!].png",
  "Named_Snaps/Castles II - Siege _ Conquest (Europe).png",
  "Named_Snaps/Cedric and the Lost Sceptre (Europe).png",
  "Named_Snaps/Cedric and the lost sceptre (1996)(NEO)(de-en)[!][AGA-CD32].png",
  "Named_Snaps/Center Court Tennis 2 (2016-07-21)(Fritsche, Gernot)(FW)[!].png",
  "Named_Snaps/Chambers of Shaolin (1993)(Unique)[!].png",
  "Named_Snaps/Chambers of Shaolin (Europe).png",
  "Named_Snaps/Chaos Engine, The (1994)(Renegade)[!][CDD3445].png",
  "Named_Snaps/Chaos Engine, The (1994)(Renegade)[!][Spectacular Voyage][CDD3446].png",
  "Named_Snaps/Chaos Engine, The (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Chaos Engine, The (Europe) (Spectacular Voyage).png",
  "Named_Snaps/Chuck Rock (1994)(Core)[!].png",
  "Named_Snaps/Chuck Rock (Europe).png",
  "Named_Snaps/Chuck Rock II - Son of Chuck (1994)(Core)[!].png",
  "Named_Snaps/Chuck Rock II - Son of Chuck (Europe).png",
  "Named_Snaps/Classic Lotus Trilogy, The (1994)(Gremlin)(PAL)[!][compilation].png",
  "Named_Snaps/Classic Lotus Trilogy, The (Europe).png",
  "Named_Snaps/Clockwiser (1994)(Rasputin)[!].png",
  "Named_Snaps/Clockwiser (Europe).png",
  "Named_Snaps/Clou!, Der (Germany).png",
  "Named_Snaps/Clue!, The (1994)(Kompart)[!].png",
  "Named_Snaps/Communicator (Germany) (En,De).png",
  "Named_Snaps/D-Generation (Europe).png",
  "Named_Snaps/D-Generation v1.0 (1993)(Mindscape)[!].png",
  "Named_Snaps/D-Generation v1.0 (1993)(Mindscape)[b].png",
  "Named_Snaps/Dangerous Streets (1993)(Flair Software)[!].png",
  "Named_Snaps/Dangerous Streets (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Dangerous Streets _ Wing Commander (1993)(Commodore)[!][compilation].png",
  "Named_Snaps/Dangerous Streets _ Wing Commander (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Darkseed (Europe).png",
  "Named_Snaps/Darkseed v1.1 (1994)(Cyberdreams)[!].png",
  "Named_Snaps/Death Mask (1994)(Alternative Software)[!].png",
  "Named_Snaps/Death Mask (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Deep Core (Europe) (v1.00).png",
  "Named_Snaps/Deep Core (Europe) (v1.01).png",
  "Named_Snaps/Deep Core v1.00 (1993)(ICE)[!][CDD2840].png",
  "Named_Snaps/Deep Core v1.01 (1993)(ICE)[!][CDD2998].png",
  "Named_Snaps/Defender of the Crown II (Europe).png",
  "Named_Snaps/Defender of the Crown II (USA).png",
  "Named_Snaps/Demo Disc, The - Commodore Amiga CD32 Demonstration Disc 2.0 (Europe).png",
  "Named_Snaps/Dennis (1993)(Ocean)[!].png",
  "Named_Snaps/Dennis (Europe).png",
  "Named_Snaps/Diggers (1993)(Millennium)(NTSC)[!].png",
  "Named_Snaps/Diggers (Europe).png",
  "Named_Snaps/Diggers _ Oscar (1993)(Commodore)[!][compilation][AMIGA-CD 31, 54].png",
  "Named_Snaps/Diggers _ Oscar (1993)(Commodore)[!][compilation][AMIGA-CD-V2].png",
  "Named_Snaps/Diggers _ Oscar (Europe) (Rev 1) (Alt).png",
  "Named_Snaps/Diggers _ Oscar (Europe) (Rev 1).png",
  "Named_Snaps/Diggers _ Oscar (Europe).png",
  "Named_Snaps/Disposable Hero (1994)(Gremlin)(PAL)[!].png",
  "Named_Snaps/Disposable Hero (Europe).png",
  "Named_Snaps/Donk! The Samurai Duck! (1994)(Supervision)[!].png",
  "Named_Snaps/Donk! The Samurai Duck! (1994)(Supervision)[a].png",
  "Named_Snaps/Donk! The Samurai Duck! (Europe).png",
  "Named_Snaps/Dragonstone (1995)(Core)(M3)[!].png",
  "Named_Snaps/Dragonstone (Europe) (En,Fr,De).png",
  "Named_Snaps/Emerald Mines (1994)(Almathera)[!][compilation][CDD4410].png",
  "Named_Snaps/Emerald Mines (Europe).png",
  "Named_Snaps/Erben der Erde - Die grosse Suche (1995)(Softgold)(DE)[!][Amiga-CD32-CDTV].png",
  "Named_Snaps/Erben der Erde - Die grosse Suche (1995)(Softgold)(DE)[AGA-CD32].png",
  "Named_Snaps/Exile (1995)(Audiogenic)[!].png",
  "Named_Snaps/Exile (Europe).png",
  "Named_Snaps/F1 Collection (AmigaJay).png",
  "Named_Snaps/Factor 5 Collection (AmigaJay).png",
  "Named_Snaps/Fears (1995)(Guildhall Leisure Services)[!].png",
  "Named_Snaps/Fears (1995)(attic)(DE)(en)[!].png",
  "Named_Snaps/Fears (Europe).png",
  "Named_Snaps/Fields of Glory (1994)(MicroProse)(M3)[!].png",
  "Named_Snaps/Fields of Glory (Europe) (En,Fr,De).png",
  "Named_Snaps/Fightin' Spirit (1996)(NEO)(M3)[!][Amiga-CD32].png",
  "Named_Snaps/Fightin' Spirit (Europe) (En,De,It).png",
  "Named_Snaps/Final Gate, The (1997)(Alternative Software - Bigg Wolf).png",
  "Named_Snaps/Final Gate, The (Europe).png",
  "Named_Snaps/Fire Force (1993)(Buzz)[!].png",
  "Named_Snaps/Fire Force (Europe).png",
  "Named_Snaps/Fire _ Ice - The Daring Adventures of Cool Coyote (1994)(Renegade)[!].png",
  "Named_Snaps/Fire _ Ice - The Daring Adventures of Cool Coyote (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Flink (1994)(Psygnosis)[!].png",
  "Named_Snaps/Flink (Europe).png",
  "Named_Snaps/Fly Harder (1993)(Buzz)[!].png",
  "Named_Snaps/Fly Harder (Europe).png",
  "Named_Snaps/Football Fever (AmigaJay).png",
  "Named_Snaps/Frog Feast (2007)(Oldergames)[!].png",
  "Named_Snaps/Frontier - Elite II (Europe).png",
  "Named_Snaps/Frontier - Elite II v1.10 (1994)(Gametek - Konami)[!].png",
  "Named_Snaps/Fury of the Furries (1994)(Kalisto - Mindscape)[!].png",
  "Named_Snaps/Fury of the Furries (Europe).png",
  "Named_Snaps/Gamers' Delight (Europe) (En,De).png",
  "Named_Snaps/Global Effect (1994)(Millennium)[!].png",
  "Named_Snaps/Global Effect (Europe).png",
  "Named_Snaps/Gloom (1995)(Guildhall Leisure Services)[!].png",
  "Named_Snaps/Gloom (Europe).png",
  "Named_Snaps/Grandslam Gamer Gold Collection (1995)(Grandslam)[!][compilation].png",
  "Named_Snaps/Grandslam Gamer Gold Collection (Europe).png",
  "Named_Snaps/Guardian (1994)(Acid Software)[!][10325611].png",
  "Named_Snaps/Guardian (1994)(Acid Software)[!][BR00424].png",
  "Named_Snaps/Guardian (1994)(Acid Software)[!][BR00424-01].png",
  "Named_Snaps/Guardian (1995)(Acid Software)[!][GH33].png",
  "Named_Snaps/Guardian (Europe) (Alt).png",
  "Named_Snaps/Guardian (Europe).png",
  "Named_Snaps/Gulp! (1994)(ICE)(M5)[!].png",
  "Named_Snaps/Gulp! (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Gunship 2000 (1994)(MicroProse)[!].png",
  "Named_Snaps/Gunship 2000 (Europe).png",
  "Named_Snaps/Heimdall 2 (1994)(Core)[!].png",
  "Named_Snaps/Heimdall 2 - Into the Hall of Worlds (Europe).png",
  "Named_Snaps/HeroQuest II - Legacy of Sorasil (1994)(Gremlin).png",
  "Named_Snaps/HeroQuest II - Legacy of Sorasil (Europe) (En,Fr,De).png",
  "Named_Snaps/Humans (1994)(Gametek - Imagitec Design)(M5)[!].png",
  "Named_Snaps/Humans (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Humans 3 - Evolution - Lost in Time... (Europe).png",
  "Named_Snaps/Hunter (AmigaJay).png",
  "Named_Snaps/Impossible Mission 2025 - The Special Edition (1994)(MicroProse)[!].png",
  "Named_Snaps/Impossible Mission 2025 - The Special Edition (Europe).png",
  "Named_Snaps/Indy Heat _ Super Off Road (AmigaJay).png",
  "Named_Snaps/International Karate + (1994)(System 3)[!].png",
  "Named_Snaps/International Karate + (Europe).png",
  "Named_Snaps/International Open Golf Championship (1993)(Ocean).png",
  "Named_Snaps/International Open Golf Championship (Europe).png",
  "Named_Snaps/International Sensible Soccer - World Champions (Europe) (En,Fr,De,It).png",
  "Named_Snaps/International Sensible Soccer - World Champions v1.2 (1994)(Renegade)(M4)[!].png",
  "Named_Snaps/Isometric Racer Collection (AmigaJay).png",
  "Named_Snaps/James Pond 2 - Robocod (1993)(Millennium)[!].png",
  "Named_Snaps/James Pond 2 - Robocod (Europe).png",
  "Named_Snaps/James Pond 3 - Operation Starfi5h (1994)(Kixx)[budget].png",
  "Named_Snaps/James Pond 3 - Operation Starfi5h (1994)(Millennium)[!].png",
  "Named_Snaps/James Pond 3 - Operation Starfi5h (Europe) (Kixx).png",
  "Named_Snaps/James Pond 3 - Operation Starfi5h (Europe).png",
  "Named_Snaps/Jetstrike (1995)(Rasputin)[!].png",
  "Named_Snaps/Jetstrike CD32 (Europe).png",
  "Named_Snaps/Jim Power in Mutant Planet (Europe).png",
  "Named_Snaps/John Barnes European Football (1993)(Buzz)(M5)[!].png",
  "Named_Snaps/John Barnes European Football (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Jungle Strike - The Sequel to Desert Strike (1994)(Ocean)[!].png",
  "Named_Snaps/Jungle Strike - The Sequel to Desert Strike (Europe).png",
  "Named_Snaps/Kang Fu (1996)(ALTER interservice - Greed)[!][Amiga-CD32].png",
  "Named_Snaps/Kang Fu (Europe).png",
  "Named_Snaps/Kid Chaos (1994)(Ocean)[!].png",
  "Named_Snaps/Kid Chaos (Europe).png",
  "Named_Snaps/Kingpin - Arcade Sports Bowling (1995)(Team 17)[!].png",
  "Named_Snaps/Kingpin - Arcade Sports Bowling (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Labyrinth of Time, The (1994)(Electronic Arts)[!][Amiga-CD32-CDTV].png",
  "Named_Snaps/Labyrinth of Time, The (Europe).png",
  "Named_Snaps/Lamborghini - American Challenge (Europe).png",
  "Named_Snaps/Lamborghini American Challenge (1994)(Titus)[CDR000363].png",
  "Named_Snaps/Last Ninja 3 (1994)(System 3)[!].png",
  "Named_Snaps/Last Ninja 3 (Europe).png",
  "Named_Snaps/Legends (1996)(Guildhall Leisure Services)(M3)[!].png",
  "Named_Snaps/Legends (Europe) (En,Fr,De).png",
  "Named_Snaps/Lemmings (1994)(Psygnosis)[!].png",
  "Named_Snaps/Lemmings (Europe).png",
  "Named_Snaps/Liberation - Captive II (Europe) (Rev 1).png",
  "Named_Snaps/Liberation - Captive II (Europe) (Rev 2).png",
  "Named_Snaps/Liberation - Captive II (Europe) (Rev 3).png",
  "Named_Snaps/Liberation - Captive II (Europe).png",
  "Named_Snaps/Liberation - Captive II v2.00-1.92 (1993-11-25)(Mindscape)[!][CDD2904].png",
  "Named_Snaps/Liberation - Captive II v2.00b-2.00 (1993-12-08)(Mindscape)[!][CDD2955].png",
  "Named_Snaps/Liberation - Captive II v2.00c-2.00c (1994-01-26)(Mindscape)[!][CDD3218].png",
  "Named_Snaps/Liberation - Captive II v2.02-2.00c (1994-04-08)(Mindscape)[!][CDD3716].png",
  "Named_Snaps/Liquid Kids _ Snow Bros (AmigaJay).png",
  "Named_Snaps/Litil Divil (1994)(Gremlin)[!].png",
  "Named_Snaps/Litil Divil (Europe).png",
  "Named_Snaps/Lost Vikings, The (1993)(Interplay)[!].png",
  "Named_Snaps/Lost Vikings, The (Europe).png",
  "Named_Snaps/Mag!!! (1996)(Greenwood)(DE)[!][Amiga-CD32][M R-0568 A].png",
  "Named_Snaps/Magic Island (Czech).png",
  "Named_Snaps/Manchester United - Premier League Champions (Europe) (En,Fr,De,It) (Rev 1).png",
  "Named_Snaps/Manchester United - Premier League Champions (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Manchester United - Premier League Champions v1.0CD (1994)(Krisalis)(M4)[!][CDD4783].png",
  "Named_Snaps/Manchester United - Premier League Champions v1.0CD (1994)(Krisalis)(M4)[!][CDD5049].png",
  "Named_Snaps/Marvin's Marvellous Adventure (1995)(21st Century Entertainment)(M4)[!].png",
  "Named_Snaps/Marvin's Marvellous Adventure (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Mean Arenas (1993)(ICE)[!].png",
  "Named_Snaps/Mean Arenas (Europe).png",
  "Named_Snaps/Microcosm (1994)(Psygnosis)[!][MCD32-1 11].png",
  "Named_Snaps/Microcosm (1994)(Psygnosis)[!][Spectacular Voyage][MICROCOSM-CD32].png",
  "Named_Snaps/Microcosm (Europe) (Alt).png",
  "Named_Snaps/Microcosm (Europe).png",
  "Named_Snaps/Morph (1993)(Millennium)[!].png",
  "Named_Snaps/Morph (Europe).png",
  "Named_Snaps/Mutation Gold Compilation (1998)(Mutation)[Amiga-CD32].png",
  "Named_Snaps/Myst (1997)(PXL computers)[!][Amiga-CD32].png",
  "Named_Snaps/Myth - History in the Making (1994)(System 3)[!].png",
  "Named_Snaps/Myth - History in the Making (Europe).png",
  "Named_Snaps/Naughty Ones (1994)(Interactivision)[!].png",
  "Named_Snaps/Naughty Ones (Europe).png",
  "Named_Snaps/Nick Faldos Championship Golf (1994)(Grandslam)[!].png",
  "Named_Snaps/Nick Faldos Championship Golf (Europe).png",
  "Named_Snaps/Nigel Mansell's World Championship (1993)(Gremlin)(PAL)[!][CDD4197].png",
  "Named_Snaps/Nigel Mansell's World Championship (1993)(Gremlin)(PAL)[!][S NIGEL 1 02].png",
  "Named_Snaps/Nigel Mansell's World Championship (Europe) (Alt).png",
  "Named_Snaps/Nigel Mansell's World Championship (Europe).png",
  "Named_Snaps/Oscar (1993)(Flair).png",
  "Named_Snaps/Oscar (Europe).png",
  "Named_Snaps/Overhead Racer Collection (AmigaJay).png",
  "Named_Snaps/Overkill _ Lunar-C (1993)(Mindscape)[!][compilation].png",
  "Named_Snaps/Overkill _ Lunar-C (Europe).png",
  "Named_Snaps/PGA European Tour (1994)(Ocean)[!].png",
  "Named_Snaps/PGA European Tour (Europe).png",
  "Named_Snaps/Pierre Le Chef Is ... Out to Lunch (Europe).png",
  "Named_Snaps/Pierre le Chef is... Out to Lunch (1994)(Mindscape)[!].png",
  "Named_Snaps/Pinball Fantasies (1993)(21st Century Entertainment)[!].png",
  "Named_Snaps/Pinball Fantasies (Europe).png",
  "Named_Snaps/Pinball Illusions (1995)(21st Century Entertainment)[!].png",
  "Named_Snaps/Pinball Illusions (Europe).png",
  "Named_Snaps/Pinball Prelude (1996)(Effigy Software)[!][Amiga-CD32-PC].png",
  "Named_Snaps/Pinball Prelude (Europe).png",
  "Named_Snaps/Pinocchio (Europe).png",
  "Named_Snaps/Pirates! Gold (1993)(MicroProse)[!].png",
  "Named_Snaps/Pirates! Gold (Europe) (En,De).png",
  "Named_Snaps/Power Drive (1994)(U.S. Gold)(M5)[!].png",
  "Named_Snaps/Power Drive (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Power-Games (Europe) (En,De).png",
  "Named_Snaps/Premiere (1994)(Core)[!].png",
  "Named_Snaps/Premiere (Europe).png",
  "Named_Snaps/Prey - An Alien Encounter (1993)(Almathera)[!].png",
  "Named_Snaps/Prey - An Alien Encounter (Europe).png",
  "Named_Snaps/Project-X _ F17 Challenge (1993)(Team 17)[!][compilation][CDD3187].png",
  "Named_Snaps/Project-X _ F17 Challenge (Europe) (En,Fr,De,It,Da) (v2.0).png",
  "Named_Snaps/Project-X _ F17 Challenge (Europe) (En,Fr,De,It,Da).png",
  "Named_Snaps/Project-X _ F17 Challenge v2.0 (1993)(Team 17)[!][compilation][CDD3499].png",
  "Named_Snaps/Project-X _ Ultimate Body Blows (1994)(Team 17)[!][compilation].png",
  "Named_Snaps/Project-X _ Ultimate Body Blows (Europe).png",
  "Named_Snaps/Projekt - Lila (Germany) (Rev 1).png",
  "Named_Snaps/Projekt - Lila (Germany).png",
  "Named_Snaps/Psygnosis Collection (AmigaJay).png",
  "Named_Snaps/Quik the Thunder Rabbit (Europe).png",
  "Named_Snaps/Rise of the Robots (1994)(Time Warner Interactive)[!].png",
  "Named_Snaps/Rise of the Robots (Europe).png",
  "Named_Snaps/Roadkill (1994)(Acid Software)[!][CDD4971].png",
  "Named_Snaps/Roadkill (1995)(Acid Software)[!][GH 32].png",
  "Named_Snaps/Roadkill (Europe) (Alt).png",
  "Named_Snaps/Roadkill (Europe).png",
  "Named_Snaps/Run 'n Gun Collection (AmigaJay).png",
  "Named_Snaps/Ryder Cup - Johnnie Walker (Europe).png",
  "Named_Snaps/Ryder Cup by Johnnie Walker, The (1993)(Ocean)[!].png",
  "Named_Snaps/Sabre Team (1994)(Krisalis)(M5)[!].png",
  "Named_Snaps/Sabre Team (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Seek _ Destroy (1993)(Mindscape)[!].png",
  "Named_Snaps/Seek and Destroy (Europe).png",
  "Named_Snaps/Sensible Soccer - European Champions (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Sensible Soccer - European Champions v1.1 (1993)(Renegade)(M4)[!].png",
  "Named_Snaps/Seven Gates of Jambala, The (1993)(Unique)[!].png",
  "Named_Snaps/Seven Gates of Jambala, The (Europe).png",
  "Named_Snaps/Seven Over Par (AmigaJay).png",
  "Named_Snaps/Shadow Fighter (1995)(Gremlin)[!].png",
  "Named_Snaps/Shadow Fighter (Europe).png",
  "Named_Snaps/Sheer Delight (USA, Europe).png",
  "Named_Snaps/Simon the Sorcerer (1994)(Adventure Soft)[!].png",
  "Named_Snaps/Simon the Sorcerer (Europe).png",
  "Named_Snaps/Skeleton Krew (1995)(Core)[!].png",
  "Named_Snaps/Skeleton Krew (Europe).png",
  "Named_Snaps/Sleepwalker (1993)(Ocean)[!].png",
  "Named_Snaps/Sleepwalker (Europe).png",
  "Named_Snaps/Sleepwalker _ Pinball Fantasies (1993)(Commodore)[!][compilation][CDAC-055300 2].png",
  "Named_Snaps/Sleepwalker _ Pinball Fantasies (1993)(Commodore)[!][compilation][PFANTASCD32].png",
  "Named_Snaps/Sleepwalker _ Pinball Fantasies (USA).png",
  "Named_Snaps/Soccer Kid (1994)(Krisalis)(M5)[!].png",
  "Named_Snaps/Soccer Kid (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Soccer Superstars (1995)(Flair Software)(M5)[!].png",
  "Named_Snaps/Soccer Superstars (Europe).png",
  "Named_Snaps/Speedball 2 (1995)(Renegade)[!].png",
  "Named_Snaps/Speedball 2 (Europe).png",
  "Named_Snaps/Speris Legacy, The (1995)(Ocean - Team 17)[!][cp code].png",
  "Named_Snaps/Speris Legacy, The (Europe).png",
  "Named_Snaps/Sports - Football (USA).png",
  "Named_Snaps/Sports Football (1993)(Commodore)[!].png",
  "Named_Snaps/Star Crusader (1994)(Gametek - Take 2)[!][Amiga-CD32].png",
  "Named_Snaps/Star Crusader (Europe).png",
  "Named_Snaps/Star Wars Trilogy, The (AmigaJay).png",
  "Named_Snaps/Striker (1994)(Gremlin)[!].png",
  "Named_Snaps/Striker (Europe).png",
  "Named_Snaps/Strip Pot (1994)(Pixel Blue)[!].png",
  "Named_Snaps/Strip Pot (Europe).png",
  "Named_Snaps/Subwar 2050 (1994)(MicroProse)(M3)[!].png",
  "Named_Snaps/Subwar 2050 (Europe) (En,Fr,De).png",
  "Named_Snaps/Summer Olympix (1994)(Flair Software)[!].png",
  "Named_Snaps/Summer Olympix (Europe).png",
  "Named_Snaps/Super League Manager (1995)(Audiogenic)[!].png",
  "Named_Snaps/Super League Manager (Europe).png",
  "Named_Snaps/Super Methane Bros (1994)(Apache)[!][10329011 01].png",
  "Named_Snaps/Super Methane Bros (1994)(Apache)[!][BR00245-01].png",
  "Named_Snaps/Super Methane Bros. (Europe) (Alt).png",
  "Named_Snaps/Super Methane Bros. (Europe).png",
  "Named_Snaps/Super Putty (1994)(System 3)[!].png",
  "Named_Snaps/Super Putty (Europe).png",
  "Named_Snaps/Super Skidmarks (Europe) (Alt).png",
  "Named_Snaps/Super Skidmarks (Europe).png",
  "Named_Snaps/Super Skidmarks v2.2 (1995)(Acid Software)[!][GH 1 10 AUG 95].png",
  "Named_Snaps/Super Skidmarks v2.2 (1995)(Acid Software)[!][GH1 21 APR 95].png",
  "Named_Snaps/Super Stardust (1994)(Team 17)[!].png",
  "Named_Snaps/Super Stardust (Europe).png",
  "Named_Snaps/Super Street Fighter II Turbo (1995)(Gametek)[!].png",
  "Named_Snaps/Super Street Fighter II Turbo (Europe).png",
  "Named_Snaps/Superfrog (1994)(Team 17)[!].png",
  "Named_Snaps/Superfrog (Europe).png",
  "Named_Snaps/Surf Ninjas (1993)(Microvalue)[!].png",
  "Named_Snaps/Surf Ninjas (Europe).png",
  "Named_Snaps/Syndicate (1995)(Mindscape)(M3)[!].png",
  "Named_Snaps/Syndicate (Europe) (En,Fr,It).png",
  "Named_Snaps/Team 17 Collection (AmigaJay).png",
  "Named_Snaps/Tennis Tossers (AmigaJay).png",
  "Named_Snaps/Theme Park (1995)(Mindscape)[!].png",
  "Named_Snaps/Theme Park (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Thomas The Tank Engine _ Friends Pinball (1995)(Alternative Software).png",
  "Named_Snaps/Thomas The Tank Engine's Pinball (Europe).png",
  "Named_Snaps/Top Gear 2 (1994)(Gremlin)[!].png",
  "Named_Snaps/Top Gear 2 (Europe).png",
  "Named_Snaps/Total Carnage (1994)(ICE)[!].png",
  "Named_Snaps/Total Carnage (Europe).png",
  "Named_Snaps/Trivial Pursuit - The CD32 Edition (Europe).png",
  "Named_Snaps/Trivial Pursuit - The CD32 Edition v1.0C (1994)(Domark)[!].png",
  "Named_Snaps/Trolls (1993)(Flair Software)(PAL)[!].png",
  "Named_Snaps/Trolls (Europe).png",
  "Named_Snaps/UFO - Enemy Unknown (1994)(MicroProse)(M3)[!].png",
  "Named_Snaps/UFO - Enemy Unknown (Europe) (En,Fr,De).png",
  "Named_Snaps/Ultimate Body Blows (1994)(Team 17)[!].png",
  "Named_Snaps/Ultimate Body Blows (Europe).png",
  "Named_Snaps/Ultimate Dizzy Collection, The (AmigaJay).png",
  "Named_Snaps/Ultimate Super SkidMarks (1997)(Guildhall Leisure Services)[!][Amiga-CD32].png",
  "Named_Snaps/Ultimate Super Skidmarks (Europe).png",
  "Named_Snaps/Universe (1994)(Core)(M4)[!].png",
  "Named_Snaps/Universe (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Unreleased Amiga Game Collection (AmigaJay).png",
  "Named_Snaps/Vertical S.E.U Collection (AmigaJay).png",
  "Named_Snaps/Vital Light (1994)(Millennium)[!].png",
  "Named_Snaps/Vital Light (Europe) (Alt).png",
  "Named_Snaps/Vital Light (Europe).png",
  "Named_Snaps/Wembley International Soccer (1994)(Audiogenic)[!][10292711 01].png",
  "Named_Snaps/Wembley International Soccer (1994)(Audiogenic)[!][10292711 02].png",
  "Named_Snaps/Wembley International Soccer (Europe).png",
  "Named_Snaps/Wendetta 2175 (1996)(Skills)[!][Amiga-CD32].png",
  "Named_Snaps/Wendetta 2175 (1996)(Skills)[AGA][Amiga-CD32].png",
  "Named_Snaps/Wendetta 2175 (Europe).png",
  "Named_Snaps/Whale's Voyage (1994)(Flair Software)[!][CDD2736].png",
  "Named_Snaps/Whale's Voyage (1994)(Flair Software)[!][CDD3080].png",
  "Named_Snaps/Whale's Voyage (Europe) (Rev 1).png",
  "Named_Snaps/Whale's Voyage (Europe).png",
  "Named_Snaps/Whale's Voyage (Germany).png",
  "Named_Snaps/Whizz (1994)(Flair Software).png",
  "Named_Snaps/Whizz (Europe).png",
  "Named_Snaps/Wild Cup Soccer (1994)(Millennium)[!].png",
  "Named_Snaps/Wild Cup Soccer (Europe).png",
  "Named_Snaps/Will Bridge - Initiation Junior (Europe).png",
  "Named_Snaps/Will Bridge - Practice 1 - Initiation - Junior (1991)(Will Bridge)(FR)(en).png",
  "Named_Snaps/Wing Commander (1994)(Origin).png",
  "Named_Snaps/Worms (1995)(Ocean - Team 17)(M3)[!][cp code].png",
  "Named_Snaps/Worms (Europe) (En,Fr,De).png",
  "Named_Snaps/Ye Old Pirates Collection (AmigaJay).png",
  "Named_Snaps/Zool - Ninja of the 'Nth' Dimension (1993)(Gremlin)(PAL)[!].png",
  "Named_Snaps/Zool - Ninja of the Nth Dimension (Europe).png",
  "Named_Snaps/Zool 2 (1994)(Gremlin)[!].png",
  "Named_Snaps/Zool 2 (Europe) (Alt).png",
  "Named_Snaps/Zool 2 (Europe).png",
  "Named_Titles/ATR - All Terrain Racing (1995)(Team 17)[!].png",
  "Named_Titles/ATR - All Terrain Racing (Europe).png",
  "Named_Titles/Akira (1994)(ICE)[!].png",
  "Named_Titles/Akira (Europe).png",
  "Named_Titles/Alfred Chicken (1993)(Mindscape)[!].png",
  "Named_Titles/Alfred Chicken (Europe).png",
  "Named_Titles/Alien Breed - Tower Assault (1994)(Team 17)[!].png",
  "Named_Titles/Alien Breed - Tower Assault (Europe).png",
  "Named_Titles/Alien Breed 3D (1995)(Ocean - Team 17)[!][cp code].png",
  "Named_Titles/Alien Breed 3D (Europe).png",
  "Named_Titles/Alien Breed Special Edition _ Qwak (1994)(Team 17)[!][compilation].png",
  "Named_Titles/Alien Breed Special Edition _ Qwak (Europe) (En,Fr,De,It,Da).png",
  "Named_Titles/Amiga CD! Magazine No. 1 (UK).png",
  "Named_Titles/Amiga CD! Magazine No. 2 (UK).png",
  "Named_Titles/Amiga CD! Magazine No. 3 (UK).png",
  "Named_Titles/Amiga CD32 - Issue 1 (Spring) (UK).png",
  "Named_Titles/Amiga CD32 - Issue 2 (Winter) (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 01 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 02 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 03 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 04 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 05 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 06 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 07 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 08 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 09 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 10 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 11 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 12 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 13 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 14 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 15 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 16 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 17 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 18 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 19 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 20 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 21 (UK).png",
  "Named_Titles/Amiga CD32 Gamer Vol. 22 (UK).png",
  "Named_Titles/Amiga CD32 Special 1 (1994-12-08)(Paragon Publishing)(GB)[!][Lamborghini American Challenge].png",
  "Named_Titles/Amiga CD32 Special 2 (1995-01-12)(Paragon Publishing)(GB)[!][Quik The Thunder Rabbit].png",
  "Named_Titles/Amiga CD32 Special 3 (1995-04)(Paragon Publishing)(GB)[!][Vital Light].png",
  "Named_Titles/Amiga Christmas Crackers (AmigaJay).png",
  "Named_Titles/Amiga Power - Games Massive Volume 1 (UK).png",
  "Named_Titles/Arabian Nights (1993)(Buzz)(M4)[!].png",
  "Named_Titles/Arabian Nights (Europe) (En,Fr,De,It).png",
  "Named_Titles/Arcade Pool (1994)(Team 17)[!][CDD4978].png",
  "Named_Titles/Arcade Pool (1994)(Team 17)[!][CDR00281].png",
  "Named_Titles/Arcade Pool (Europe) (En,Fr,De,It) (Alt).png",
  "Named_Titles/Arcade Pool (Europe) (En,Fr,De,It).png",
  "Named_Titles/Assassins - Ultimate Games Compact Disc (Europe) (v2.0).png",
  "Named_Titles/Banshee (1994)(Core)(M4)[!].png",
  "Named_Titles/Banshee (Europe) (En,Fr,De,Da).png",
  "Named_Titles/Base Jumpers (1995)(Rasputin)[!].png",
  "Named_Titles/Base Jumpers (Europe).png",
  "Named_Titles/Battle Chess (1994)(Interplay)[!].png",
  "Named_Titles/Battle Chess (Europe).png",
  "Named_Titles/Battletoads (1994)(Mindscape)[!].png",
  "Named_Titles/Battletoads (Europe).png",
  "Named_Titles/Beavers (1994)(Unique)[!].png",
  "Named_Titles/Beavers (Europe).png",
  "Named_Titles/Beneath a Steel Sky (1994)(Virgin)(M4)[!].png",
  "Named_Titles/Beneath a Steel Sky (Europe) (En,Fr,De,It).png",
  "Named_Titles/Benefactor (1994)(Psygnosis)[!].png",
  "Named_Titles/Benefactor (Europe).png",
  "Named_Titles/Big 6, The (Europe).png",
  "Named_Titles/Big 6, The - Original Dizzy Adventure Games (1994)(Codemasters)[!][compilation].png",
  "Named_Titles/Bitmap Brothers Collection, The (AGA) (AmigaJay).png",
  "Named_Titles/Bitmap Brothers Collection, The (OCS) (AmigaJay).png",
  "Named_Titles/Black Viper (1996)(NEO)(M3)[!][Amiga-CD32].png",
  "Named_Titles/Black Viper (1996)(Neo)(M3).png",
  "Named_Titles/Black Viper (Europe) (En,De,It).png",
  "Named_Titles/Brian the Lion (Europe) (En,Fr,De,It) (Gameplay CD-ROM).png",
  "Named_Titles/Brian the Lion Starring in Rumble in the Jungle (1994)(Psygnosis)(M4)[!].png",
  "Named_Titles/Brutal - Paws of Fury (1995)(Gametek)(M3)[!].png",
  "Named_Titles/Brutal - Paws of Fury (Europe).png",
  "Named_Titles/Brutal Football (1994)(Millennium)[!].png",
  "Named_Titles/Brutal Football (Europe).png",
  "Named_Titles/Bubba 'N' Stix (1994)(Core)[!].png",
  "Named_Titles/Bubba 'n' Stix (Europe).png",
  "Named_Titles/Bubble Bobble Trilogy (AmigaJay).png",
  "Named_Titles/Bubble and Squeak (1994)(Audiogenic)[!].png",
  "Named_Titles/Bubble and Squeak (Europe).png",
  "Named_Titles/Bump 'N' Burn (1994)(Grandslam)[!].png",
  "Named_Titles/Bump 'n' Burn (Europe).png",
  "Named_Titles/CD Exchange - Volume 1 (UK).png",
  "Named_Titles/Candy Puzzle (1996)(Gevin)[CUBO].png",
  "Named_Titles/Cannon Fodder (1993)(Virgin)[!][Amiga-CD32].png",
  "Named_Titles/Cannon Fodder (1993)(Virgin)[Amiga-CD32][a].png",
  "Named_Titles/Cannon Fodder (Europe).png",
  "Named_Titles/Castles II - Siege _ Conquest (1993)(Interplay)[!].png",
  "Named_Titles/Castles II - Siege _ Conquest (Europe).png",
  "Named_Titles/Cedric and the Lost Sceptre (Europe).png",
  "Named_Titles/Cedric and the lost sceptre (1996)(NEO)(de-en)[!][AGA-CD32].png",
  "Named_Titles/Center Court Tennis 2 (2016-07-21)(Fritsche, Gernot)(FW)[!].png",
  "Named_Titles/Chambers of Shaolin (1993)(Unique)[!].png",
  "Named_Titles/Chambers of Shaolin (Europe).png",
  "Named_Titles/Chaos Engine, The (1994)(Renegade)[!][CDD3445].png",
  "Named_Titles/Chaos Engine, The (1994)(Renegade)[!][Spectacular Voyage][CDD3446].png",
  "Named_Titles/Chaos Engine, The (Europe) (En,Fr,De,It).png",
  "Named_Titles/Chaos Engine, The (Europe) (Spectacular Voyage).png",
  "Named_Titles/Chuck Rock (1994)(Core)[!].png",
  "Named_Titles/Chuck Rock (Europe).png",
  "Named_Titles/Chuck Rock II - Son of Chuck (1994)(Core)[!].png",
  "Named_Titles/Chuck Rock II - Son of Chuck (Europe).png",
  "Named_Titles/Classic Lotus Trilogy, The (1994)(Gremlin)(PAL)[!][compilation].png",
  "Named_Titles/Classic Lotus Trilogy, The (Europe).png",
  "Named_Titles/Clockwiser (1994)(Rasputin)[!].png",
  "Named_Titles/Clockwiser (Europe).png",
  "Named_Titles/Clou!, Der (Germany).png",
  "Named_Titles/Clue!, The (1994)(Kompart)[!].png",
  "Named_Titles/Communicator (Germany) (En,De).png",
  "Named_Titles/D-Generation (Europe).png",
  "Named_Titles/D-Generation v1.0 (1993)(Mindscape)[!].png",
  "Named_Titles/D-Generation v1.0 (1993)(Mindscape)[b].png",
  "Named_Titles/Dangerous Streets (1993)(Flair Software)[!].png",
  "Named_Titles/Dangerous Streets (Europe) (En,Fr,De,It).png",
  "Named_Titles/Dangerous Streets _ Wing Commander (1993)(Commodore)[!][compilation].png",
  "Named_Titles/Dangerous Streets _ Wing Commander (Europe) (En,Fr,De,It).png",
  "Named_Titles/Darkseed (Europe).png",
  "Named_Titles/Darkseed v1.1 (1994)(Cyberdreams)[!].png",
  "Named_Titles/Death Mask (1994)(Alternative Software)[!].png",
  "Named_Titles/Death Mask (Europe) (En,Fr,De,It).png",
  "Named_Titles/Deep Core (Europe) (v1.00).png",
  "Named_Titles/Deep Core (Europe) (v1.01).png",
  "Named_Titles/Deep Core v1.00 (1993)(ICE)[!][CDD2840].png",
  "Named_Titles/Deep Core v1.01 (1993)(ICE)[!][CDD2998].png",
  "Named_Titles/Defender of the Crown II (Europe).png",
  "Named_Titles/Defender of the Crown II (USA).png",
  "Named_Titles/Demo Disc, The - Commodore Amiga CD32 Demonstration Disc 2.0 (Europe).png",
  "Named_Titles/Dennis (1993)(Ocean)[!].png",
  "Named_Titles/Dennis (Europe).png",
  "Named_Titles/Diggers (1993)(Millennium)(NTSC)[!].png",
  "Named_Titles/Diggers (Europe).png",
  "Named_Titles/Diggers _ Oscar (1993)(Commodore)[!][compilation][AMIGA-CD 31, 54].png",
  "Named_Titles/Diggers _ Oscar (1993)(Commodore)[!][compilation][AMIGA-CD-V2].png",
  "Named_Titles/Diggers _ Oscar (Europe) (Rev 1) (Alt).png",
  "Named_Titles/Diggers _ Oscar (Europe) (Rev 1).png",
  "Named_Titles/Diggers _ Oscar (Europe).png",
  "Named_Titles/Disposable Hero (1994)(Gremlin)(PAL)[!].png",
  "Named_Titles/Disposable Hero (Europe).png",
  "Named_Titles/Donk! The Samurai Duck! (1994)(Supervision)[!].png",
  "Named_Titles/Donk! The Samurai Duck! (1994)(Supervision)[a].png",
  "Named_Titles/Donk! The Samurai Duck! (Europe).png",
  "Named_Titles/Dragonstone (1995)(Core)(M3)[!].png",
  "Named_Titles/Dragonstone (Europe) (En,Fr,De).png",
  "Named_Titles/Emerald Mines (1994)(Almathera)[!][compilation][CDD4410].png",
  "Named_Titles/Emerald Mines (Europe).png",
  "Named_Titles/Erben der Erde - Die grosse Suche (1995)(Softgold)(DE)[!][Amiga-CD32-CDTV].png",
  "Named_Titles/Erben der Erde - Die grosse Suche (1995)(Softgold)(DE)[AGA-CD32].png",
  "Named_Titles/Exile (1995)(Audiogenic)[!].png",
  "Named_Titles/Exile (Europe).png",
  "Named_Titles/F1 Collection (AmigaJay).png",
  "Named_Titles/Factor 5 Collection (AmigaJay).png",
  "Named_Titles/Fears (1995)(Guildhall Leisure Services)[!].png",
  "Named_Titles/Fears (1995)(attic)(DE)(en)[!].png",
  "Named_Titles/Fears (Europe).png",
  "Named_Titles/Fields of Glory (1994)(MicroProse)(M3)[!].png",
  "Named_Titles/Fields of Glory (Europe) (En,Fr,De).png",
  "Named_Titles/Fightin' Spirit (1996)(NEO)(M3)[!][Amiga-CD32].png",
  "Named_Titles/Fightin' Spirit (Europe) (En,De,It).png",
  "Named_Titles/Final Gate, The (1997)(Alternative Software - Bigg Wolf).png",
  "Named_Titles/Final Gate, The (Europe).png",
  "Named_Titles/Fire Force (1993)(Buzz)[!].png",
  "Named_Titles/Fire Force (Europe).png",
  "Named_Titles/Fire _ Ice - The Daring Adventures of Cool Coyote (1994)(Renegade)[!].png",
  "Named_Titles/Fire _ Ice - The Daring Adventures of Cool Coyote (Europe) (En,Fr,De,It).png",
  "Named_Titles/Flink (1994)(Psygnosis)[!].png",
  "Named_Titles/Flink (Europe).png",
  "Named_Titles/Fly Harder (1993)(Buzz)[!].png",
  "Named_Titles/Fly Harder (Europe).png",
  "Named_Titles/Football Fever (AmigaJay).png",
  "Named_Titles/Frog Feast (2007)(Oldergames)[!].png",
  "Named_Titles/Frontier - Elite II (Europe).png",
  "Named_Titles/Frontier - Elite II v1.10 (1994)(Gametek - Konami)[!].png",
  "Named_Titles/Fury of the Furries (1994)(Kalisto - Mindscape)[!].png",
  "Named_Titles/Fury of the Furries (Europe).png",
  "Named_Titles/Gamers' Delight (Europe) (En,De).png",
  "Named_Titles/Global Effect (1994)(Millennium)[!].png",
  "Named_Titles/Global Effect (Europe).png",
  "Named_Titles/Gloom (1995)(Guildhall Leisure Services)[!].png",
  "Named_Titles/Gloom (Europe).png",
  "Named_Titles/Grandslam Gamer Gold Collection (1995)(Grandslam)[!][compilation].png",
  "Named_Titles/Grandslam Gamer Gold Collection (Europe).png",
  "Named_Titles/Guardian (1994)(Acid Software)[!][10325611].png",
  "Named_Titles/Guardian (1994)(Acid Software)[!][BR00424].png",
  "Named_Titles/Guardian (1994)(Acid Software)[!][BR00424-01].png",
  "Named_Titles/Guardian (1995)(Acid Software)[!][GH33].png",
  "Named_Titles/Guardian (Europe) (Alt).png",
  "Named_Titles/Guardian (Europe).png",
  "Named_Titles/Gulp! (1994)(ICE)(M5)[!].png",
  "Named_Titles/Gulp! (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Gunship 2000 (1994)(MicroProse)[!].png",
  "Named_Titles/Gunship 2000 (Europe).png",
  "Named_Titles/Heimdall 2 (1994)(Core)[!].png",
  "Named_Titles/Heimdall 2 - Into the Hall of Worlds (Europe).png",
  "Named_Titles/HeroQuest II - Legacy of Sorasil (1994)(Gremlin).png",
  "Named_Titles/HeroQuest II - Legacy of Sorasil (Europe) (En,Fr,De).png",
  "Named_Titles/Humans (1994)(Gametek - Imagitec Design)(M5)[!].png",
  "Named_Titles/Humans (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Humans 3 - Evolution - Lost in Time... (Europe).png",
  "Named_Titles/Hunter (AmigaJay).png",
  "Named_Titles/Impossible Mission 2025 - The Special Edition (1994)(MicroProse)[!].png",
  "Named_Titles/Impossible Mission 2025 - The Special Edition (Europe).png",
  "Named_Titles/Indy Heat _ Super Off Road (AmigaJay).png",
  "Named_Titles/International Karate + (1994)(System 3)[!].png",
  "Named_Titles/International Karate + (Europe).png",
  "Named_Titles/International Open Golf Championship (1993)(Ocean).png",
  "Named_Titles/International Open Golf Championship (Europe).png",
  "Named_Titles/International Sensible Soccer - World Champions (Europe) (En,Fr,De,It).png",
  "Named_Titles/International Sensible Soccer - World Champions v1.2 (1994)(Renegade)(M4)[!].png",
  "Named_Titles/Isometric Racer Collection (AmigaJay).png",
  "Named_Titles/James Pond 2 - Robocod (1993)(Millennium)[!].png",
  "Named_Titles/James Pond 2 - Robocod (Europe).png",
  "Named_Titles/James Pond 3 - Operation Starfi5h (1994)(Kixx)[budget].png",
  "Named_Titles/James Pond 3 - Operation Starfi5h (1994)(Millennium)[!].png",
  "Named_Titles/James Pond 3 - Operation Starfi5h (Europe) (Kixx).png",
  "Named_Titles/James Pond 3 - Operation Starfi5h (Europe).png",
  "Named_Titles/Jetstrike (1995)(Rasputin)[!].png",
  "Named_Titles/Jetstrike CD32 (Europe).png",
  "Named_Titles/Jim Power in Mutant Planet (Europe).png",
  "Named_Titles/John Barnes European Football (1993)(Buzz)(M5)[!].png",
  "Named_Titles/John Barnes European Football (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Jungle Strike - The Sequel to Desert Strike (1994)(Ocean)[!].png",
  "Named_Titles/Jungle Strike - The Sequel to Desert Strike (Europe).png",
  "Named_Titles/Kang Fu (1996)(ALTER interservice - Greed)[!][Amiga-CD32].png",
  "Named_Titles/Kang Fu (Europe).png",
  "Named_Titles/Kid Chaos (1994)(Ocean)[!].png",
  "Named_Titles/Kid Chaos (Europe).png",
  "Named_Titles/Kingpin - Arcade Sports Bowling (1995)(Team 17)[!].png",
  "Named_Titles/Kingpin - Arcade Sports Bowling (Europe) (En,Fr,De,It).png",
  "Named_Titles/Labyrinth of Time, The (1994)(Electronic Arts)[!][Amiga-CD32-CDTV].png",
  "Named_Titles/Labyrinth of Time, The (Europe).png",
  "Named_Titles/Lamborghini - American Challenge (Europe).png",
  "Named_Titles/Lamborghini American Challenge (1994)(Titus)[CDR000363].png",
  "Named_Titles/Last Ninja 3 (1994)(System 3)[!].png",
  "Named_Titles/Last Ninja 3 (Europe).png",
  "Named_Titles/Legends (1996)(Guildhall Leisure Services)(M3)[!].png",
  "Named_Titles/Legends (Europe) (En,Fr,De).png",
  "Named_Titles/Lemmings (1994)(Psygnosis)[!].png",
  "Named_Titles/Lemmings (Europe).png",
  "Named_Titles/Liberation - Captive II (Europe) (Rev 1).png",
  "Named_Titles/Liberation - Captive II (Europe) (Rev 2).png",
  "Named_Titles/Liberation - Captive II (Europe) (Rev 3).png",
  "Named_Titles/Liberation - Captive II (Europe).png",
  "Named_Titles/Liberation - Captive II v2.00-1.92 (1993-11-25)(Mindscape)[!][CDD2904].png",
  "Named_Titles/Liberation - Captive II v2.00b-2.00 (1993-12-08)(Mindscape)[!][CDD2955].png",
  "Named_Titles/Liberation - Captive II v2.00c-2.00c (1994-01-26)(Mindscape)[!][CDD3218].png",
  "Named_Titles/Liberation - Captive II v2.02-2.00c (1994-04-08)(Mindscape)[!][CDD3716].png",
  "Named_Titles/Liquid Kids _ Snow Bros (AmigaJay).png",
  "Named_Titles/Litil Divil (1994)(Gremlin)[!].png",
  "Named_Titles/Litil Divil (Europe).png",
  "Named_Titles/Lost Vikings, The (1993)(Interplay)[!].png",
  "Named_Titles/Lost Vikings, The (Europe).png",
  "Named_Titles/Mag!!! (1996)(Greenwood)(DE)[!][Amiga-CD32][M R-0568 A].png",
  "Named_Titles/Magic Island (Czech).png",
  "Named_Titles/Manchester United - Premier League Champions (Europe) (En,Fr,De,It) (Rev 1).png",
  "Named_Titles/Manchester United - Premier League Champions (Europe) (En,Fr,De,It).png",
  "Named_Titles/Manchester United - Premier League Champions v1.0CD (1994)(Krisalis)(M4)[!][CDD4783].png",
  "Named_Titles/Manchester United - Premier League Champions v1.0CD (1994)(Krisalis)(M4)[!][CDD5049].png",
  "Named_Titles/Marvin's Marvellous Adventure (1995)(21st Century Entertainment)(M4)[!].png",
  "Named_Titles/Marvin's Marvellous Adventure (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Mean Arenas (1993)(ICE)[!].png",
  "Named_Titles/Mean Arenas (Europe).png",
  "Named_Titles/Microcosm (1994)(Psygnosis)[!][MCD32-1 11].png",
  "Named_Titles/Microcosm (1994)(Psygnosis)[!][Spectacular Voyage][MICROCOSM-CD32].png",
  "Named_Titles/Microcosm (Europe) (Alt).png",
  "Named_Titles/Microcosm (Europe).png",
  "Named_Titles/Morph (1993)(Millennium)[!].png",
  "Named_Titles/Morph (Europe).png",
  "Named_Titles/Mutation Gold Compilation (1998)(Mutation)[Amiga-CD32].png",
  "Named_Titles/Myst (1997)(PXL computers)[!][Amiga-CD32].png",
  "Named_Titles/Myth - History in the Making (1994)(System 3)[!].png",
  "Named_Titles/Myth - History in the Making (Europe).png",
  "Named_Titles/Naughty Ones (1994)(Interactivision)[!].png",
  "Named_Titles/Naughty Ones (Europe).png",
  "Named_Titles/Nick Faldos Championship Golf (1994)(Grandslam)[!].png",
  "Named_Titles/Nick Faldos Championship Golf (Europe).png",
  "Named_Titles/Nigel Mansell's World Championship (1993)(Gremlin)(PAL)[!][CDD4197].png",
  "Named_Titles/Nigel Mansell's World Championship (1993)(Gremlin)(PAL)[!][S NIGEL 1 02].png",
  "Named_Titles/Nigel Mansell's World Championship (Europe) (Alt).png",
  "Named_Titles/Nigel Mansell's World Championship (Europe).png",
  "Named_Titles/Oscar (1993)(Flair).png",
  "Named_Titles/Oscar (Europe).png",
  "Named_Titles/Overhead Racer Collection (AmigaJay).png",
  "Named_Titles/Overkill _ Lunar-C (1993)(Mindscape)[!][compilation].png",
  "Named_Titles/Overkill _ Lunar-C (Europe).png",
  "Named_Titles/PGA European Tour (1994)(Ocean)[!].png",
  "Named_Titles/PGA European Tour (Europe).png",
  "Named_Titles/Pierre Le Chef Is ... Out to Lunch (Europe).png",
  "Named_Titles/Pierre le Chef is... Out to Lunch (1994)(Mindscape)[!].png",
  "Named_Titles/Pinball Fantasies (1993)(21st Century Entertainment)[!].png",
  "Named_Titles/Pinball Fantasies (Europe).png",
  "Named_Titles/Pinball Illusions (1995)(21st Century Entertainment)[!].png",
  "Named_Titles/Pinball Illusions (Europe).png",
  "Named_Titles/Pinball Prelude (1996)(Effigy Software)[!][Amiga-CD32-PC].png",
  "Named_Titles/Pinball Prelude (Europe).png",
  "Named_Titles/Pinocchio (Europe).png",
  "Named_Titles/Pirates! Gold (1993)(MicroProse)[!].png",
  "Named_Titles/Pirates! Gold (Europe) (En,De).png",
  "Named_Titles/Power Drive (1994)(U.S. Gold)(M5)[!].png",
  "Named_Titles/Power Drive (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Power-Games (Europe) (En,De).png",
  "Named_Titles/Premiere (1994)(Core)[!].png",
  "Named_Titles/Premiere (Europe).png",
  "Named_Titles/Prey - An Alien Encounter (1993)(Almathera)[!].png",
  "Named_Titles/Prey - An Alien Encounter (Europe).png",
  "Named_Titles/Project-X _ F17 Challenge (1993)(Team 17)[!][compilation][CDD3187].png",
  "Named_Titles/Project-X _ F17 Challenge (Europe) (En,Fr,De,It,Da) (v2.0).png",
  "Named_Titles/Project-X _ F17 Challenge (Europe) (En,Fr,De,It,Da).png",
  "Named_Titles/Project-X _ F17 Challenge v2.0 (1993)(Team 17)[!][compilation][CDD3499].png",
  "Named_Titles/Project-X _ Ultimate Body Blows (1994)(Team 17)[!][compilation].png",
  "Named_Titles/Project-X _ Ultimate Body Blows (Europe).png",
  "Named_Titles/Projekt - Lila (Germany) (Rev 1).png",
  "Named_Titles/Projekt - Lila (Germany).png",
  "Named_Titles/Psygnosis Collection (AmigaJay).png",
  "Named_Titles/Quik the Thunder Rabbit (Europe).png",
  "Named_Titles/Rise of the Robots (1994)(Time Warner Interactive)[!].png",
  "Named_Titles/Rise of the Robots (Europe).png",
  "Named_Titles/Roadkill (1994)(Acid Software)[!][CDD4971].png",
  "Named_Titles/Roadkill (1995)(Acid Software)[!][GH 32].png",
  "Named_Titles/Roadkill (Europe) (Alt).png",
  "Named_Titles/Roadkill (Europe).png",
  "Named_Titles/Run 'n Gun Collection (AmigaJay).png",
  "Named_Titles/Ryder Cup - Johnnie Walker (Europe).png",
  "Named_Titles/Ryder Cup by Johnnie Walker, The (1993)(Ocean)[!].png",
  "Named_Titles/Sabre Team (1994)(Krisalis)(M5)[!].png",
  "Named_Titles/Sabre Team (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Seek _ Destroy (1993)(Mindscape)[!].png",
  "Named_Titles/Seek and Destroy (Europe).png",
  "Named_Titles/Sensible Soccer - European Champions (Europe) (En,Fr,De,It).png",
  "Named_Titles/Sensible Soccer - European Champions v1.1 (1993)(Renegade)(M4)[!].png",
  "Named_Titles/Seven Gates of Jambala, The (1993)(Unique)[!].png",
  "Named_Titles/Seven Gates of Jambala, The (Europe).png",
  "Named_Titles/Seven Over Par (AmigaJay).png",
  "Named_Titles/Shadow Fighter (1995)(Gremlin)[!].png",
  "Named_Titles/Shadow Fighter (Europe).png",
  "Named_Titles/Sheer Delight (USA, Europe).png",
  "Named_Titles/Simon the Sorcerer (1994)(Adventure Soft)[!].png",
  "Named_Titles/Simon the Sorcerer (Europe).png",
  "Named_Titles/Skeleton Krew (1995)(Core)[!].png",
  "Named_Titles/Skeleton Krew (Europe).png",
  "Named_Titles/Sleepwalker (1993)(Ocean)[!].png",
  "Named_Titles/Sleepwalker (Europe).png",
  "Named_Titles/Sleepwalker _ Pinball Fantasies (1993)(Commodore)[!][compilation][CDAC-055300 2].png",
  "Named_Titles/Sleepwalker _ Pinball Fantasies (1993)(Commodore)[!][compilation][PFANTASCD32].png",
  "Named_Titles/Sleepwalker _ Pinball Fantasies (USA).png",
  "Named_Titles/Soccer Kid (1994)(Krisalis)(M5)[!].png",
  "Named_Titles/Soccer Kid (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Soccer Superstars (1995)(Flair Software)(M5)[!].png",
  "Named_Titles/Soccer Superstars (Europe).png",
  "Named_Titles/Speedball 2 (1995)(Renegade)[!].png",
  "Named_Titles/Speedball 2 (Europe).png",
  "Named_Titles/Speris Legacy, The (1995)(Ocean - Team 17)[!][cp code].png",
  "Named_Titles/Speris Legacy, The (Europe).png",
  "Named_Titles/Sports - Football (USA).png",
  "Named_Titles/Sports Football (1993)(Commodore)[!].png",
  "Named_Titles/Star Crusader (1994)(Gametek - Take 2)[!][Amiga-CD32].png",
  "Named_Titles/Star Crusader (Europe).png",
  "Named_Titles/Star Wars Trilogy, The (AmigaJay).png",
  "Named_Titles/Striker (1994)(Gremlin)[!].png",
  "Named_Titles/Striker (Europe).png",
  "Named_Titles/Strip Pot (1994)(Pixel Blue)[!].png",
  "Named_Titles/Strip Pot (Europe).png",
  "Named_Titles/Subwar 2050 (1994)(MicroProse)(M3)[!].png",
  "Named_Titles/Subwar 2050 (Europe) (En,Fr,De).png",
  "Named_Titles/Summer Olympix (1994)(Flair Software)[!].png",
  "Named_Titles/Summer Olympix (Europe).png",
  "Named_Titles/Super League Manager (1995)(Audiogenic)[!].png",
  "Named_Titles/Super League Manager (Europe).png",
  "Named_Titles/Super Methane Bros (1994)(Apache)[!][10329011 01].png",
  "Named_Titles/Super Methane Bros (1994)(Apache)[!][BR00245-01].png",
  "Named_Titles/Super Methane Bros. (Europe) (Alt).png",
  "Named_Titles/Super Methane Bros. (Europe).png",
  "Named_Titles/Super Putty (1994)(System 3)[!].png",
  "Named_Titles/Super Putty (Europe).png",
  "Named_Titles/Super Skidmarks (Europe) (Alt).png",
  "Named_Titles/Super Skidmarks (Europe).png",
  "Named_Titles/Super Skidmarks v2.2 (1995)(Acid Software)[!][GH 1 10 AUG 95].png",
  "Named_Titles/Super Skidmarks v2.2 (1995)(Acid Software)[!][GH1 21 APR 95].png",
  "Named_Titles/Super Stardust (1994)(Team 17)[!].png",
  "Named_Titles/Super Stardust (Europe).png",
  "Named_Titles/Super Street Fighter II Turbo (1995)(Gametek)[!].png",
  "Named_Titles/Super Street Fighter II Turbo (Europe).png",
  "Named_Titles/Superfrog (1994)(Team 17)[!].png",
  "Named_Titles/Superfrog (Europe).png",
  "Named_Titles/Surf Ninjas (1993)(Microvalue)[!].png",
  "Named_Titles/Surf Ninjas (Europe).png",
  "Named_Titles/Syndicate (1995)(Mindscape)(M3)[!].png",
  "Named_Titles/Syndicate (Europe) (En,Fr,It).png",
  "Named_Titles/Team 17 Collection (AmigaJay).png",
  "Named_Titles/Tennis Tossers (AmigaJay).png",
  "Named_Titles/Theme Park (1995)(Mindscape)[!].png",
  "Named_Titles/Theme Park (Europe) (En,Fr,De,It).png",
  "Named_Titles/Thomas The Tank Engine _ Friends Pinball (1995)(Alternative Software).png",
  "Named_Titles/Thomas the Tank Engine's Pinball (Europe).png",
  "Named_Titles/Top Gear 2 (1994)(Gremlin)[!].png",
  "Named_Titles/Top Gear 2 (Europe).png",
  "Named_Titles/Total Carnage (1994)(ICE)[!].png",
  "Named_Titles/Total Carnage (Europe).png",
  "Named_Titles/Trivial Pursuit - The CD32 Edition (Europe).png",
  "Named_Titles/Trivial Pursuit - The CD32 Edition v1.0C (1994)(Domark)[!].png",
  "Named_Titles/Trolls (1993)(Flair Software)(PAL)[!].png",
  "Named_Titles/Trolls (Europe).png",
  "Named_Titles/UFO - Enemy Unknown (1994)(MicroProse)(M3)[!].png",
  "Named_Titles/UFO - Enemy Unknown (Europe) (En,Fr,De).png",
  "Named_Titles/Ultimate Body Blows (1994)(Team 17)[!].png",
  "Named_Titles/Ultimate Body Blows (Europe).png",
  "Named_Titles/Ultimate Dizzy Collection, The (AmigaJay).png",
  "Named_Titles/Ultimate Super SkidMarks (1997)(Guildhall Leisure Services)[!][Amiga-CD32].png",
  "Named_Titles/Ultimate Super Skidmarks (Europe).png",
  "Named_Titles/Universe (1994)(Core)(M4)[!].png",
  "Named_Titles/Universe (Europe) (En,Fr,De,It).png",
  "Named_Titles/Unreleased Amiga Game Collection (AmigaJay).png",
  "Named_Titles/Vertical S.E.U Collection (AmigaJay).png",
  "Named_Titles/Vital Light (1994)(Millennium)[!].png",
  "Named_Titles/Vital Light (Europe) (Alt).png",
  "Named_Titles/Vital Light (Europe).png",
  "Named_Titles/Wembley International Soccer (1994)(Audiogenic)[!][10292711 01].png",
  "Named_Titles/Wembley International Soccer (1994)(Audiogenic)[!][10292711 02].png",
  "Named_Titles/Wembley International Soccer (Europe).png",
  "Named_Titles/Wendetta 2175 (1996)(Skills)[!][Amiga-CD32].png",
  "Named_Titles/Wendetta 2175 (1996)(Skills)[AGA][Amiga-CD32].png",
  "Named_Titles/Wendetta 2175 (Europe).png",
  "Named_Titles/Whale's Voyage (1994)(Flair Software)[!][CDD2736].png",
  "Named_Titles/Whale's Voyage (1994)(Flair Software)[!][CDD3080].png",
  "Named_Titles/Whale's Voyage (Europe) (Rev 1).png",
  "Named_Titles/Whale's Voyage (Europe).png",
  "Named_Titles/Whale's Voyage (Germany).png",
  "Named_Titles/Whizz (1994)(Flair Software).png",
  "Named_Titles/Whizz (Europe).png",
  "Named_Titles/Wild Cup Soccer (1994)(Millennium)[!].png",
  "Named_Titles/Wild Cup Soccer (Europe).png",
  "Named_Titles/Will Bridge - Initiation Junior (Europe).png",
  "Named_Titles/Will Bridge - Practice 1 - Initiation - Junior (1991)(Will Bridge)(FR)(en).png",
  "Named_Titles/Wing Commander (1994)(Origin).png",
  "Named_Titles/Worms (1995)(Ocean - Team 17)(M3)[!][cp code].png",
  "Named_Titles/Worms (Europe) (En,Fr,De).png",
  "Named_Titles/Ye Old Pirates Collection (AmigaJay).png",
  "Named_Titles/Zool - Ninja of the 'Nth' Dimension (1993)(Gremlin)(PAL)[!].png",
  "Named_Titles/Zool - Ninja of the Nth Dimension (Europe).png",
  "Named_Titles/Zool 2 (1994)(Gremlin)[!].png",
  "Named_Titles/Zool 2 (Europe) (Alt).png",
  "Named_Titles/Zool 2 (Europe).png",
}
