return {
  "Named_Boxarts/3D Bowling (USA, Europe).png",
  "Named_Boxarts/3D Soccer (Europe).png",
  "Named_Boxarts/Alien Invaders (USA, Europe).png",
  "Named_Boxarts/American Football (USA, Europe).png",
  "Named_Boxarts/Astro Invader (Europe).png",
  "Named_Boxarts/Autorace (Europe).png",
  "Named_Boxarts/Baseball (USA, Europe).png",
  "Named_Boxarts/Basketball (Europe).png",
  "Named_Boxarts/Blackjack and Poker (Europe).png",
  "Named_Boxarts/Boxing (Europe).png",
  "Named_Boxarts/Brain Quiz (USA, Europe).png",
  "Named_Boxarts/Breakaway (USA, Europe).png",
  "Named_Boxarts/Capture (USA, Europe).png",
  "Named_Boxarts/Cat Trax (USA, Europe).png",
  "Named_Boxarts/Circus (Europe).png",
  "Named_Boxarts/Combat (Europe).png",
  "Named_Boxarts/Crazy Climber (Europe).png",
  "Named_Boxarts/Crazy Gobbler (Europe).png",
  "Named_Boxarts/Escape (USA, Europe).png",
  "Named_Boxarts/Funky Fish (Europe).png",
  "Named_Boxarts/Golf (Europe).png",
  "Named_Boxarts/Grand Slam Tennis (USA, Europe).png",
  "Named_Boxarts/Hobo (Europe).png",
  "Named_Boxarts/Horse Racing (Europe).png",
  "Named_Boxarts/Jump Bug (Europe).png",
  "Named_Boxarts/Jungler (USA, Europe).png",
  "Named_Boxarts/Missile War (USA, Europe).png",
  "Named_Boxarts/Monaco Grand Prix (Europe).png",
  "Named_Boxarts/Nibblemen (Europe).png",
  "Named_Boxarts/Ocean Battle (USA, Europe).png",
  "Named_Boxarts/Parashooter (Europe).png",
  "Named_Boxarts/Pleiades (Europe).png",
  "Named_Boxarts/R2D Tank (Europe).png",
  "Named_Boxarts/Red Clash (USA, Europe).png",
  "Named_Boxarts/Robot Killer (Europe).png",
  "Named_Boxarts/Route 16 (Europe).png",
  "Named_Boxarts/Soccer (USA, Europe).png",
  "Named_Boxarts/Space Attack (USA, Europe).png",
  "Named_Boxarts/Space Mission (USA, Europe).png",
  "Named_Boxarts/Space Raiders (USA, Europe).png",
  "Named_Boxarts/Space Squadron (Europe).png",
  "Named_Boxarts/Space Vultures (USA, Europe).png",
  "Named_Boxarts/Spiders (USA, Europe).png",
  "Named_Boxarts/Star Chess (USA, Europe).png",
  "Named_Boxarts/Super Gobbler (Europe).png",
  "Named_Boxarts/Tanks a Lot (USA, Europe).png",
  "Named_Boxarts/The End (Europe).png",
  "Named_Boxarts/Turtles (Europe).png",
  "Named_Logos/3D Bowling (USA, Europe).png",
  "Named_Logos/3D Soccer (Europe).png",
  "Named_Logos/Alien Invaders (USA, Europe).png",
  "Named_Logos/American Football (USA, Europe).png",
  "Named_Logos/Astro Invader (Europe).png",
  "Named_Logos/Autorace (Europe).png",
  "Named_Logos/Baseball (USA, Europe).png",
  "Named_Logos/Basketball (Europe).png",
  "Named_Logos/Blackjack and Poker (Europe).png",
  "Named_Logos/Boxing (Europe).png",
  "Named_Logos/Brain Quiz (USA, Europe).png",
  "Named_Logos/Breakaway (USA, Europe).png",
  "Named_Logos/Capture (USA, Europe).png",
  "Named_Logos/Cat Trax (USA, Europe).png",
  "Named_Logos/Circus (Europe).png",
  "Named_Logos/Combat (Europe).png",
  "Named_Logos/Crazy Climber (Europe).png",
  "Named_Logos/Crazy Gobbler (Europe).png",
  "Named_Logos/Escape (USA, Europe).png",
  "Named_Logos/Funky Fish (Europe).png",
  "Named_Logos/Golf (Europe).png",
  "Named_Logos/Grand Slam Tennis (USA, Europe).png",
  "Named_Logos/Hobo (Europe).png",
  "Named_Logos/Horse Racing (Europe).png",
  "Named_Logos/Jump Bug (Europe).png",
  "Named_Logos/Jungler (USA, Europe).png",
  "Named_Logos/Missile War (USA, Europe).png",
  "Named_Logos/Monaco Grand Prix (Europe).png",
  "Named_Logos/Nibblemen (Europe).png",
  "Named_Logos/Ocean Battle (USA, Europe).png",
  "Named_Logos/Parashooter (Europe).png",
  "Named_Logos/Pleiades (Europe).png",
  "Named_Logos/R2D Tank (Europe).png",
  "Named_Logos/Red Clash (USA, Europe).png",
  "Named_Logos/Robot Killer (Europe).png",
  "Named_Logos/Route 16 (Europe).png",
  "Named_Logos/Soccer (USA, Europe).png",
  "Named_Logos/Space Attack (USA, Europe).png",
  "Named_Logos/Space Mission (USA, Europe).png",
  "Named_Logos/Space Raiders (USA, Europe).png",
  "Named_Logos/Space Squadron (Europe).png",
  "Named_Logos/Space Vultures (USA, Europe).png",
  "Named_Logos/Spiders (USA, Europe).png",
  "Named_Logos/Star Chess (USA, Europe).png",
  "Named_Logos/Super Gobbler (Europe).png",
  "Named_Logos/Tanks a Lot (USA, Europe).png",
  "Named_Logos/The End (Europe).png",
  "Named_Logos/Turtles (Europe).png",
  "Named_Snaps/3D Bowling (USA, Europe).png",
  "Named_Snaps/3D Soccer (Europe).png",
  "Named_Snaps/Alien Invaders (USA, Europe).png",
  "Named_Snaps/American Football (USA, Europe).png",
  "Named_Snaps/Astro Invader (Europe).png",
  "Named_Snaps/Autorace (Europe).png",
  "Named_Snaps/Baseball (USA, Europe).png",
  "Named_Snaps/Basketball (Europe).png",
  "Named_Snaps/Blackjack and Poker (Europe).png",
  "Named_Snaps/Boxing (Europe).png",
  "Named_Snaps/Brain Quiz (USA, Europe).png",
  "Named_Snaps/Breakaway (USA, Europe).png",
  "Named_Snaps/Capture (USA, Europe).png",
  "Named_Snaps/Cat Trax (USA, Europe).png",
  "Named_Snaps/Circus (Europe).png",
  "Named_Snaps/Combat (Europe).png",
  "Named_Snaps/Crazy Climber (Europe).png",
  "Named_Snaps/Crazy Gobbler (Europe).png",
  "Named_Snaps/Escape (USA, Europe).png",
  "Named_Snaps/Funky Fish (Europe).png",
  "Named_Snaps/Golf (Europe).png",
  "Named_Snaps/Grand Slam Tennis (USA, Europe).png",
  "Named_Snaps/Hobo (Europe).png",
  "Named_Snaps/Horse Racing (Europe).png",
  "Named_Snaps/Jump Bug (Europe).png",
  "Named_Snaps/Jungler (USA, Europe).png",
  "Named_Snaps/Missile War (USA, Europe).png",
  "Named_Snaps/Monaco Grand Prix (Europe).png",
  "Named_Snaps/Nibblemen (Europe).png",
  "Named_Snaps/Ocean Battle (USA, Europe).png",
  "Named_Snaps/Parashooter (Europe).png",
  "Named_Snaps/Pleiades (Europe).png",
  "Named_Snaps/R2D Tank (Europe).png",
  "Named_Snaps/Red Clash (USA, Europe).png",
  "Named_Snaps/Robot Killer (Europe).png",
  "Named_Snaps/Route 16 (Europe).png",
  "Named_Snaps/Soccer (USA, Europe).png",
  "Named_Snaps/Space Attack (USA, Europe).png",
  "Named_Snaps/Space Mission (USA, Europe).png",
  "Named_Snaps/Space Raiders (USA, Europe).png",
  "Named_Snaps/Space Squadron (Europe).png",
  "Named_Snaps/Space Vultures (USA, Europe).png",
  "Named_Snaps/Spiders (USA, Europe).png",
  "Named_Snaps/Star Chess (USA, Europe).png",
  "Named_Snaps/Super Gobbler (Europe).png",
  "Named_Snaps/Tanks a Lot (USA, Europe).png",
  "Named_Snaps/The End (Europe).png",
  "Named_Snaps/Turtles (Europe).png",
  "Named_Titles/3D Bowling (USA, Europe).png",
  "Named_Titles/3D Soccer (Europe).png",
  "Named_Titles/Alien Invaders (USA, Europe).png",
  "Named_Titles/American Football (USA, Europe).png",
  "Named_Titles/Astro Invader (Europe).png",
  "Named_Titles/Autorace (Europe).png",
  "Named_Titles/Baseball (USA, Europe).png",
  "Named_Titles/Basketball (Europe).png",
  "Named_Titles/Blackjack and Poker (Europe).png",
  "Named_Titles/Boxing (Europe).png",
  "Named_Titles/Brain Quiz (USA, Europe).png",
  "Named_Titles/Breakaway (USA, Europe).png",
  "Named_Titles/Capture (USA, Europe).png",
  "Named_Titles/Cat Trax (USA, Europe).png",
  "Named_Titles/Circus (Europe).png",
  "Named_Titles/Combat (Europe).png",
  "Named_Titles/Crazy Climber (Europe).png",
  "Named_Titles/Crazy Gobbler (Europe).png",
  "Named_Titles/Escape (USA, Europe).png",
  "Named_Titles/Funky Fish (Europe).png",
  "Named_Titles/Golf (Europe).png",
  "Named_Titles/Grand Slam Tennis (USA, Europe).png",
  "Named_Titles/Hobo (Europe).png",
  "Named_Titles/Horse Racing (Europe).png",
  "Named_Titles/Jump Bug (Europe).png",
  "Named_Titles/Jungler (USA, Europe).png",
  "Named_Titles/Missile War (USA, Europe).png",
  "Named_Titles/Monaco Grand Prix (Europe).png",
  "Named_Titles/Nibblemen (Europe).png",
  "Named_Titles/Ocean Battle (USA, Europe).png",
  "Named_Titles/Parashooter (Europe).png",
  "Named_Titles/Pleiades (Europe).png",
  "Named_Titles/R2D Tank (Europe).png",
  "Named_Titles/Red Clash (USA, Europe).png",
  "Named_Titles/Robot Killer (Europe).png",
  "Named_Titles/Route 16 (Europe).png",
  "Named_Titles/Soccer (USA, Europe).png",
  "Named_Titles/Space Attack (USA, Europe).png",
  "Named_Titles/Space Mission (USA, Europe).png",
  "Named_Titles/Space Raiders (USA, Europe).png",
  "Named_Titles/Space Squadron (Europe).png",
  "Named_Titles/Space Vultures (USA, Europe).png",
  "Named_Titles/Spiders (USA, Europe).png",
  "Named_Titles/Star Chess (USA, Europe).png",
  "Named_Titles/Super Gobbler (Europe).png",
  "Named_Titles/Tanks a Lot (USA, Europe).png",
  "Named_Titles/The End (Europe).png",
  "Named_Titles/Turtles (Europe).png",
}
