return {
  "Named_Snaps/Bobble.png",
  "Named_Snaps/Deep Dungeon.png",
  "Named_Snaps/Game of Life.png",
  "Named_Snaps/In Your Face City Trains.png",
  "Named_Snaps/Onion Kidd.png",
  "Named_Snaps/Platformer.png",
  "Named_Snaps/Pong.png",
  "Named_Snaps/Sienna.png",
  "Named_Snaps/Snake.png",
  "Named_Snaps/Spaceship.png",
  "Named_Snaps/Tactics.png",
  "Named_Snaps/Tetris.png",
  "Named_Snaps/Vespa.png",
  "Named_Titles/Bobble.png",
  "Named_Titles/Deep Dungeon.png",
  "Named_Titles/Game of Life.png",
  "Named_Titles/In Your Face City Trains.png",
  "Named_Titles/Onion Kidd.png",
  "Named_Titles/Platformer.png",
  "Named_Titles/Pong.png",
  "Named_Titles/Sienna.png",
  "Named_Titles/Snake.png",
  "Named_Titles/Spaceship.png",
  "Named_Titles/Tactics.png",
  "Named_Titles/Tetris.png",
  "Named_Titles/Vespa.png",
}
