return {
  "Named_Boxarts/Aa! Megami-sama (Japan) (Disc 1).png",
  "Named_Boxarts/Aa! Megami-sama (Japan) (Disc 2).png",
  "Named_Boxarts/Akazukin ChaCha - Osawagase! Panic Race! (Japan).png",
  "Named_Boxarts/Albaria no Otome (Japan).png",
  "Named_Boxarts/Angelique - Tenkuu no Requiem (Japan).png",
  "Named_Boxarts/Angelique Special (Japan).png",
  "Named_Boxarts/Angelique Special 2 (Japan).png",
  "Named_Boxarts/AnimeFreak FX Vol. 1 (Japan).png",
  "Named_Boxarts/AnimeFreak FX Vol. 2 (Japan).png",
  "Named_Boxarts/AnimeFreak FX Vol. 3 (Japan).png",
  "Named_Boxarts/AnimeFreak FX Vol. 4 (Japan).png",
  "Named_Boxarts/AnimeFreak FX Vol. 5 (Japan) (Disc 1).png",
  "Named_Boxarts/AnimeFreak FX Vol. 5 (Japan) (Disc 2).png",
  "Named_Boxarts/AnimeFreak FX Vol. 6 (Japan) (Disc 1).png",
  "Named_Boxarts/AnimeFreak FX Vol. 6 (Japan) (Disc 2).png",
  "Named_Boxarts/Battle Heat (Japan).png",
  "Named_Boxarts/Blue Breaker - Ken yori mo Hohoemi o (Japan).png",
  "Named_Boxarts/Boundary Gate - Daughter of Kingdom (Japan).png",
  "Named_Boxarts/Can Can Bunny Extra DX (Japan).png",
  "Named_Boxarts/Chip-chan Kick! (Japan).png",
  "Named_Boxarts/Choujin Heiki Zeroigar (Japan).png",
  "Named_Boxarts/Cocktail Pack (Japan).png",
  "Named_Boxarts/Comic Road (Japan).png",
  "Named_Boxarts/Cutey Honey FX (Japan).png",
  "Named_Boxarts/Doukyuusei 2 (Japan).png",
  "Named_Boxarts/Dragon Knight 4 (Japan).png",
  "Named_Boxarts/Farland Story FX (Japan).png",
  "Named_Boxarts/Fire Woman Matoigumi (Japan).png",
  "Named_Boxarts/First Kiss Story (Japan).png",
  "Named_Boxarts/Fushigi no Kuni no Angelique (Japan).png",
  "Named_Boxarts/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan) (Sample).png",
  "Named_Boxarts/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan).png",
  "Named_Boxarts/Hataraku Shoujo - Tekipaki Working Love FX (Japan).png",
  "Named_Boxarts/J. B. Harold - Blue Chicago Blues (Japan) (Disc 1).png",
  "Named_Boxarts/J. B. Harold - Blue Chicago Blues (Japan) (Disc 2).png",
  "Named_Boxarts/Kishin Douji Zenki FX - Vajra Fight (Japan).png",
  "Named_Boxarts/Kokuu Hyouryuu - Nirgends (Japan).png",
  "Named_Boxarts/Konpeki no Kantai (Japan).png",
  "Named_Boxarts/Langrisser FX, Der (Japan).png",
  "Named_Boxarts/Last Imperial Prince (Japan) (Disc A).png",
  "Named_Boxarts/Last Imperial Prince (Japan) (Disc B).png",
  "Named_Boxarts/Lunatic Dawn FX (Japan).png",
  "Named_Boxarts/Mahjong Gokuu Tenjiku (Japan) (SABS).png",
  "Named_Boxarts/Makeruna! Makendou Z (Japan).png",
  "Named_Boxarts/Megami Paradise II (Japan).png",
  "Named_Boxarts/Minimum Nanonic (Japan).png",
  "Named_Boxarts/Miraculum - The Last Revelation (Japan).png",
  "Named_Boxarts/Ojousama Sousamou (Japan).png",
  "Named_Boxarts/PC Engine Fan - Special CD-ROM Vol. 2 (Japan).png",
  "Named_Boxarts/Pachio-kun FX - Maboroshi no Shima Daisakusen (Japan).png",
  "Named_Boxarts/Pia Carrot e Youkoso!! We've Been Waiting for You (Japan).png",
  "Named_Boxarts/Power DoLLS FX (Japan).png",
  "Named_Boxarts/Return to Zork (Japan).png",
  "Named_Boxarts/Ruruli Ra Rura (Japan).png",
  "Named_Boxarts/Shanghai - Banri no Choujou (Japan).png",
  "Named_Boxarts/Sotsugyou II FX - Neo Generation (Japan) (SABS, SACS).png",
  "Named_Boxarts/Sotsugyou R - Graduation Real (Japan).png",
  "Named_Boxarts/Sparkling Feather (Japan).png",
  "Named_Boxarts/Super PC Engine Fan Deluxe - Special CD-ROM Vol. 2 (Japan).png",
  "Named_Boxarts/Super Power League FX (Japan).png",
  "Named_Boxarts/Super Real Mahjong P.V FX (Japan).png",
  "Named_Boxarts/Team Innocent - The Point of No Return - G.C.P.O.SS (Japan).png",
  "Named_Boxarts/Tenchi Muyou! Ryououki FX (Japan) (Disc A) (Hakua Kaikou).png",
  "Named_Boxarts/Tenchi Muyou! Ryououki FX (Japan) (Disc B) (Kiyone Houguu).png",
  "Named_Boxarts/Tengai Makyou - Dennou Karakuri Kakutouden (Japan).png",
  "Named_Boxarts/Tokimeki Card Paradise - Koi no Royal Straight Flush (Japan).png",
  "Named_Boxarts/Tonari no Princess Rolfee! (Japan).png",
  "Named_Boxarts/Voice Paradise (Japan) (Disc A).png",
  "Named_Boxarts/Voice Paradise (Japan) (Disc B).png",
  "Named_Boxarts/Wakusei Koukitai - Little Cats (Japan).png",
  "Named_Boxarts/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc A) (Zenjo vs Zenjo).png",
  "Named_Boxarts/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc B) (Zenjo vs KWP).png",
  "Named_Boxarts/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 1).png",
  "Named_Boxarts/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 2).png",
  "Named_Logos/Aa! Megami-sama (Japan) (Disc 1).png",
  "Named_Logos/Aa! Megami-sama (Japan) (Disc 2).png",
  "Named_Logos/Akazukin ChaCha - Osawagase! Panic Race! (Japan).png",
  "Named_Logos/Albaria no Otome (Japan).png",
  "Named_Logos/Angelique - Tenkuu no Requiem (Japan).png",
  "Named_Logos/Angelique Special (Japan).png",
  "Named_Logos/Angelique Special 2 (Japan).png",
  "Named_Logos/Battle Heat (Japan).png",
  "Named_Logos/Blue Breaker - Ken yori mo Hohoemi o (Japan).png",
  "Named_Logos/Boundary Gate - Daughter of Kingdom (Japan).png",
  "Named_Logos/Can Can Bunny Extra DX (Japan).png",
  "Named_Logos/Chip-chan Kick! (Japan).png",
  "Named_Logos/Choujin Heiki Zeroigar (Japan).png",
  "Named_Logos/Comic Road (Japan).png",
  "Named_Logos/Cutey Honey FX (Japan).png",
  "Named_Logos/Doukyuusei 2 (Japan).png",
  "Named_Logos/Dragon Knight 4 (Japan).png",
  "Named_Logos/Farland Story FX (Japan).png",
  "Named_Logos/Fire Woman Matoigumi (Japan).png",
  "Named_Logos/First Kiss Story (Japan).png",
  "Named_Logos/Fushigi no Kuni no Angelique (Japan).png",
  "Named_Logos/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan).png",
  "Named_Logos/Hataraku Shoujo - Tekipaki Working Love FX (Japan).png",
  "Named_Logos/J. B. Harold - Blue Chicago Blues (Japan) (Disc 1).png",
  "Named_Logos/J. B. Harold - Blue Chicago Blues (Japan) (Disc 2).png",
  "Named_Logos/Kishin Douji Zenki FX - Vajra Fight (Japan).png",
  "Named_Logos/Kokuu Hyouryuu - Nirgends (Japan).png",
  "Named_Logos/Konpeki no Kantai (Japan).png",
  "Named_Logos/Langrisser FX, Der (Japan).png",
  "Named_Logos/Last Imperial Prince (Japan) (Disc A).png",
  "Named_Logos/Last Imperial Prince (Japan) (Disc B).png",
  "Named_Logos/Lunatic Dawn FX (Japan).png",
  "Named_Logos/Mahjong Gokuu Tenjiku (Japan) (SABS).png",
  "Named_Logos/Makeruna! Makendou Z (Japan).png",
  "Named_Logos/Megami Paradise II (Japan).png",
  "Named_Logos/Minimum Nanonic (Japan).png",
  "Named_Logos/Miraculum - The Last Revelation (Japan).png",
  "Named_Logos/Ojousama Sousamou (Japan).png",
  "Named_Logos/Pachio-kun FX - Maboroshi no Shima Daisakusen (Japan).png",
  "Named_Logos/Power DoLLS FX (Japan).png",
  "Named_Logos/Return to Zork (Japan).png",
  "Named_Logos/Ruruli Ra Rura (Japan).png",
  "Named_Logos/Shanghai - Banri no Choujou (Japan).png",
  "Named_Logos/Sotsugyou II FX - Neo Generation (Japan) (SABS, SACS).png",
  "Named_Logos/Sotsugyou R - Graduation Real (Japan).png",
  "Named_Logos/Sparkling Feather (Japan).png",
  "Named_Logos/Super Power League FX (Japan).png",
  "Named_Logos/Super Real Mahjong P.V FX (Japan).png",
  "Named_Logos/Team Innocent - The Point of No Return - G.C.P.O.SS (Japan).png",
  "Named_Logos/Tenchi Muyou! Ryououki FX (Japan) (Disc A) (Hakua Kaikou).png",
  "Named_Logos/Tenchi Muyou! Ryououki FX (Japan) (Disc B) (Kiyone Houguu).png",
  "Named_Logos/Tengai Makyou - Dennou Karakuri Kakutouden (Japan).png",
  "Named_Logos/Tokimeki Card Paradise - Koi no Royal Straight Flush (Japan).png",
  "Named_Logos/Tonari no Princess Rolfee! (Japan).png",
  "Named_Logos/Voice Paradise (Japan) (Disc A).png",
  "Named_Logos/Voice Paradise (Japan) (Disc B).png",
  "Named_Logos/Wakusei Koukitai - Little Cats (Japan).png",
  "Named_Logos/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc A) (Zenjo vs Zenjo).png",
  "Named_Logos/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc B) (Zenjo vs KWP).png",
  "Named_Logos/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 1).png",
  "Named_Logos/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 2).png",
  "Named_Snaps/Aa! Megami-sama (Japan) (Disc 1).png",
  "Named_Snaps/Aa! Megami-sama (Japan) (Disc 2).png",
  "Named_Snaps/Akazukin ChaCha - Osawagase! Panic Race! (Japan).png",
  "Named_Snaps/Albaria no Otome (Japan).png",
  "Named_Snaps/Amateur Teikyou CD-ROM (Japan) (DOS-V-you) (NEC PC-FXGA).png",
  "Named_Snaps/Amateur Teikyou CD-ROM (Japan) (NEC PC-FXGA).png",
  "Named_Snaps/Angelique - Tenkuu no Requiem (Japan).png",
  "Named_Snaps/Angelique Special (Japan).png",
  "Named_Snaps/Angelique Special 2 (Japan).png",
  "Named_Snaps/AnimeFreak FX Vol. 1 (Japan).png",
  "Named_Snaps/AnimeFreak FX Vol. 2 (Japan).png",
  "Named_Snaps/AnimeFreak FX Vol. 3 (Japan).png",
  "Named_Snaps/AnimeFreak FX Vol. 4 (Japan).png",
  "Named_Snaps/AnimeFreak FX Vol. 5 (Japan) (Disc 1).png",
  "Named_Snaps/AnimeFreak FX Vol. 5 (Japan) (Disc 2).png",
  "Named_Snaps/AnimeFreak FX Vol. 6 (Japan) (Disc 1).png",
  "Named_Snaps/AnimeFreak FX Vol. 6 (Japan) (Disc 2).png",
  "Named_Snaps/Battle Heat (Japan).png",
  "Named_Snaps/Blue Breaker - Ken yori mo Hohoemi o (Japan).png",
  "Named_Snaps/Boundary Gate - Daughter of Kingdom (Japan).png",
  "Named_Snaps/Can Can Bunny Extra DX (Japan).png",
  "Named_Snaps/Chip-chan Kick! (Japan).png",
  "Named_Snaps/Choujin Heiki Zeroigar (Japan).png",
  "Named_Snaps/Comic Road (Japan).png",
  "Named_Snaps/Cutey Honey FX (Japan).png",
  "Named_Snaps/Doukyuusei 2 (Japan).png",
  "Named_Snaps/Dragon Knight 4 (Japan).png",
  "Named_Snaps/Farland Story FX (Japan) [T-En by Djlpap R2].png",
  "Named_Snaps/Farland Story FX (Japan).png",
  "Named_Snaps/Fire Woman Matoigumi (Japan).png",
  "Named_Snaps/First Kiss Story (Japan).png",
  "Named_Snaps/Fushigi no Kuni no Angelique (Japan).png",
  "Named_Snaps/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan) (Sample).png",
  "Named_Snaps/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan).png",
  "Named_Snaps/God-Fighter Zeroigar (Japan) [T-En by SamIAm _ Elmer _ Esteban v1.0.1] [n].png",
  "Named_Snaps/Hataraku Shoujo - Tekipaki Working Love FX (Japan).png",
  "Named_Snaps/J. B. Harold - Blue Chicago Blues (Japan) (Disc 1).png",
  "Named_Snaps/J. B. Harold - Blue Chicago Blues (Japan) (Disc 2).png",
  "Named_Snaps/Kishin Douji Zenki FX - Vajra Fight (Japan).png",
  "Named_Snaps/Kokuu Hyouryuu - Nirgends (Japan).png",
  "Named_Snaps/Konpeki no Kantai (Japan).png",
  "Named_Snaps/Langrisser FX, Der (Japan).png",
  "Named_Snaps/Last Imperial Prince (Japan) (Disc A).png",
  "Named_Snaps/Last Imperial Prince (Japan) (Disc B).png",
  "Named_Snaps/Lunatic Dawn FX (Japan).png",
  "Named_Snaps/Mahjong Gokuu Tenjiku (Japan) (SABS).png",
  "Named_Snaps/Makeruna! Makendou Z (Japan).png",
  "Named_Snaps/Megami Paradise II (Japan).png",
  "Named_Snaps/Minimum Nanonic (Japan).png",
  "Named_Snaps/Miraculum - The Last Revelation (Japan).png",
  "Named_Snaps/Ojousama Sousamou (Japan).png",
  "Named_Snaps/PC Engine Fan - Special CD-ROM Vol. 2 (Japan).png",
  "Named_Snaps/PC Engine Fan - Special CD-ROM Vol. 3 (Japan).png",
  "Named_Snaps/Pachio-kun FX - Maboroshi no Shima Daisakusen (Japan).png",
  "Named_Snaps/Pia Carrot e Youkoso!! We've Been Waiting for You (Japan).png",
  "Named_Snaps/Power DoLLS FX (Japan).png",
  "Named_Snaps/Return to Zork (Japan).png",
  "Named_Snaps/Ruruli Ra Rura (Japan) [T-En by Nekozomb v1-Infinity] [i].png",
  "Named_Snaps/Ruruli Ra Rura (Japan).png",
  "Named_Snaps/Same Game FX (Japan) (NEC PC-FXGA).png",
  "Named_Snaps/Shanghai - Banri no Choujou (Japan).png",
  "Named_Snaps/Sotsugyou II FX - Neo Generation (Japan) (SABS, SACS).png",
  "Named_Snaps/Sotsugyou R - Graduation Real (Japan).png",
  "Named_Snaps/Sparkling Feather (Japan).png",
  "Named_Snaps/Super PC Engine Fan Deluxe - Special CD-ROM Vol. 1 (Japan).png",
  "Named_Snaps/Super PC Engine Fan Deluxe - Special CD-ROM Vol. 2 (Japan).png",
  "Named_Snaps/Super Power League FX (Japan).png",
  "Named_Snaps/Super Real Mahjong P.V FX (Japan).png",
  "Named_Snaps/Team Innocent - The Point of No Return - G.C.P.O.SS (Japan) (SABS).png",
  "Named_Snaps/Team Innocent - The Point of No Return - G.C.P.O.SS (Japan).png",
  "Named_Snaps/Tenchi Muyou! Ryououki FX (Japan) (Disc A) (Hakua Kaikou).png",
  "Named_Snaps/Tenchi Muyou! Ryououki FX (Japan) (Disc B) (Kiyone Houguu).png",
  "Named_Snaps/Tengai Makyou - Dennou Karakuri Kakutouden (Japan).png",
  "Named_Snaps/Tokimeki Card Paradise - Koi no Royal Straight Flush (Japan).png",
  "Named_Snaps/Tonari no Princess Rolfee! (Japan).png",
  "Named_Snaps/Voice Paradise (Japan) (Disc A).png",
  "Named_Snaps/Voice Paradise (Japan) (Disc B).png",
  "Named_Snaps/Wakusei Koukitai - Little Cats (Japan).png",
  "Named_Snaps/Welcome to Pia Carrot!! We've Been Waiting for You (Japan) [T-En by David Michel _ Filler] [Add by BabaJeanmel v1.0] [n].png",
  "Named_Snaps/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc A) (Zenjo vs Zenjo).png",
  "Named_Snaps/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc B) (Zenjo vs KWP).png",
  "Named_Snaps/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 1).png",
  "Named_Snaps/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 2).png",
  "Named_Snaps/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc I).png",
  "Named_Snaps/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc II).png",
  "Named_Titles/Aa! Megami-sama (Japan) (Disc 1).png",
  "Named_Titles/Aa! Megami-sama (Japan) (Disc 2).png",
  "Named_Titles/Akazukin ChaCha - Osawagase! Panic Race! (Japan).png",
  "Named_Titles/Albaria no Otome (Japan).png",
  "Named_Titles/Amateur Teikyou CD-ROM (Japan) (DOS-V-you) (NEC PC-FXGA).png",
  "Named_Titles/Amateur Teikyou CD-ROM (Japan) (NEC PC-FXGA).png",
  "Named_Titles/Angelique - Tenkuu no Requiem (Japan).png",
  "Named_Titles/Angelique Special (Japan).png",
  "Named_Titles/Angelique Special 2 (Japan).png",
  "Named_Titles/AnimeFreak FX Vol. 1 (Japan).png",
  "Named_Titles/AnimeFreak FX Vol. 2 (Japan).png",
  "Named_Titles/AnimeFreak FX Vol. 3 (Japan).png",
  "Named_Titles/AnimeFreak FX Vol. 4 (Japan).png",
  "Named_Titles/AnimeFreak FX Vol. 5 (Japan) (Disc 1).png",
  "Named_Titles/AnimeFreak FX Vol. 5 (Japan) (Disc 2).png",
  "Named_Titles/AnimeFreak FX Vol. 6 (Japan) (Disc 1).png",
  "Named_Titles/AnimeFreak FX Vol. 6 (Japan) (Disc 2).png",
  "Named_Titles/Battle Heat (Japan).png",
  "Named_Titles/Blue Breaker - Ken yori mo Hohoemi o (Japan).png",
  "Named_Titles/Boundary Gate - Daughter of Kingdom (Japan).png",
  "Named_Titles/Can Can Bunny Extra DX (Japan).png",
  "Named_Titles/Chip-chan Kick! (Japan).png",
  "Named_Titles/Choujin Heiki Zeroigar (Japan).png",
  "Named_Titles/Comic Road (Japan).png",
  "Named_Titles/Cutey Honey FX (Japan).png",
  "Named_Titles/Doukyuusei 2 (Japan).png",
  "Named_Titles/Dragon Knight 4 (Japan).png",
  "Named_Titles/Farland Story FX (Japan) [T-En by Djlpap R2].png",
  "Named_Titles/Farland Story FX (Japan).png",
  "Named_Titles/Fire Woman Matoigumi (Japan).png",
  "Named_Titles/First Kiss Story (Japan).png",
  "Named_Titles/Fushigi no Kuni no Angelique (Japan).png",
  "Named_Titles/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan) (Sample).png",
  "Named_Titles/Ginga Ojousama Densetsu Yuna FX - Kanashimi no Selene (Japan).png",
  "Named_Titles/God-Fighter Zeroigar (Japan) [T-En by SamIAm _ Elmer _ Esteban v1.0.1] [n].png",
  "Named_Titles/Hataraku Shoujo - Tekipaki Working Love FX (Japan).png",
  "Named_Titles/J. B. Harold - Blue Chicago Blues (Japan) (Disc 1).png",
  "Named_Titles/J. B. Harold - Blue Chicago Blues (Japan) (Disc 2).png",
  "Named_Titles/Kishin Douji Zenki FX - Vajra Fight (Japan).png",
  "Named_Titles/Kokuu Hyouryuu - Nirgends (Japan).png",
  "Named_Titles/Konpeki no Kantai (Japan).png",
  "Named_Titles/Langrisser FX, Der (Japan).png",
  "Named_Titles/Last Imperial Prince (Japan) (Disc A).png",
  "Named_Titles/Last Imperial Prince (Japan) (Disc B).png",
  "Named_Titles/Lunatic Dawn FX (Japan).png",
  "Named_Titles/Mahjong Gokuu Tenjiku (Japan) (SABS).png",
  "Named_Titles/Makeruna! Makendou Z (Japan).png",
  "Named_Titles/Megami Paradise II (Japan).png",
  "Named_Titles/Minimum Nanonic (Japan).png",
  "Named_Titles/Miraculum - The Last Revelation (Japan).png",
  "Named_Titles/Ojousama Sousamou (Japan).png",
  "Named_Titles/PC Engine Fan - Special CD-ROM Vol. 2 (Japan).png",
  "Named_Titles/PC Engine Fan - Special CD-ROM Vol. 3 (Japan).png",
  "Named_Titles/Pachio-kun FX - Maboroshi no Shima Daisakusen (Japan).png",
  "Named_Titles/Pia Carrot e Youkoso!! We've Been Waiting for You (Japan).png",
  "Named_Titles/Power DoLLS FX (Japan).png",
  "Named_Titles/Return to Zork (Japan).png",
  "Named_Titles/Ruruli Ra Rura (Japan) [T-En by Nekozomb v1-Infinity] [i].png",
  "Named_Titles/Ruruli Ra Rura (Japan).png",
  "Named_Titles/Same Game FX (Japan) (NEC PC-FXGA).png",
  "Named_Titles/Shanghai - Banri no Choujou (Japan).png",
  "Named_Titles/Sotsugyou II FX - Neo Generation (Japan) (SABS, SACS).png",
  "Named_Titles/Sotsugyou R - Graduation Real (Japan).png",
  "Named_Titles/Sparkling Feather (Japan).png",
  "Named_Titles/Super PC Engine Fan Deluxe - Special CD-ROM Vol. 1 (Japan).png",
  "Named_Titles/Super PC Engine Fan Deluxe - Special CD-ROM Vol. 2 (Japan).png",
  "Named_Titles/Super Power League FX (Japan).png",
  "Named_Titles/Super Real Mahjong P.V FX (Japan).png",
  "Named_Titles/Team Innocent - The Point of No Return - G.C.P.O.SS (Japan) (SABS).png",
  "Named_Titles/Team Innocent - The Point of No Return - G.C.P.O.SS (Japan).png",
  "Named_Titles/Tenchi Muyou! Ryououki FX (Japan) (Disc A) (Hakua Kaikou).png",
  "Named_Titles/Tenchi Muyou! Ryououki FX (Japan) (Disc B) (Kiyone Houguu).png",
  "Named_Titles/Tengai Makyou - Dennou Karakuri Kakutouden (Japan).png",
  "Named_Titles/Tokimeki Card Paradise - Koi no Royal Straight Flush (Japan).png",
  "Named_Titles/Tonari no Princess Rolfee! (Japan).png",
  "Named_Titles/Voice Paradise (Japan) (Disc A).png",
  "Named_Titles/Voice Paradise (Japan) (Disc B).png",
  "Named_Titles/Wakusei Koukitai - Little Cats (Japan).png",
  "Named_Titles/Welcome to Pia Carrot!! We've Been Waiting for You (Japan) [T-En by David Michel _ Filler] [Add by BabaJeanmel v1.0] [n].png",
  "Named_Titles/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc A) (Zenjo vs Zenjo).png",
  "Named_Titles/Zen Nihon Joshi Pro Wres - Queen of Queens (Japan) (Disc B) (Zenjo vs KWP).png",
  "Named_Titles/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 1).png",
  "Named_Titles/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc 2).png",
  "Named_Titles/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc I).png",
  "Named_Titles/Zoku Hatsukoi Monogatari - Shuugaku Ryokou (Japan) (Disc II).png",
}
