return {
  "Named_Boxarts/007 Legends (Europe) (En,Fr,De).png",
  "Named_Boxarts/007 Legends (USA) (En,Fr).png",
  "Named_Boxarts/ABC Wipeout - Create &amp; Crash (USA).png",
  "Named_Boxarts/ABC Wipeout 3 (USA).png",
  "Named_Boxarts/Adventure Time - Explore the Dungeon Because I Don't Know! (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Adventure Time - Explore the Dungeon Because I Don't Know! (USA) (En,Fr,Es).png",
  "Named_Boxarts/Adventure Time - Finn &amp; Jake Investigations (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Adventure Time - Finn &amp; Jake Investigations (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Angry Birds Star Wars (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Angry Birds Star Wars (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Angry Birds Trilogy (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Angry Birds Trilogy (USA) (En,Fr).png",
  "Named_Boxarts/Animal Crossing - Amiibo Festival (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Animal Crossing - Amiibo Festival (USA) (En,Fr,Es).png",
  "Named_Boxarts/Assassin's Creed III (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Boxarts/Assassin's Creed III (Japan).png",
  "Named_Boxarts/Assassin's Creed III (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Assassin's Creed IV - Black Flag (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Boxarts/Assassin's Creed IV - Black Flag (Japan).png",
  "Named_Boxarts/Assassin's Creed IV - Black Flag (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Axiom Verge (USA) (En,Fr,De,Es,It,Pt).png",
  "Named_Boxarts/Baila Latino (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Barbie &amp; Her Sisters - Puppy Rescue (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Barbie &amp; Her Sisters - Puppy Rescue (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Barbie Dreamhouse Party (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Boxarts/Barbie Dreamhouse Party (USA) (En,Fr,Es).png",
  "Named_Boxarts/Batman - Arkham City - Armored Edition (Japan).png",
  "Named_Boxarts/Batman - Arkham City - Armored Edition (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Batman - Arkham City - Armoured Edition (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Boxarts/Batman - Arkham Origins (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Boxarts/Batman - Arkham Origins (Japan).png",
  "Named_Boxarts/Batman - Arkham Origins (USA) (En,Fr,Es).png",
  "Named_Boxarts/Bayonetta (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Bayonetta (Japan) (Rev 1).png",
  "Named_Boxarts/Bayonetta (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Bayonetta 2 (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Bayonetta 2 (Japan).png",
  "Named_Boxarts/Bayonetta 2 (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Bayonetta 2 (USA).png",
  "Named_Boxarts/Ben 10 - Omniverse (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Boxarts/Ben 10 - Omniverse (USA) (En,Fr,Es).png",
  "Named_Boxarts/Ben 10 - Omniverse 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Ben 10 - Omniverse 2 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Biohazard - Revelations - Unveiled Edition (Japan) (Rev 1).png",
  "Named_Boxarts/Book of Unwritten Tales 2, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Book of Unwritten Tales 2, The (USA) (En,Fr,De,Es,It,Pl).png",
  "Named_Boxarts/Brunswick Pro Bowling (USA).png",
  "Named_Boxarts/Cabela's Big Game Hunter - Pro Hunts (USA).png",
  "Named_Boxarts/Cabela's Dangerous Hunts 2013 (Europe) (En,Fr,De,It).png",
  "Named_Boxarts/Cabela's Dangerous Hunts 2013 (USA) (En,Fr).png",
  "Named_Boxarts/Call of Duty - Black Ops II (Europe) (En,Fr).png",
  "Named_Boxarts/Call of Duty - Black Ops II (Europe) (Es,It).png",
  "Named_Boxarts/Call of Duty - Black Ops II (Germany).png",
  "Named_Boxarts/Call of Duty - Black Ops II (Japan) (En,Ja).png",
  "Named_Boxarts/Call of Duty - Black Ops II (USA) (En,Fr).png",
  "Named_Boxarts/Call of Duty - Ghosts (Europe) (En,Fr,De).png",
  "Named_Boxarts/Call of Duty - Ghosts (Europe) (Es,It).png",
  "Named_Boxarts/Call of Duty - Ghosts (Japan).png",
  "Named_Boxarts/Call of Duty - Ghosts (USA) (En,Fr).png",
  "Named_Boxarts/Captain Toad - Treasure Tracker (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Boxarts/Captain Toad - Treasure Tracker (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Captain Toad - Treasure Tracker (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Captain Toad - Treasure Tracker (USA) (En,Fr,Es).png",
  "Named_Boxarts/Captain Toad_ Treasure Tracker (Europe).png",
  "Named_Boxarts/Captain Toad_ Treasure Tracker (USA).png",
  "Named_Boxarts/Cocoto Magic Circus 2 (Europe) (En,Fr,De,Es,It,Nl,Pt).png",
  "Named_Boxarts/Dairantou Smash Brothers for Wii U (Japan).png",
  "Named_Boxarts/Darksiders - Warmastered Edition (Europe) (En,Fr,De,Es,It,Pt,Zh,Pl,Ru,Cs).png",
  "Named_Boxarts/Darksiders - Warmastered Edition (USA) (En,Ja,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru,Cs).png",
  "Named_Boxarts/Darksiders II (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Darksiders II (USA) (En,Fr,Es).png",
  "Named_Boxarts/Deus Ex - Human Revolution - Director's Cut (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Deus Ex - Human Revolution - Director's Cut (USA) (En,Fr,Es).png",
  "Named_Boxarts/Devil's Third (Europe) (En,Fr).png",
  "Named_Boxarts/Devil's Third (Japan).png",
  "Named_Boxarts/Devil's Third (USA) (En,Fr).png",
  "Named_Boxarts/Disney DuckTales - Remastered (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Disney Epic Mickey 2 - Futatsu no Chikara (Japan).png",
  "Named_Boxarts/Disney Epic Mickey 2 - The Power of Two (Europe) (En,Es).png",
  "Named_Boxarts/Disney Epic Mickey 2 - The Power of Two (Europe) (En,Fr,De,Es,It,Pt).png",
  "Named_Boxarts/Disney Epic Mickey 2 - The Power of Two (Scandinavia) (En,Sv,No,Da).png",
  "Named_Boxarts/Disney Epic Mickey 2 - The Power of Two (USA) (En,Fr,Es).png",
  "Named_Boxarts/Disney Infinity (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Disney Infinity (Japan).png",
  "Named_Boxarts/Disney Infinity (Scandinavia) (En,Sv,No,Da,Fi).png",
  "Named_Boxarts/Disney Infinity (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Disney Infinity 2.0 - Play Without Limits (Europe) (En,Fr,De,Es,It,Nl) (Rev 1).png",
  "Named_Boxarts/Disney Infinity 2.0 - Play Without Limits (Scandinavia) (En,Sv,No,Da,Fi) (Rev 2).png",
  "Named_Boxarts/Disney Infinity 2.0 Edition (USA) (En,Fr,Es,Pt) (Rev 1).png",
  "Named_Boxarts/Disney Infinity 2.0 Edition (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Disney Infinity 3.0 (Japan).png",
  "Named_Boxarts/Disney Infinity 3.0 - Play Without Limits (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Disney Infinity 3.0 - Play Without Limits (Scandinavia) (En,Sv,No,Da,Fi).png",
  "Named_Boxarts/Disney Infinity 3.0 Edition (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/Disney Infinity 3.0 Edition (USA) (En,Fr,Es).png",
  "Named_Boxarts/Disney Phineas and Ferb - Quest for Cool Stuff (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Disney Phineas and Ferb - Quest for Cool Stuff (USA).png",
  "Named_Boxarts/Disney Planes (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Disney Planes (Russia).png",
  "Named_Boxarts/Disney Planes (Scandinavia) (En,Sv,No,Da,Fi).png",
  "Named_Boxarts/Disney Planes (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Disney Planes - Fire &amp; Rescue (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Disney Planes - Fire &amp; Rescue (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Disney-Pixar Cars 3 - Driven to Win (Europe) (En,Fr,De,Es,It,Nl,Pl,Ru).png",
  "Named_Boxarts/Disney-Pixar Cars 3 - Driven to Win (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Donkey Kong - Tropical Freeze (Japan) (Rev 3).png",
  "Named_Boxarts/Donkey Kong Country - Tropical Freeze (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Boxarts/Donkey Kong Country - Tropical Freeze (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Donkey Kong Country - Tropical Freeze (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Donkey Kong Country - Tropical Freeze (USA) (En,Fr,Es).png",
  "Named_Boxarts/Doubutsu no Mori - Amiibo Festival (Japan).png",
  "Named_Boxarts/Dragon Quest X - 5000-nen no Tabiji - Haruka naru Kokyou e Online (Japan).png",
  "Named_Boxarts/Dragon Quest X - All in One Package (Japan) (BTPJ).png",
  "Named_Boxarts/Dragon Quest X - Inishie no Ryuu no Denshou Online (Japan).png",
  "Named_Boxarts/Dragon Quest X - Mezameshi Itsutsu no Shuzoku Online (Japan) (Rev 1).png",
  "Named_Boxarts/Dragon Quest X - Nemureru Yuusha to Michibiki no Meiyuu Online (Japan) (Rev 10).png",
  "Named_Boxarts/DreamWorks How to Train Your Dragon 2 (Europe) (En,Fr,De,Es,It,Pt).png",
  "Named_Boxarts/DreamWorks How to Train Your Dragon 2 (USA).png",
  "Named_Boxarts/DreamWorks Kung Fu Panda - Showdown of Legendary Legends (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/DreamWorks Kung Fu Panda - Showdown of Legendary Legends (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/DreamWorks Penguins of Madagascar (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/DreamWorks Penguins of Madagascar (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/DreamWorks Rise of the Guardians (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/DreamWorks Rise of the Guardians (USA) (En,Fr,Es).png",
  "Named_Boxarts/DreamWorks The Croods - Prehistoric Party! (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/DreamWorks The Croods - Prehistoric Party! (USA) (En,Fr,Es).png",
  "Named_Boxarts/DreamWorks Turbo - Super Stunt Squad (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/DreamWorks Turbo - Super Stunt Squad (USA) (En,Fr,Es).png",
  "Named_Boxarts/ESPN Sports Connection (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/F1 Race Stars - Powered Up Edition (Japan) (Rev 1).png",
  "Named_Boxarts/FIFA 13 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/FIFA 13 - World Class Soccer (Japan).png",
  "Named_Boxarts/FIFA Soccer 13 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Famicom Remix 1 + 2 (Japan).png",
  "Named_Boxarts/Family Party - 30 Great Games - Obstacle Arcade (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Family Party - 30 Great Games - Obstacle Arcade (USA) (En,Fr,Es).png",
  "Named_Boxarts/Fast &amp; Furious - Showdown (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Fast &amp; Furious - Showdown (USA) (En,Fr).png",
  "Named_Boxarts/Fast Racing Neo (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Finding Teddy II - Definitive Edition (Europe) (En,Fr,De,Es,It,Pt,Ru).png",
  "Named_Boxarts/Fit Music for Wii U (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Fujiko F. Fujio Characters Daishuugou! SF Dotabata Party!! (Japan).png",
  "Named_Boxarts/Funky Barn (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Funky Barn (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Game &amp; Wario (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Game &amp; Wario (Japan) (Rev 1).png",
  "Named_Boxarts/Game &amp; Wario (USA) (En,Fr,Es).png",
  "Named_Boxarts/Game Party Champions (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Game Party Champions (USA) (En,Fr,Es).png",
  "Named_Boxarts/Gen'ei Ibunroku FE (Japan).png",
  "Named_Boxarts/Giana Sisters - Twisted Dreams - Director's Cut (USA) (En,Fr,Es).png",
  "Named_Boxarts/Ginsei Shougi - Kyoutendo Toufuu Raijin (Japan).png",
  "Named_Boxarts/Gotouchi Tetsudou - Gotouchi Chara to Nippon Zenkoku no Tabi (Japan).png",
  "Named_Boxarts/Guitar Hero Live (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Guitar Hero Live (USA) (En,Fr,Es).png",
  "Named_Boxarts/Hello Kitty Kruisers (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Hello Kitty Kruisers (USA).png",
  "Named_Boxarts/Hot Wheels - World's Best Driver (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Hot Wheels - World's Best Driver (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Hunter's Trophy 2 - Europa (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Hyrule Warriors (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Boxarts/Hyrule Warriors (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Hyrule Warriors (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Hyrule Warriors (USA) (En,Fr,Es).png",
  "Named_Boxarts/Injustice - Gods Among Us (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Boxarts/Injustice - Gods Among Us (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Injustice - Hero no Gekitotsu (Japan).png",
  "Named_Boxarts/Jeopardy! (USA).png",
  "Named_Boxarts/Jett Tailfin (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Jikkuri Egokoro Kyoushitsu (Japan) (Rev 1).png",
  "Named_Boxarts/Just Dance - Disney Party 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Just Dance - Disney Party 2 (USA) (En,Fr,De,Es,It,Pt).png",
  "Named_Boxarts/Just Dance 2014 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 2014 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance 2015 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 2015 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance 2016 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 2016 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance 2017 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 2017 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance 2018 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 2018 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance 2019 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 2019 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance 4 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Just Dance 4 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Just Dance Kids 2014 (Europe) (En,Fr,Es).png",
  "Named_Boxarts/Just Dance Kids 2014 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Just Dance Wii U (Japan) (Rev 1).png",
  "Named_Boxarts/Kamen Rider - Battride War II (Japan).png",
  "Named_Boxarts/Kamen Rider - Battride War II - Premium TV &amp; Movie Sound Edition (Japan).png",
  "Named_Boxarts/Kamen Rider Summonride! (Japan).png",
  "Named_Boxarts/Kirby and the Rainbow Curse (USA) (En,Fr,Es).png",
  "Named_Boxarts/Kirby and the Rainbow Paintbrush (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/LEGO Batman 2 - DC Super Heroes (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/LEGO Batman 2 - DC Super Heroes (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO Batman 3 - Beyond Gotham (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO Batman 3 - Beyond Gotham (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO Batman 3 - The Game - Gotham kara Uchuu e (Japan).png",
  "Named_Boxarts/LEGO City Undercover (Europe) (En,Fr,De,Es,It,Nl,Pt,Da,Ru) (Rev 1).png",
  "Named_Boxarts/LEGO City Undercover (Europe) (En,Fr,De,Es,It,Nl,Pt,Da,Ru).png",
  "Named_Boxarts/LEGO City Undercover (Japan).png",
  "Named_Boxarts/LEGO City Undercover (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/LEGO City Undercover (USA) (En,Fr,Es).png",
  "Named_Boxarts/LEGO Dimensions (Europe) (En,Fr,De,Nl,Da) (Rev 1).png",
  "Named_Boxarts/LEGO Dimensions (USA) (En,Fr,Es).png",
  "Named_Boxarts/LEGO Jurassic World (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO Jurassic World (Japan).png",
  "Named_Boxarts/LEGO Jurassic World (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO Marvel Avengers (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO Marvel Avengers (Japan).png",
  "Named_Boxarts/LEGO Marvel Avengers (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO Marvel Super Heroes (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO Marvel Super Heroes (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO Marvel Super Heroes - The Game (Japan).png",
  "Named_Boxarts/LEGO Movie - The Game (Japan).png",
  "Named_Boxarts/LEGO Movie, The - Videogame (Europe) (En,Fr,Es,It,Nl,Da) (Rev 1).png",
  "Named_Boxarts/LEGO Movie, The - Videogame (Europe) (En,Fr,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO Movie, The - Videogame (USA) (En,Fr,Es,Pt) (Rev 1).png",
  "Named_Boxarts/LEGO Movie, The - Videogame (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO Star Wars - Force no Kakusei (Japan).png",
  "Named_Boxarts/LEGO Star Wars - The Force Awakens (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO Star Wars - The Force Awakens (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/LEGO The Hobbit (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Boxarts/LEGO The Hobbit (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Legend of Kay - Anniversary (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Legend of Kay - Anniversary (USA) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Legend of Zelda, The - Breath of the Wild (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Boxarts/Legend of Zelda, The - Breath of the Wild (USA) (En,Fr,Es).png",
  "Named_Boxarts/Legend of Zelda, The - The Wind Waker HD (Europe, Australia) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Legend of Zelda, The - The Wind Waker HD (USA, Asia) (En,Fr,Es).png",
  "Named_Boxarts/Legend of Zelda, The - Twilight Princess HD (Europe, Australia) (En,Fr,De,Es,It) (Rev 2).png",
  "Named_Boxarts/Legend of Zelda, The - Twilight Princess HD (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/Luv Me Buddies - Wonderland (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Madden NFL 13 (USA).png",
  "Named_Boxarts/Mario &amp; Sonic at Rio Olympic (Japan) (Rev 1).png",
  "Named_Boxarts/Mario &amp; Sonic at the Rio 2016 Olympic Games (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Mario &amp; Sonic at the Rio 2016 Olympic Games (USA) (En,Fr,Es).png",
  "Named_Boxarts/Mario &amp; Sonic at the Sochi 2014 Olympic Winter Games (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Boxarts/Mario &amp; Sonic at the Sochi 2014 Olympic Winter Games (USA) (En,Fr,Es).png",
  "Named_Boxarts/Mario &amp; Sonic at the Sochi Olympic (Japan) (Rev 1).png",
  "Named_Boxarts/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Boxarts/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 3).png",
  "Named_Boxarts/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 4).png",
  "Named_Boxarts/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Mario Kart 8 (Japan) (Rev 3).png",
  "Named_Boxarts/Mario Kart 8 (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/Mario Kart 8 (USA) (En,Fr,Es) (Rev 5).png",
  "Named_Boxarts/Mario Kart 8 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Mario Kart 8 (USA).png",
  "Named_Boxarts/Mario Party 10 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Mario Party 10 (Japan).png",
  "Named_Boxarts/Mario Party 10 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Mario Tennis - Ultra Smash (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Mario Tennis - Ultra Smash (Japan) (Rev 1).png",
  "Named_Boxarts/Mario Tennis - Ultra Smash (USA) (En,Fr,Es).png",
  "Named_Boxarts/Marvel Avengers - Battle for Earth (Europe) (En,Fr,De,Es,It,Nl,Pl).png",
  "Named_Boxarts/Marvel Avengers - Battle for Earth (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Mass Effect 3 - Special Edition (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Mass Effect 3 - Special Edition (USA) (En,Fr,Es).png",
  "Named_Boxarts/Mass Effect 3 - Tokubetsu-ban (Japan).png",
  "Named_Boxarts/Mighty No. 9 (Europe) (En,Ja,Fr,De,Es,It,Pt,Ru).png",
  "Named_Boxarts/Mighty No. 9 (USA) (En,Ja,Fr,De,Es,It,Pt,Ru).png",
  "Named_Boxarts/Minecraft - Wii U Edition (Europe) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Ru) (Rev 1).png",
  "Named_Boxarts/Minecraft - Wii U Edition (Japan) (Rev 1).png",
  "Named_Boxarts/Minecraft - Wii U Edition (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Ru) (Rev 1).png",
  "Named_Boxarts/Monster High - New Ghoul in School (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Monster High - New Ghoul in School (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Monster Hunter 3 Ultimate (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Monster Hunter 3 Ultimate (USA).png",
  "Named_Boxarts/Monster Hunter 3G - HD Ver. (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier G - Beginner's Package (Japan) (Rev 1).png",
  "Named_Boxarts/Monster Hunter Frontier G - Memorial Package (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier G5 - Premium Package (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier G6 - Premium Package (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier G7 - Premium Package (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier G8 - Premium Package (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier G9 - Premium Package (Japan).png",
  "Named_Boxarts/Monster Hunter Frontier GG - Premium Package (Japan).png",
  "Named_Boxarts/Musou Orochi 2 Hyper (Japan).png",
  "Named_Boxarts/NBA 2K13 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/NBA 2K13 (USA).png",
  "Named_Boxarts/NES Remix Pack (USA) (En,Fr,Es).png",
  "Named_Boxarts/Need for Speed - Most Wanted U (USA) (En,Fr,Es).png",
  "Named_Boxarts/New Super Luigi U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/New Super Luigi U (Japan).png",
  "Named_Boxarts/New Super Luigi U (USA) (En,Fr,Es).png",
  "Named_Boxarts/New Super Mario Bros. U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/New Super Mario Bros. U (Japan).png",
  "Named_Boxarts/New Super Mario Bros. U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/New Super Mario Bros. U + New Super Luigi U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/New Super Mario Bros. U + New Super Luigi U (USA) (En,Fr,Es).png",
  "Named_Boxarts/Nickelodeon SpongeBob SquarePants - Plankton's Robotic Revenge (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Boxarts/Nickelodeon SpongeBob SquarePants - Plankton's Robotic Revenge (USA) (En,Fr).png",
  "Named_Boxarts/Ninja Gaiden 3 - Razor's Edge (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Ninja Gaiden 3 - Razor's Edge (Japan).png",
  "Named_Boxarts/Ninja Gaiden 3 - Razor's Edge (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Nintendo Land (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Nintendo Land (Japan).png",
  "Named_Boxarts/Nintendo Land (USA) (En,Fr,Es).png",
  "Named_Boxarts/One Piece - Unlimited World R (Japan).png",
  "Named_Boxarts/One Piece - Unlimited World Red (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Pac-Man and the Ghostly Adventures (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Pac-Man and the Ghostly Adventures (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Pac-Man and the Ghostly Adventures 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Pac-Man and the Ghostly Adventures 2 (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Paper Mario - Color Splash (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Paper Mario - Color Splash (Japan).png",
  "Named_Boxarts/Paper Mario - Color Splash (USA) (En,Fr,Es).png",
  "Named_Boxarts/Pikmin 3 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Pikmin 3 (Japan).png",
  "Named_Boxarts/Pikmin 3 (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Pokken - Pokken Tournament (Japan).png",
  "Named_Boxarts/Pokken Tournament (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Pokken Tournament (USA) (En,Fr,Es).png",
  "Named_Boxarts/Project Zero - Maiden of Black Water (Europe) (En,Fr,De).png",
  "Named_Boxarts/Puyo Puyo Tetris (Japan).png",
  "Named_Boxarts/Rabbids Land (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Boxarts/Rabbids Land (Japan).png",
  "Named_Boxarts/Rabbids Land (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Rapala Pro Bass Fishing (USA).png",
  "Named_Boxarts/Rayman Legends (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Rayman Legends (Japan).png",
  "Named_Boxarts/Rayman Legends (USA) (En,Fr,Es).png",
  "Named_Boxarts/Resident Evil - Revelations (Europe) (En,Ja,Fr,De,Es,It,Nl,Pt,Pl,Ru) (Rev 1).png",
  "Named_Boxarts/Resident Evil - Revelations (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Pl,Ru) (Rev 1).png",
  "Named_Boxarts/Rodea the Sky Soldier (Europe) (En,Ja,Fr,De).png",
  "Named_Boxarts/Rodea the Sky Soldier (Japan).png",
  "Named_Boxarts/Rodea the Sky Soldier (USA) (En,Ja,Fr,De).png",
  "Named_Boxarts/Runbow - Deluxe Edition (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Ryuu ga Gotoku 1 &amp; 2 HD for Wii U (Japan).png",
  "Named_Boxarts/Scribblenauts Unlimited (Australia).png",
  "Named_Boxarts/Scribblenauts Unlimited (Europe) (En,Fr,De,Es,It,Nl) (Rev 1).png",
  "Named_Boxarts/Scribblenauts Unlimited (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Scribblenauts Unlimited (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Scribblenauts Unmasked - A DC Comics Adventure (Australia).png",
  "Named_Boxarts/Scribblenauts Unmasked - A DC Comics Adventure (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Shantae - Half-Genie Hero (USA) (En,Fr,Es).png",
  "Named_Boxarts/Shin Hokuto Musou (Japan).png",
  "Named_Boxarts/Shovel Knight (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Shovel Knight (USA).png",
  "Named_Boxarts/SiNG Party (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/SiNG Party (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Simple Series for Wii U Vol. 1 - The Family Party (Japan).png",
  "Named_Boxarts/Skylanders - Giants (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Boxarts/Skylanders - Giants (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Skylanders - Imaginators (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Boxarts/Skylanders - Imaginators (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Skylanders - SuperChargers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Boxarts/Skylanders - SuperChargers (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Skylanders - Trap Team (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Boxarts/Skylanders - Trap Team (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Sniper Elite V2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Sniper Elite V2 (Japan).png",
  "Named_Boxarts/Sniper Elite V2 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Snoopy's Grand Adventure (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Boxarts/Snoopy's Grand Adventure (USA) (En,Fr).png",
  "Named_Boxarts/Sonic &amp; All-Stars Racing Transformed (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Sonic &amp; All-Stars Racing Transformed (Japan).png",
  "Named_Boxarts/Sonic &amp; All-Stars Racing Transformed (USA) (En,Fr,Es).png",
  "Named_Boxarts/Sonic Boom - Rise of Lyric (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Sonic Boom - Rise of Lyric (USA) (Beta).png",
  "Named_Boxarts/Sonic Boom - Rise of Lyric (USA) (En,Fr,Es).png",
  "Named_Boxarts/Sonic Lost World (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Sonic Lost World (Japan).png",
  "Named_Boxarts/Sonic Lost World (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Boxarts/Sonic Toon - Taiko no Hihou (Japan).png",
  "Named_Boxarts/Splatoon (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Splatoon (Japan) (Rev 2).png",
  "Named_Boxarts/Splatoon (USA) (En,Fr,Es).png",
  "Named_Boxarts/Star Fox Guard (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Star Fox Guard (Japan).png",
  "Named_Boxarts/Star Fox Guard (USA) (En,Fr,Es).png",
  "Named_Boxarts/Star Fox Zero (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Star Fox Zero (Japan).png",
  "Named_Boxarts/Star Fox Zero (USA) (En,Fr,Es).png",
  "Named_Boxarts/SteamWorld Collection (Europe) (En,Ja,Fr,De,Es,It,Ru).png",
  "Named_Boxarts/SteamWorld Collection (USA) (En,Ja,Fr,De,Es,It,Ru).png",
  "Named_Boxarts/Super Mario 3D World (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Boxarts/Super Mario 3D World (Japan).png",
  "Named_Boxarts/Super Mario 3D World (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/Super Mario 3D World (USA) (En,Fr,Es).png",
  "Named_Boxarts/Super Mario 3D World (USA).png",
  "Named_Boxarts/Super Mario Maker (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Super Mario Maker (Japan).png",
  "Named_Boxarts/Super Mario Maker (USA) (En,Fr,Es) (Rev 5).png",
  "Named_Boxarts/Super Mario Maker (USA) (En,Fr,Es).png",
  "Named_Boxarts/Super Smash Bros. for Wii U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 4).png",
  "Named_Boxarts/Super Smash Bros. for Wii U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 4).png",
  "Named_Boxarts/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 9).png",
  "Named_Boxarts/Super Smash Bros. for Wii U (USA) (En,Fr,Es).png",
  "Named_Boxarts/Susume! Kinopio Taicho (Japan).png",
  "Named_Boxarts/Susume! Kinopio Taichou (Japan).png",
  "Named_Boxarts/Taiko no Tatsujin - Wii U Version! (Japan).png",
  "Named_Boxarts/Tank! Tank! Tank! (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Tank! Tank! Tank! (Japan).png",
  "Named_Boxarts/Tank! Tank! Tank! (USA) (En,Fr,Es).png",
  "Named_Boxarts/Tekken Tag Tournament 2 - Wii U Edition (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Boxarts/Tekken Tag Tournament 2 - Wii U Edition (Japan).png",
  "Named_Boxarts/Tekken Tag Tournament 2 - Wii U Edition (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Terraria (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Terraria (Japan).png",
  "Named_Boxarts/Terraria (USA) (En,Fr,Es).png",
  "Named_Boxarts/Teslagrad (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Tokyo Mirage Sessions FE (Europe).png",
  "Named_Boxarts/Tokyo Mirage Sessions FE (USA).png",
  "Named_Boxarts/Touch! Kirby Super Rainbow (Japan).png",
  "Named_Boxarts/Transformers Prime - The Game (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Boxarts/Transformers Prime - The Game (USA) (En,Fr).png",
  "Named_Boxarts/Voice, The - I Want You (USA).png",
  "Named_Boxarts/Walking Dead, The - Survival Instinct (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Walking Dead, The - Survival Instinct (USA).png",
  "Named_Boxarts/Warriors Orochi 3 Hyper (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Warriors Orochi 3 Hyper (USA).png",
  "Named_Boxarts/Watch Dogs (Japan).png",
  "Named_Boxarts/Watch_Dogs (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Boxarts/Watch_Dogs (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Wheel of Fortune (USA).png",
  "Named_Boxarts/Wii Fit U (Europe) (En,Fr,De,Es,It) (Rev 2).png",
  "Named_Boxarts/Wii Fit U (Japan) (Rev 3).png",
  "Named_Boxarts/Wii Fit U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Boxarts/Wii Karaoke U (Japan) (Trial Disc) (Rev 1).png",
  "Named_Boxarts/Wii Party U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Boxarts/Wii Party U (Japan) (Rev 2).png",
  "Named_Boxarts/Wii Party U (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Wii Sports Club (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Boxarts/Wii Sports Club (Japan) (Rev 1).png",
  "Named_Boxarts/Wii Sports Club (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Boxarts/Wonderful 101, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Wonderful 101, The (Japan).png",
  "Named_Boxarts/Wonderful 101, The (USA) (En,Ja).png",
  "Named_Boxarts/Xenoblade Chronicles X (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Xenoblade Chronicles X (USA) (En,Fr,Es).png",
  "Named_Boxarts/Xenoblade X (Japan).png",
  "Named_Boxarts/Yoshi Wool World (Japan) (Rev 1).png",
  "Named_Boxarts/Yoshi's Woolly World (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Boxarts/Yoshi's Woolly World (USA) (En,Fr,Es).png",
  "Named_Boxarts/Youkai Watch Dance - Just Dance Special Version (Japan).png",
  "Named_Boxarts/Your Shape - Fitness Evolved 2013 (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Your Shape - Fitness Evolved 2013 (USA) (En,Fr,Es).png",
  "Named_Boxarts/Zelda Musou (Japan) (Rev 1).png",
  "Named_Boxarts/Zelda no Densetsu - Breath of the Wild (Japan).png",
  "Named_Boxarts/Zelda no Densetsu - Kaze no Takuto HD (Japan).png",
  "Named_Boxarts/Zelda no Densetsu - Twilight Princess HD (Japan) (Rev 1).png",
  "Named_Boxarts/Zero - Nuregarasu no Miko (Japan).png",
  "Named_Boxarts/ZombiU (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Boxarts/ZombiU (Germany) (En,De).png",
  "Named_Boxarts/ZombiU (Japan).png",
  "Named_Boxarts/ZombiU (USA) (En,Fr,Es,Pt).png",
  "Named_Boxarts/Zumba Fitness - World Party (Europe) (En,Fr,De,Es,It).png",
  "Named_Boxarts/Zumba Fitness - World Party (Japan) (En,Ja).png",
  "Named_Boxarts/Zumba Fitness - World Party (USA).png",
  "Named_Snaps/007 Legends (Europe) (En,Fr,De).png",
  "Named_Snaps/007 Legends (USA) (En,Fr).png",
  "Named_Snaps/ABC Wipeout - Create &amp; Crash (USA).png",
  "Named_Snaps/ABC Wipeout 3 (USA).png",
  "Named_Snaps/Adventure Time - Explore the Dungeon Because I Don't Know! (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Adventure Time - Explore the Dungeon Because I Don't Know! (USA) (En,Fr,Es).png",
  "Named_Snaps/Adventure Time - Finn &amp; Jake Investigations (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Adventure Time - Finn &amp; Jake Investigations (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Amazing Spider-Man 2, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Amazing Spider-Man 2, The (USA) (En,Fr).png",
  "Named_Snaps/Angry Birds Star Wars (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Angry Birds Star Wars (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Angry Birds Trilogy (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Angry Birds Trilogy (USA) (En,Fr).png",
  "Named_Snaps/Animal Crossing - Amiibo Festival (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Animal Crossing - Amiibo Festival (USA) (En,Fr,Es).png",
  "Named_Snaps/Art Academy - Atelier (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Assassin's Creed III (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/Assassin's Creed III (Japan).png",
  "Named_Snaps/Assassin's Creed III (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Assassin's Creed IV - Black Flag (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/Assassin's Creed IV - Black Flag (Japan).png",
  "Named_Snaps/Assassin's Creed IV - Black Flag (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Axiom Verge (USA) (En,Fr,De,Es,It,Pt).png",
  "Named_Snaps/Baila Latino (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Barbie &amp; Her Sisters - Puppy Rescue (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Barbie &amp; Her Sisters - Puppy Rescue (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Barbie Dreamhouse Party (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Snaps/Barbie Dreamhouse Party (USA) (En,Fr,Es).png",
  "Named_Snaps/Batman - Arkham City - Armored Edition (Japan).png",
  "Named_Snaps/Batman - Arkham City - Armored Edition (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Batman - Arkham City - Armoured Edition (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Snaps/Batman - Arkham Origins (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Snaps/Batman - Arkham Origins (Japan).png",
  "Named_Snaps/Batman - Arkham Origins (USA) (En,Fr,Es).png",
  "Named_Snaps/Bayonetta (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Bayonetta (Japan) (Rev 1).png",
  "Named_Snaps/Bayonetta (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Bayonetta 2 (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Bayonetta 2 (Japan).png",
  "Named_Snaps/Bayonetta 2 (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Ben 10 - Omniverse 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Ben 10 - Omniverse 2 (USA) (En,Fr,Es).png",
  "Named_Snaps/Biohazard - Revelations - Unveiled Edition (Japan) (Rev 1).png",
  "Named_Snaps/Book of Unwritten Tales 2, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Book of Unwritten Tales 2, The (USA) (En,Fr,De,Es,It,Pl).png",
  "Named_Snaps/Brunswick Pro Bowling (USA).png",
  "Named_Snaps/Cabela's Big Game Hunter - Pro Hunts (USA).png",
  "Named_Snaps/Cabela's Dangerous Hunts 2013 (Europe) (En,Fr,De,It).png",
  "Named_Snaps/Cabela's Dangerous Hunts 2013 (USA) (En,Fr).png",
  "Named_Snaps/Call of Duty - Black Ops II (Europe) (En,Fr).png",
  "Named_Snaps/Call of Duty - Black Ops II (Europe) (Es,It).png",
  "Named_Snaps/Call of Duty - Black Ops II (Germany).png",
  "Named_Snaps/Call of Duty - Black Ops II (Japan) (En,Ja).png",
  "Named_Snaps/Call of Duty - Black Ops II (USA) (En,Fr).png",
  "Named_Snaps/Call of Duty - Ghosts (Europe) (En,Fr,De).png",
  "Named_Snaps/Call of Duty - Ghosts (Europe) (Es,It).png",
  "Named_Snaps/Call of Duty - Ghosts (Japan).png",
  "Named_Snaps/Call of Duty - Ghosts (USA) (En,Fr).png",
  "Named_Snaps/Captain Toad - Treasure Tracker (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Snaps/Captain Toad - Treasure Tracker (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Captain Toad - Treasure Tracker (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Captain Toad - Treasure Tracker (USA) (En,Fr,Es).png",
  "Named_Snaps/Captain Toad_ Treasure Tracker (Europe).png",
  "Named_Snaps/Captain Toad_ Treasure Tracker (USA).png",
  "Named_Snaps/Cocoto Magic Circus 2 (Europe) (En,Fr,De,Es,It,Nl,Pt).png",
  "Named_Snaps/Dairantou Smash Brothers for Wii U (Japan).png",
  "Named_Snaps/Darksiders - Warmastered Edition (Europe) (En,Fr,De,Es,It,Pt,Zh,Pl,Ru,Cs).png",
  "Named_Snaps/Darksiders - Warmastered Edition (USA) (En,Ja,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru,Cs).png",
  "Named_Snaps/Darksiders II (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Darksiders II (USA) (En,Fr,Es).png",
  "Named_Snaps/Deus Ex - Human Revolution - Director's Cut (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Deus Ex - Human Revolution - Director's Cut (USA) (En,Fr,Es).png",
  "Named_Snaps/Devil's Third (Europe) (En,Fr).png",
  "Named_Snaps/Devil's Third (Japan).png",
  "Named_Snaps/Devil's Third (USA) (En,Fr).png",
  "Named_Snaps/Disney DuckTales - Remastered (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Disney Epic Mickey 2 - Futatsu no Chikara (Japan).png",
  "Named_Snaps/Disney Epic Mickey 2 - The Power of Two (Europe) (En,Es).png",
  "Named_Snaps/Disney Epic Mickey 2 - The Power of Two (Europe) (En,Fr,De,Es,It,Pt).png",
  "Named_Snaps/Disney Epic Mickey 2 - The Power of Two (Scandinavia) (En,Sv,No,Da).png",
  "Named_Snaps/Disney Epic Mickey 2 - The Power of Two (USA) (En,Fr,Es).png",
  "Named_Snaps/Disney Infinity 2.0 Edition (USA) (En,Fr,Es,Pt) (Rev 1).png",
  "Named_Snaps/Disney Infinity 3.0 (Japan).png",
  "Named_Snaps/Disney Phineas and Ferb - Quest for Cool Stuff (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Disney Phineas and Ferb - Quest for Cool Stuff (USA).png",
  "Named_Snaps/Disney Planes (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Disney Planes (Russia).png",
  "Named_Snaps/Disney Planes (Scandinavia) (En,Sv,No,Da,Fi).png",
  "Named_Snaps/Disney Planes (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Disney Planes - Fire &amp; Rescue (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Disney Planes - Fire &amp; Rescue (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Disney-Pixar Cars 3 - Driven to Win (Europe) (En,Fr,De,Es,It,Nl,Pl,Ru).png",
  "Named_Snaps/Disney-Pixar Cars 3 - Driven to Win (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Donkey Kong - Tropical Freeze (Japan) (Rev 3).png",
  "Named_Snaps/Donkey Kong Country - Tropical Freeze (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Snaps/Donkey Kong Country - Tropical Freeze (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Donkey Kong Country - Tropical Freeze (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Donkey Kong Country - Tropical Freeze (USA) (En,Fr,Es).png",
  "Named_Snaps/Doubutsu no Mori - Amiibo Festival (Japan).png",
  "Named_Snaps/Dragon Quest X - 5000-nen no Tabiji - Haruka naru Kokyou e Online (Japan).png",
  "Named_Snaps/Dragon Quest X - All in One Package (Japan) (BTPJ).png",
  "Named_Snaps/Dragon Quest X - Inishie no Ryuu no Denshou Online (Japan).png",
  "Named_Snaps/Dragon Quest X - Mezameshi Itsutsu no Shuzoku Online (Japan) (Rev 1).png",
  "Named_Snaps/Dragon Quest X - Nemureru Yuusha to Michibiki no Meiyuu Online (Japan) (Rev 10).png",
  "Named_Snaps/DreamWorks How to Train Your Dragon 2 (Europe) (En,Fr,De,Es,It,Pt).png",
  "Named_Snaps/DreamWorks How to Train Your Dragon 2 (USA).png",
  "Named_Snaps/DreamWorks Kung Fu Panda - Showdown of Legendary Legends (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/DreamWorks Kung Fu Panda - Showdown of Legendary Legends (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/DreamWorks Penguins of Madagascar (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/DreamWorks Penguins of Madagascar (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/DreamWorks Rise of the Guardians (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/DreamWorks Rise of the Guardians (USA) (En,Fr,Es).png",
  "Named_Snaps/DreamWorks The Croods - Prehistoric Party! (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/DreamWorks The Croods - Prehistoric Party! (USA) (En,Fr,Es).png",
  "Named_Snaps/ESPN Sports Connection (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/F1 Race Stars - Powered Up Edition (Japan) (Rev 1).png",
  "Named_Snaps/FIFA 13 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/FIFA 13 - World Class Soccer (Japan).png",
  "Named_Snaps/FIFA Soccer 13 (USA) (En,Fr,Es).png",
  "Named_Snaps/Famicom Remix 1 + 2 (Japan).png",
  "Named_Snaps/Family Party - 30 Great Games - Obstacle Arcade (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Family Party - 30 Great Games - Obstacle Arcade (USA) (En,Fr,Es).png",
  "Named_Snaps/Fast Racing Neo (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Finding Teddy II - Definitive Edition (Europe) (En,Fr,De,Es,It,Pt,Ru).png",
  "Named_Snaps/Fit Music for Wii U (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Fujiko F. Fujio Characters Daishuugou! SF Dotabata Party!! (Japan).png",
  "Named_Snaps/Funky Barn (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Funky Barn (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Game &amp; Wario (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Game &amp; Wario (Japan) (Rev 1).png",
  "Named_Snaps/Game &amp; Wario (USA) (En,Fr,Es).png",
  "Named_Snaps/Game Party Champions (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Game Party Champions (USA) (En,Fr,Es).png",
  "Named_Snaps/Gen'ei Ibunroku FE (Japan).png",
  "Named_Snaps/Giana Sisters - Twisted Dreams - Director's Cut (USA) (En,Fr,Es).png",
  "Named_Snaps/Ginsei Shougi - Kyoutendo Toufuu Raijin (Japan).png",
  "Named_Snaps/Gotouchi Tetsudou - Gotouchi Chara to Nippon Zenkoku no Tabi (Japan).png",
  "Named_Snaps/Guitar Hero Live (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Guitar Hero Live (USA) (En,Fr,Es).png",
  "Named_Snaps/Hello Kitty Kruisers (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Hello Kitty Kruisers (USA).png",
  "Named_Snaps/Hot Wheels - World's Best Driver (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Hot Wheels - World's Best Driver (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Hunter's Trophy 2 - Europa (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Hyrule Warriors (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Snaps/Hyrule Warriors (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Hyrule Warriors (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Hyrule Warriors (USA) (En,Fr,Es).png",
  "Named_Snaps/Jeopardy! (USA).png",
  "Named_Snaps/Jett Tailfin (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Jikkuri Egokoro Kyoushitsu (Japan) (Rev 1).png",
  "Named_Snaps/Just Dance - Disney Party 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Just Dance - Disney Party 2 (USA) (En,Fr,De,Es,It,Pt).png",
  "Named_Snaps/Just Dance 2014 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 2014 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance 2015 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 2015 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance 2016 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 2016 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance 2017 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 2017 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance 2018 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 2018 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance 2019 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 2019 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance 4 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Just Dance 4 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Just Dance Kids 2014 (Europe) (En,Fr,Es).png",
  "Named_Snaps/Just Dance Kids 2014 (USA) (En,Fr,Es).png",
  "Named_Snaps/Just Dance Wii U (Japan) (Rev 1).png",
  "Named_Snaps/Kamen Rider - Battride War II (Japan).png",
  "Named_Snaps/Kamen Rider - Battride War II - Premium TV &amp; Movie Sound Edition (Japan).png",
  "Named_Snaps/Kamen Rider Summonride! (Japan).png",
  "Named_Snaps/Kirby and the Rainbow Curse (USA) (En,Fr,Es).png",
  "Named_Snaps/Kirby and the Rainbow Paintbrush (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/LEGO Batman 2 - DC Super Heroes (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/LEGO Batman 2 - DC Super Heroes (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO Batman 3 - Beyond Gotham (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO Batman 3 - Beyond Gotham (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO Batman 3 - The Game - Gotham kara Uchuu e (Japan).png",
  "Named_Snaps/LEGO City Undercover (Europe) (En,Fr,De,Es,It,Nl,Pt,Da,Ru) (Rev 1).png",
  "Named_Snaps/LEGO City Undercover (Europe) (En,Fr,De,Es,It,Nl,Pt,Da,Ru).png",
  "Named_Snaps/LEGO City Undercover (Japan).png",
  "Named_Snaps/LEGO City Undercover (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/LEGO City Undercover (USA) (En,Fr,Es).png",
  "Named_Snaps/LEGO Dimensions (Europe) (En,Fr,De,Nl,Da) (Rev 1).png",
  "Named_Snaps/LEGO Dimensions (USA) (En,Fr,Es).png",
  "Named_Snaps/LEGO Jurassic World (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO Jurassic World (Japan).png",
  "Named_Snaps/LEGO Jurassic World (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO Marvel Avengers (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO Marvel Avengers (Japan).png",
  "Named_Snaps/LEGO Marvel Avengers (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO Marvel Super Heroes (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO Marvel Super Heroes (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO Marvel Super Heroes - The Game (Japan).png",
  "Named_Snaps/LEGO Movie - The Game (Japan).png",
  "Named_Snaps/LEGO Movie, The - Videogame (Europe) (En,Fr,Es,It,Nl,Da) (Rev 1).png",
  "Named_Snaps/LEGO Movie, The - Videogame (Europe) (En,Fr,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO Movie, The - Videogame (USA) (En,Fr,Es,Pt) (Rev 1).png",
  "Named_Snaps/LEGO Movie, The - Videogame (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO Star Wars - Force no Kakusei (Japan).png",
  "Named_Snaps/LEGO Star Wars - The Force Awakens (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO Star Wars - The Force Awakens (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/LEGO The Hobbit (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Snaps/LEGO The Hobbit (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Legend of Kay - Anniversary (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Legend of Kay - Anniversary (USA) (En,Fr,De,Es,It).png",
  "Named_Snaps/Legend of Zelda, The - Breath of the Wild (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/Legend of Zelda, The - Breath of the Wild (USA) (En,Fr,Es).png",
  "Named_Snaps/Legend of Zelda, The - The Wind Waker HD (Europe, Australia) (En,Fr,De,Es,It).png",
  "Named_Snaps/Legend of Zelda, The - The Wind Waker HD (USA, Asia) (En,Fr,Es).png",
  "Named_Snaps/Legend of Zelda, The - Twilight Princess HD (Europe, Australia) (En,Fr,De,Es,It) (Rev 2).png",
  "Named_Snaps/Legend of Zelda, The - Twilight Princess HD (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Snaps/Luv Me Buddies - Wonderland (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Mario &amp; Sonic at Rio Olympic (Japan) (Rev 1).png",
  "Named_Snaps/Mario &amp; Sonic at the Rio 2016 Olympic Games (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Mario &amp; Sonic at the Rio 2016 Olympic Games (USA) (En,Fr,Es).png",
  "Named_Snaps/Mario &amp; Sonic at the Sochi 2014 Olympic Winter Games (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/Mario &amp; Sonic at the Sochi 2014 Olympic Winter Games (USA) (En,Fr,Es).png",
  "Named_Snaps/Mario &amp; Sonic at the Sochi Olympic (Japan) (Rev 1).png",
  "Named_Snaps/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Snaps/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 3).png",
  "Named_Snaps/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 4).png",
  "Named_Snaps/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Mario Kart 8 (Europe).png",
  "Named_Snaps/Mario Kart 8 (Japan) (Rev 3).png",
  "Named_Snaps/Mario Kart 8 (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Snaps/Mario Kart 8 (USA) (En,Fr,Es) (Rev 5).png",
  "Named_Snaps/Mario Kart 8 (USA) (En,Fr,Es).png",
  "Named_Snaps/Mario Kart 8 (USA).png",
  "Named_Snaps/Mario Party 10 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Mario Party 10 (Japan).png",
  "Named_Snaps/Mario Party 10 (USA) (En,Fr,Es).png",
  "Named_Snaps/Mario Tennis - Ultra Smash (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Mario Tennis - Ultra Smash (Japan) (Rev 1).png",
  "Named_Snaps/Mario Tennis - Ultra Smash (USA) (En,Fr,Es).png",
  "Named_Snaps/Marvel Avengers - Battle for Earth (Europe) (En,Fr,De,Es,It,Nl,Pl).png",
  "Named_Snaps/Marvel Avengers - Battle for Earth (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Mass Effect 3 - Special Edition (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Mass Effect 3 - Special Edition (USA) (En,Fr,Es).png",
  "Named_Snaps/Mass Effect 3 - Tokubetsu-ban (Japan).png",
  "Named_Snaps/Mighty No. 9 (Europe) (En,Ja,Fr,De,Es,It,Pt,Ru).png",
  "Named_Snaps/Mighty No. 9 (USA) (En,Ja,Fr,De,Es,It,Pt,Ru).png",
  "Named_Snaps/Minecraft - Story Mode - A Telltale Games Series - The Complete Adventure (Europe) (En,Fr,De,Es,Pt,Ru).png",
  "Named_Snaps/Minecraft - Story Mode - A Telltale Games Series - The Complete Adventure (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Minecraft - Wii U Edition (Europe) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Ru) (Rev 1).png",
  "Named_Snaps/Minecraft - Wii U Edition (Japan) (Rev 1).png",
  "Named_Snaps/Minecraft - Wii U Edition (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Ru) (Rev 1).png",
  "Named_Snaps/Monster High - New Ghoul in School (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Monster High - New Ghoul in School (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Monster Hunter 3 Ultimate (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Monster Hunter 3 Ultimate (USA).png",
  "Named_Snaps/Monster Hunter 3G - HD Ver. (Japan).png",
  "Named_Snaps/Musou Orochi 2 Hyper (Japan).png",
  "Named_Snaps/NBA 2K13 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/NBA 2K13 (USA).png",
  "Named_Snaps/NES Remix Pack (USA) (En,Fr,Es).png",
  "Named_Snaps/Need for Speed - Most Wanted U (USA) (En,Fr,Es).png",
  "Named_Snaps/New Super Luigi U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/New Super Luigi U (Japan).png",
  "Named_Snaps/New Super Luigi U (USA) (En,Fr,Es).png",
  "Named_Snaps/New Super Mario Bros. U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/New Super Mario Bros. U (Japan).png",
  "Named_Snaps/New Super Mario Bros. U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Snaps/New Super Mario Bros. U + New Super Luigi U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/New Super Mario Bros. U + New Super Luigi U (USA) (En,Fr,Es).png",
  "Named_Snaps/Nickelodeon SpongeBob SquarePants - Plankton's Robotic Revenge (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Snaps/Nickelodeon SpongeBob SquarePants - Plankton's Robotic Revenge (USA) (En,Fr).png",
  "Named_Snaps/Ninja Gaiden 3 - Razor's Edge (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Ninja Gaiden 3 - Razor's Edge (Japan).png",
  "Named_Snaps/Ninja Gaiden 3 - Razor's Edge (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Nintendo Land (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Nintendo Land (Japan).png",
  "Named_Snaps/Nintendo Land (USA) (En,Fr,Es).png",
  "Named_Snaps/One Piece - Unlimited World R (Japan).png",
  "Named_Snaps/One Piece - Unlimited World Red (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Pac-Man and the Ghostly Adventures (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Pac-Man and the Ghostly Adventures (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Pac-Man and the Ghostly Adventures 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Pac-Man and the Ghostly Adventures 2 (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Paper Mario - Color Splash (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Paper Mario - Color Splash (Japan).png",
  "Named_Snaps/Paper Mario - Color Splash (USA) (En,Fr,Es).png",
  "Named_Snaps/Pikmin 3 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Pikmin 3 (Japan).png",
  "Named_Snaps/Pikmin 3 (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Pokken - Pokken Tournament (Japan).png",
  "Named_Snaps/Pokken Tournament (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Pokken Tournament (USA) (En,Fr,Es).png",
  "Named_Snaps/Project Zero - Maiden of Black Water (Europe) (En,Fr,De).png",
  "Named_Snaps/Puyo Puyo Tetris (Japan).png",
  "Named_Snaps/Rabbids Land (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/Rabbids Land (Japan).png",
  "Named_Snaps/Rabbids Land (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Rapala Pro Bass Fishing (USA).png",
  "Named_Snaps/Rayman Legends (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Rayman Legends (Japan).png",
  "Named_Snaps/Rayman Legends (USA) (En,Fr,Es).png",
  "Named_Snaps/Resident Evil - Revelations (Europe) (En,Ja,Fr,De,Es,It,Nl,Pt,Pl,Ru) (Rev 1).png",
  "Named_Snaps/Resident Evil - Revelations (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Pl,Ru) (Rev 1).png",
  "Named_Snaps/Rodea the Sky Soldier (Europe) (En,Ja,Fr,De).png",
  "Named_Snaps/Rodea the Sky Soldier (Japan).png",
  "Named_Snaps/Rodea the Sky Soldier (USA) (En,Ja,Fr,De).png",
  "Named_Snaps/Runbow - Deluxe Edition (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Ryuu ga Gotoku 1 &amp; 2 HD for Wii U (Japan).png",
  "Named_Snaps/Scribblenauts Unlimited (Australia).png",
  "Named_Snaps/Scribblenauts Unlimited (Europe) (En,Fr,De,Es,It,Nl) (Rev 1).png",
  "Named_Snaps/Scribblenauts Unlimited (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Scribblenauts Unlimited (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Scribblenauts Unmasked - A DC Comics Adventure (Australia).png",
  "Named_Snaps/Scribblenauts Unmasked - A DC Comics Adventure (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Shantae - Half-Genie Hero (USA) (En,Fr,Es).png",
  "Named_Snaps/Shin Hokuto Musou (Japan).png",
  "Named_Snaps/Shovel Knight (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Shovel Knight (USA).png",
  "Named_Snaps/Simple Series for Wii U Vol. 1 - The Family Party (Japan).png",
  "Named_Snaps/Skylanders - Giants (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Snaps/Skylanders - Giants (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Skylanders - Imaginators (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Snaps/Skylanders - Imaginators (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Skylanders - SuperChargers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Snaps/Skylanders - SuperChargers (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Skylanders - Swap Force (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Snaps/Skylanders - Swap Force (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Skylanders - Trap Team (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Snaps/Skylanders - Trap Team (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Sniper Elite V2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Sniper Elite V2 (Japan).png",
  "Named_Snaps/Sniper Elite V2 (USA) (En,Fr,Es).png",
  "Named_Snaps/Snoopy's Grand Adventure (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Snaps/Snoopy's Grand Adventure (USA) (En,Fr).png",
  "Named_Snaps/Sonic &amp; All-Stars Racing Transformed (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Sonic &amp; All-Stars Racing Transformed (Japan).png",
  "Named_Snaps/Sonic &amp; All-Stars Racing Transformed (USA) (En,Fr,Es).png",
  "Named_Snaps/Sonic Boom - Rise of Lyric (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Sonic Boom - Rise of Lyric (USA) (Beta).png",
  "Named_Snaps/Sonic Boom - Rise of Lyric (USA) (En,Fr,Es).png",
  "Named_Snaps/Sonic Lost World (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Sonic Lost World (Japan).png",
  "Named_Snaps/Sonic Lost World (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Snaps/Sonic Toon - Taiko no Hihou (Japan).png",
  "Named_Snaps/Splatoon (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Splatoon (Japan) (Rev 2).png",
  "Named_Snaps/Splatoon (USA) (En,Fr,Es).png",
  "Named_Snaps/Star Fox Guard (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Star Fox Guard (Japan).png",
  "Named_Snaps/Star Fox Guard (USA) (En,Fr,Es).png",
  "Named_Snaps/Star Fox Zero (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Star Fox Zero (Japan).png",
  "Named_Snaps/Star Fox Zero (USA) (En,Fr,Es).png",
  "Named_Snaps/Super Mario 3D World (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Snaps/Super Mario 3D World (Europe).png",
  "Named_Snaps/Super Mario 3D World (Japan).png",
  "Named_Snaps/Super Mario 3D World (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Snaps/Super Mario 3D World (USA) (En,Fr,Es).png",
  "Named_Snaps/Super Mario 3D World (USA).png",
  "Named_Snaps/Super Mario Maker (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Super Mario Maker (Japan).png",
  "Named_Snaps/Super Mario Maker (USA) (En,Fr,Es) (Rev 5).png",
  "Named_Snaps/Super Mario Maker (USA) (En,Fr,Es).png",
  "Named_Snaps/Super Smash Bros. for Wii U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 4).png",
  "Named_Snaps/Super Smash Bros. for Wii U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Snaps/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 4).png",
  "Named_Snaps/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 9).png",
  "Named_Snaps/Super Smash Bros. for Wii U (USA) (En,Fr,Es).png",
  "Named_Snaps/Susume! Kinopio Taicho (Japan).png",
  "Named_Snaps/Susume! Kinopio Taichou (Japan).png",
  "Named_Snaps/Taiko no Tatsujin - Tokumori! (Japan).png",
  "Named_Snaps/Tank! Tank! Tank! (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Tank! Tank! Tank! (Japan).png",
  "Named_Snaps/Tank! Tank! Tank! (USA) (En,Fr,Es).png",
  "Named_Snaps/Tekken Tag Tournament 2 - Wii U Edition (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Snaps/Tekken Tag Tournament 2 - Wii U Edition (Japan).png",
  "Named_Snaps/Tekken Tag Tournament 2 - Wii U Edition (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Terraria (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Terraria (Japan).png",
  "Named_Snaps/Terraria (USA) (En,Fr,Es).png",
  "Named_Snaps/Teslagrad (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Tokyo Mirage Sessions FE (Europe).png",
  "Named_Snaps/Tokyo Mirage Sessions FE (USA).png",
  "Named_Snaps/Tom Clancy's Splinter Cell - Blacklist (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/Tom Clancy's Splinter Cell - Blacklist (Japan).png",
  "Named_Snaps/Tom Clancy's Splinter Cell - Blacklist (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Touch! Kirby Super Rainbow (Japan).png",
  "Named_Snaps/Walking Dead, The - Survival Instinct (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Walking Dead, The - Survival Instinct (USA).png",
  "Named_Snaps/Warriors Orochi 3 Hyper (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Warriors Orochi 3 Hyper (USA).png",
  "Named_Snaps/Watch Dogs (Japan).png",
  "Named_Snaps/Watch_Dogs (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Snaps/Watch_Dogs (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Wheel of Fortune (USA).png",
  "Named_Snaps/Wii Fit U (Europe) (En,Fr,De,Es,It) (Rev 2).png",
  "Named_Snaps/Wii Fit U (Japan) (Rev 3).png",
  "Named_Snaps/Wii Fit U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Snaps/Wii Party U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Snaps/Wii Party U (Japan) (Rev 2).png",
  "Named_Snaps/Wii Party U (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Wii Sports Club (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Snaps/Wii Sports Club (Japan) (Rev 1).png",
  "Named_Snaps/Wii Sports Club (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Snaps/Wonderful 101, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Wonderful 101, The (Japan).png",
  "Named_Snaps/Wonderful 101, The (USA) (En,Ja).png",
  "Named_Snaps/Xenoblade Chronicles X (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Xenoblade Chronicles X (USA) (En,Fr,Es).png",
  "Named_Snaps/Xenoblade X (Japan).png",
  "Named_Snaps/Yoshi Wool World (Japan) (Rev 1).png",
  "Named_Snaps/Yoshi's Woolly World (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Snaps/Yoshi's Woolly World (USA) (En,Fr,Es).png",
  "Named_Snaps/Youkai Watch Dance - Just Dance Special Version (Japan).png",
  "Named_Snaps/Your Shape - Fitness Evolved 2013 (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Your Shape - Fitness Evolved 2013 (USA) (En,Fr,Es).png",
  "Named_Snaps/Zelda Musou (Japan) (Rev 1).png",
  "Named_Snaps/Zelda no Densetsu - Breath of the Wild (Japan).png",
  "Named_Snaps/Zelda no Densetsu - Kaze no Takuto HD (Japan).png",
  "Named_Snaps/Zelda no Densetsu - Twilight Princess HD (Japan) (Rev 1).png",
  "Named_Snaps/Zero - Nuregarasu no Miko (Japan).png",
  "Named_Snaps/ZombiU (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Snaps/ZombiU (Germany) (En,De).png",
  "Named_Snaps/ZombiU (Japan).png",
  "Named_Snaps/ZombiU (USA) (En,Fr,Es,Pt).png",
  "Named_Snaps/Zumba Fitness - World Party (Europe) (En,Fr,De,Es,It).png",
  "Named_Snaps/Zumba Fitness - World Party (Japan) (En,Ja).png",
  "Named_Snaps/Zumba Fitness - World Party (USA).png",
  "Named_Titles/007 Legends (Europe) (En,Fr,De).png",
  "Named_Titles/007 Legends (USA) (En,Fr).png",
  "Named_Titles/ABC Wipeout - Create &amp; Crash (USA).png",
  "Named_Titles/ABC Wipeout 3 (USA).png",
  "Named_Titles/Adventure Time - Explore the Dungeon Because I Don't Know! (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Adventure Time - Explore the Dungeon Because I Don't Know! (USA) (En,Fr,Es).png",
  "Named_Titles/Adventure Time - Finn &amp; Jake Investigations (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Adventure Time - Finn &amp; Jake Investigations (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Amazing Spider-Man 2, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Amazing Spider-Man 2, The (USA) (En,Fr).png",
  "Named_Titles/Angry Birds Star Wars (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Angry Birds Star Wars (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Angry Birds Trilogy (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Angry Birds Trilogy (USA) (En,Fr).png",
  "Named_Titles/Animal Crossing - Amiibo Festival (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Animal Crossing - Amiibo Festival (USA) (En,Fr,Es).png",
  "Named_Titles/Art Academy - Atelier (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Assassin's Creed III (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/Assassin's Creed III (Japan).png",
  "Named_Titles/Assassin's Creed III (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Assassin's Creed IV - Black Flag (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/Assassin's Creed IV - Black Flag (Japan).png",
  "Named_Titles/Assassin's Creed IV - Black Flag (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Axiom Verge (USA) (En,Fr,De,Es,It,Pt).png",
  "Named_Titles/Baila Latino (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Barbie &amp; Her Sisters - Puppy Rescue (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Barbie &amp; Her Sisters - Puppy Rescue (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Barbie Dreamhouse Party (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Titles/Barbie Dreamhouse Party (USA) (En,Fr,Es).png",
  "Named_Titles/Batman - Arkham City - Armored Edition (Japan).png",
  "Named_Titles/Batman - Arkham City - Armored Edition (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Batman - Arkham City - Armoured Edition (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Titles/Batman - Arkham Origins (Europe) (En,Fr,De,Es,It,Ru).png",
  "Named_Titles/Batman - Arkham Origins (Japan).png",
  "Named_Titles/Batman - Arkham Origins (USA) (En,Fr,Es).png",
  "Named_Titles/Bayonetta (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Bayonetta (Japan) (Rev 1).png",
  "Named_Titles/Bayonetta (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Bayonetta 2 (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Bayonetta 2 (Japan).png",
  "Named_Titles/Bayonetta 2 (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Ben 10 - Omniverse 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Ben 10 - Omniverse 2 (USA) (En,Fr,Es).png",
  "Named_Titles/Biohazard - Revelations - Unveiled Edition (Japan) (Rev 1).png",
  "Named_Titles/Book of Unwritten Tales 2, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Book of Unwritten Tales 2, The (USA) (En,Fr,De,Es,It,Pl).png",
  "Named_Titles/Brunswick Pro Bowling (USA).png",
  "Named_Titles/Cabela's Big Game Hunter - Pro Hunts (USA).png",
  "Named_Titles/Cabela's Dangerous Hunts 2013 (Europe) (En,Fr,De,It).png",
  "Named_Titles/Cabela's Dangerous Hunts 2013 (USA) (En,Fr).png",
  "Named_Titles/Call of Duty - Black Ops II (Europe) (En,Fr).png",
  "Named_Titles/Call of Duty - Black Ops II (Europe) (Es,It).png",
  "Named_Titles/Call of Duty - Black Ops II (Germany).png",
  "Named_Titles/Call of Duty - Black Ops II (Japan) (En,Ja).png",
  "Named_Titles/Call of Duty - Black Ops II (USA) (En,Fr).png",
  "Named_Titles/Call of Duty - Ghosts (Europe) (En,Fr,De).png",
  "Named_Titles/Call of Duty - Ghosts (Europe) (Es,It).png",
  "Named_Titles/Call of Duty - Ghosts (Japan).png",
  "Named_Titles/Call of Duty - Ghosts (USA) (En,Fr).png",
  "Named_Titles/Captain Toad - Treasure Tracker (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Titles/Captain Toad - Treasure Tracker (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Captain Toad - Treasure Tracker (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Captain Toad - Treasure Tracker (USA) (En,Fr,Es).png",
  "Named_Titles/Captain Toad_ Treasure Tracker (USA).png",
  "Named_Titles/Cocoto Magic Circus 2 (Europe) (En,Fr,De,Es,It,Nl,Pt).png",
  "Named_Titles/Dairantou Smash Brothers for Wii U (Japan).png",
  "Named_Titles/Darksiders - Warmastered Edition (Europe) (En,Fr,De,Es,It,Pt,Zh,Pl,Ru,Cs).png",
  "Named_Titles/Darksiders - Warmastered Edition (USA) (En,Ja,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru,Cs).png",
  "Named_Titles/Darksiders II (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Darksiders II (USA) (En,Fr,Es).png",
  "Named_Titles/Deus Ex - Human Revolution - Director's Cut (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Deus Ex - Human Revolution - Director's Cut (USA) (En,Fr,Es).png",
  "Named_Titles/Devil's Third (Europe) (En,Fr).png",
  "Named_Titles/Devil's Third (Japan).png",
  "Named_Titles/Devil's Third (USA) (En,Fr).png",
  "Named_Titles/Disney DuckTales - Remastered (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Disney Epic Mickey 2 - Futatsu no Chikara (Japan).png",
  "Named_Titles/Disney Epic Mickey 2 - The Power of Two (Europe) (En,Es).png",
  "Named_Titles/Disney Epic Mickey 2 - The Power of Two (Europe) (En,Fr,De,Es,It,Pt).png",
  "Named_Titles/Disney Epic Mickey 2 - The Power of Two (Scandinavia) (En,Sv,No,Da).png",
  "Named_Titles/Disney Epic Mickey 2 - The Power of Two (USA) (En,Fr,Es).png",
  "Named_Titles/Disney Infinity 2.0 Edition (USA) (En,Fr,Es,Pt) (Rev 1).png",
  "Named_Titles/Disney Infinity 3.0 (Japan).png",
  "Named_Titles/Disney Phineas and Ferb - Quest for Cool Stuff (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Disney Phineas and Ferb - Quest for Cool Stuff (USA).png",
  "Named_Titles/Disney Planes (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Disney Planes (Russia).png",
  "Named_Titles/Disney Planes (Scandinavia) (En,Sv,No,Da,Fi).png",
  "Named_Titles/Disney Planes (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Disney Planes - Fire &amp; Rescue (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Disney Planes - Fire &amp; Rescue (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Disney-Pixar Cars 3 - Driven to Win (Europe) (En,Fr,De,Es,It,Nl,Pl,Ru).png",
  "Named_Titles/Disney-Pixar Cars 3 - Driven to Win (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Donkey Kong - Tropical Freeze (Japan) (Rev 3).png",
  "Named_Titles/Donkey Kong Country - Tropical Freeze (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Titles/Donkey Kong Country - Tropical Freeze (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Donkey Kong Country - Tropical Freeze (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Donkey Kong Country - Tropical Freeze (USA) (En,Fr,Es).png",
  "Named_Titles/Doubutsu no Mori - Amiibo Festival (Japan).png",
  "Named_Titles/Dragon Quest X - 5000-nen no Tabiji - Haruka naru Kokyou e Online (Japan).png",
  "Named_Titles/Dragon Quest X - All in One Package (Japan) (BTPJ).png",
  "Named_Titles/Dragon Quest X - Inishie no Ryuu no Denshou Online (Japan).png",
  "Named_Titles/Dragon Quest X - Mezameshi Itsutsu no Shuzoku Online (Japan) (Rev 1).png",
  "Named_Titles/Dragon Quest X - Nemureru Yuusha to Michibiki no Meiyuu Online (Japan) (Rev 10).png",
  "Named_Titles/DreamWorks How to Train Your Dragon 2 (Europe) (En,Fr,De,Es,It,Pt).png",
  "Named_Titles/DreamWorks How to Train Your Dragon 2 (USA).png",
  "Named_Titles/DreamWorks Kung Fu Panda - Showdown of Legendary Legends (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/DreamWorks Kung Fu Panda - Showdown of Legendary Legends (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/DreamWorks Penguins of Madagascar (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/DreamWorks Penguins of Madagascar (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/DreamWorks Rise of the Guardians (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/DreamWorks Rise of the Guardians (USA) (En,Fr,Es).png",
  "Named_Titles/DreamWorks The Croods - Prehistoric Party! (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/DreamWorks The Croods - Prehistoric Party! (USA) (En,Fr,Es).png",
  "Named_Titles/ESPN Sports Connection (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/F1 Race Stars - Powered Up Edition (Japan) (Rev 1).png",
  "Named_Titles/FIFA 13 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/FIFA 13 - World Class Soccer (Japan).png",
  "Named_Titles/FIFA Soccer 13 (USA) (En,Fr,Es).png",
  "Named_Titles/Famicom Remix 1 + 2 (Japan).png",
  "Named_Titles/Family Party - 30 Great Games - Obstacle Arcade (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Family Party - 30 Great Games - Obstacle Arcade (USA) (En,Fr,Es).png",
  "Named_Titles/Fast Racing Neo (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Finding Teddy II - Definitive Edition (Europe) (En,Fr,De,Es,It,Pt,Ru).png",
  "Named_Titles/Fit Music for Wii U (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Fujiko F. Fujio Characters Daishuugou! SF Dotabata Party!! (Japan).png",
  "Named_Titles/Funky Barn (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Funky Barn (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Game &amp; Wario (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Game &amp; Wario (Japan) (Rev 1).png",
  "Named_Titles/Game &amp; Wario (USA) (En,Fr,Es).png",
  "Named_Titles/Game Party Champions (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Game Party Champions (USA) (En,Fr,Es).png",
  "Named_Titles/Gen'ei Ibunroku FE (Japan).png",
  "Named_Titles/Giana Sisters - Twisted Dreams - Director's Cut (USA) (En,Fr,Es).png",
  "Named_Titles/Ginsei Shougi - Kyoutendo Toufuu Raijin (Japan).png",
  "Named_Titles/Gotouchi Tetsudou - Gotouchi Chara to Nippon Zenkoku no Tabi (Japan).png",
  "Named_Titles/Guitar Hero Live (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Guitar Hero Live (USA) (En,Fr,Es).png",
  "Named_Titles/Hello Kitty Kruisers (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Hello Kitty Kruisers (USA).png",
  "Named_Titles/Hot Wheels - World's Best Driver (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Hot Wheels - World's Best Driver (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Hunter's Trophy 2 - Europa (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Hyrule Warriors (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Titles/Hyrule Warriors (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Hyrule Warriors (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Hyrule Warriors (USA) (En,Fr,Es).png",
  "Named_Titles/Jeopardy! (USA).png",
  "Named_Titles/Jett Tailfin (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Jikkuri Egokoro Kyoushitsu (Japan) (Rev 1).png",
  "Named_Titles/Just Dance - Disney Party 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Just Dance - Disney Party 2 (USA) (En,Fr,De,Es,It,Pt).png",
  "Named_Titles/Just Dance 2014 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 2014 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance 2015 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 2015 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance 2016 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 2016 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance 2017 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 2017 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance 2018 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 2018 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance 2019 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 2019 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance 4 (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Just Dance 4 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Just Dance Kids 2014 (Europe) (En,Fr,Es).png",
  "Named_Titles/Just Dance Kids 2014 (USA) (En,Fr,Es).png",
  "Named_Titles/Just Dance Wii U (Japan) (Rev 1).png",
  "Named_Titles/Kamen Rider - Battride War II (Japan).png",
  "Named_Titles/Kamen Rider - Battride War II - Premium TV &amp; Movie Sound Edition (Japan).png",
  "Named_Titles/Kamen Rider Summonride! (Japan).png",
  "Named_Titles/Kirby and the Rainbow Curse (USA) (En,Fr,Es).png",
  "Named_Titles/Kirby and the Rainbow Paintbrush (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/LEGO Batman 2 - DC Super Heroes (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/LEGO Batman 2 - DC Super Heroes (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO Batman 3 - Beyond Gotham (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Titles/LEGO Batman 3 - Beyond Gotham (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO Batman 3 - The Game - Gotham kara Uchuu e (Japan).png",
  "Named_Titles/LEGO City Undercover (Europe) (En,Fr,De,Es,It,Nl,Pt,Da,Ru) (Rev 1).png",
  "Named_Titles/LEGO City Undercover (Europe) (En,Fr,De,Es,It,Nl,Pt,Da,Ru).png",
  "Named_Titles/LEGO City Undercover (Japan).png",
  "Named_Titles/LEGO City Undercover (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/LEGO City Undercover (USA) (En,Fr,Es).png",
  "Named_Titles/LEGO Dimensions (Europe) (En,Fr,De,Nl,Da) (Rev 1).png",
  "Named_Titles/LEGO Dimensions (USA) (En,Fr,Es).png",
  "Named_Titles/LEGO Jurassic World (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Titles/LEGO Jurassic World (Japan).png",
  "Named_Titles/LEGO Jurassic World (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO Marvel Avengers (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Titles/LEGO Marvel Avengers (Japan).png",
  "Named_Titles/LEGO Marvel Avengers (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO Marvel Super Heroes (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Titles/LEGO Marvel Super Heroes (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO Marvel Super Heroes - The Game (Japan).png",
  "Named_Titles/LEGO Movie - The Game (Japan).png",
  "Named_Titles/LEGO Movie, The - Videogame (Europe) (En,Fr,Es,It,Nl,Da) (Rev 1).png",
  "Named_Titles/LEGO Movie, The - Videogame (Europe) (En,Fr,Es,It,Nl,Da).png",
  "Named_Titles/LEGO Movie, The - Videogame (USA) (En,Fr,Es,Pt) (Rev 1).png",
  "Named_Titles/LEGO Movie, The - Videogame (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO Star Wars - Force no Kakusei (Japan).png",
  "Named_Titles/LEGO Star Wars - The Force Awakens (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Titles/LEGO Star Wars - The Force Awakens (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/LEGO The Hobbit (Europe) (En,Fr,De,Es,It,Nl,Da).png",
  "Named_Titles/LEGO The Hobbit (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Legend of Kay - Anniversary (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Legend of Kay - Anniversary (USA) (En,Fr,De,Es,It).png",
  "Named_Titles/Legend of Zelda, The - Breath of the Wild (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/Legend of Zelda, The - Breath of the Wild (USA) (En,Fr,Es).png",
  "Named_Titles/Legend of Zelda, The - The Wind Waker HD (Europe, Australia) (En,Fr,De,Es,It).png",
  "Named_Titles/Legend of Zelda, The - The Wind Waker HD (USA, Asia) (En,Fr,Es).png",
  "Named_Titles/Legend of Zelda, The - Twilight Princess HD (Europe, Australia) (En,Fr,De,Es,It) (Rev 2).png",
  "Named_Titles/Legend of Zelda, The - Twilight Princess HD (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Titles/Luv Me Buddies - Wonderland (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Mario &amp; Sonic at Rio Olympic (Japan) (Rev 1).png",
  "Named_Titles/Mario &amp; Sonic at the Rio 2016 Olympic Games (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Mario &amp; Sonic at the Rio 2016 Olympic Games (USA) (En,Fr,Es).png",
  "Named_Titles/Mario &amp; Sonic at the Sochi 2014 Olympic Winter Games (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/Mario &amp; Sonic at the Sochi 2014 Olympic Winter Games (USA) (En,Fr,Es).png",
  "Named_Titles/Mario &amp; Sonic at the Sochi Olympic (Japan) (Rev 1).png",
  "Named_Titles/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Titles/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 3).png",
  "Named_Titles/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 4).png",
  "Named_Titles/Mario Kart 8 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Mario Kart 8 (Japan) (Rev 3).png",
  "Named_Titles/Mario Kart 8 (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Titles/Mario Kart 8 (USA) (En,Fr,Es) (Rev 5).png",
  "Named_Titles/Mario Kart 8 (USA) (En,Fr,Es).png",
  "Named_Titles/Mario Kart 8 (USA).png",
  "Named_Titles/Mario Party 10 (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Mario Party 10 (Japan).png",
  "Named_Titles/Mario Party 10 (USA) (En,Fr,Es).png",
  "Named_Titles/Mario Tennis - Ultra Smash (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Mario Tennis - Ultra Smash (Japan) (Rev 1).png",
  "Named_Titles/Mario Tennis - Ultra Smash (USA) (En,Fr,Es).png",
  "Named_Titles/Marvel Avengers - Battle for Earth (Europe) (En,Fr,De,Es,It,Nl,Pl).png",
  "Named_Titles/Marvel Avengers - Battle for Earth (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Mass Effect 3 - Special Edition (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Mass Effect 3 - Special Edition (USA) (En,Fr,Es).png",
  "Named_Titles/Mass Effect 3 - Tokubetsu-ban (Japan).png",
  "Named_Titles/Mighty No. 9 (Europe) (En,Ja,Fr,De,Es,It,Pt,Ru).png",
  "Named_Titles/Mighty No. 9 (USA) (En,Ja,Fr,De,Es,It,Pt,Ru).png",
  "Named_Titles/Minecraft - Story Mode - A Telltale Games Series - The Complete Adventure (Europe) (En,Fr,De,Es,Pt,Ru).png",
  "Named_Titles/Minecraft - Story Mode - A Telltale Games Series - The Complete Adventure (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Minecraft - Wii U Edition (Europe) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Ru) (Rev 1).png",
  "Named_Titles/Minecraft - Wii U Edition (Japan) (Rev 1).png",
  "Named_Titles/Minecraft - Wii U Edition (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Ru) (Rev 1).png",
  "Named_Titles/Monster High - New Ghoul in School (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Monster High - New Ghoul in School (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Monster Hunter 3 Ultimate (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Monster Hunter 3 Ultimate (USA).png",
  "Named_Titles/Monster Hunter 3G - HD Ver. (Japan).png",
  "Named_Titles/Musou Orochi 2 Hyper (Japan).png",
  "Named_Titles/NBA 2K13 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/NBA 2K13 (USA).png",
  "Named_Titles/NES Remix Pack (USA) (En,Fr,Es).png",
  "Named_Titles/Need for Speed - Most Wanted U (USA) (En,Fr,Es).png",
  "Named_Titles/New Super Luigi U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/New Super Luigi U (Japan).png",
  "Named_Titles/New Super Luigi U (USA) (En,Fr,Es).png",
  "Named_Titles/New Super Mario Bros. U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/New Super Mario Bros. U (Japan).png",
  "Named_Titles/New Super Mario Bros. U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Titles/New Super Mario Bros. U + New Super Luigi U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/New Super Mario Bros. U + New Super Luigi U (USA) (En,Fr,Es).png",
  "Named_Titles/Nickelodeon SpongeBob SquarePants - Plankton's Robotic Revenge (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Titles/Nickelodeon SpongeBob SquarePants - Plankton's Robotic Revenge (USA) (En,Fr).png",
  "Named_Titles/Ninja Gaiden 3 - Razor's Edge (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Ninja Gaiden 3 - Razor's Edge (Japan).png",
  "Named_Titles/Ninja Gaiden 3 - Razor's Edge (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Nintendo Land (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Nintendo Land (Japan).png",
  "Named_Titles/Nintendo Land (USA) (En,Fr,Es).png",
  "Named_Titles/One Piece - Unlimited World R (Japan).png",
  "Named_Titles/One Piece - Unlimited World Red (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Pac-Man and the Ghostly Adventures (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Pac-Man and the Ghostly Adventures (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Pac-Man and the Ghostly Adventures 2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Pac-Man and the Ghostly Adventures 2 (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Paper Mario - Color Splash (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Paper Mario - Color Splash (Japan).png",
  "Named_Titles/Paper Mario - Color Splash (USA) (En,Fr,Es).png",
  "Named_Titles/Pikmin 3 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Pikmin 3 (Japan).png",
  "Named_Titles/Pikmin 3 (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Pokken - Pokken Tournament (Japan).png",
  "Named_Titles/Pokken Tournament (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Pokken Tournament (USA) (En,Fr,Es).png",
  "Named_Titles/Project Zero - Maiden of Black Water (Europe) (En,Fr,De).png",
  "Named_Titles/Puyo Puyo Tetris (Japan).png",
  "Named_Titles/Rabbids Land (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/Rabbids Land (Japan).png",
  "Named_Titles/Rabbids Land (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Rapala Pro Bass Fishing (USA).png",
  "Named_Titles/Rayman Legends (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Rayman Legends (Japan).png",
  "Named_Titles/Rayman Legends (USA) (En,Fr,Es).png",
  "Named_Titles/Resident Evil - Revelations (Europe) (En,Ja,Fr,De,Es,It,Nl,Pt,Pl,Ru) (Rev 1).png",
  "Named_Titles/Resident Evil - Revelations (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Pl,Ru) (Rev 1).png",
  "Named_Titles/Rodea the Sky Soldier (Europe) (En,Ja,Fr,De).png",
  "Named_Titles/Rodea the Sky Soldier (Japan).png",
  "Named_Titles/Rodea the Sky Soldier (USA) (En,Ja,Fr,De).png",
  "Named_Titles/Runbow - Deluxe Edition (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Ryuu ga Gotoku 1 &amp; 2 HD for Wii U (Japan).png",
  "Named_Titles/Scribblenauts Unlimited (Australia).png",
  "Named_Titles/Scribblenauts Unlimited (Europe) (En,Fr,De,Es,It,Nl) (Rev 1).png",
  "Named_Titles/Scribblenauts Unlimited (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Scribblenauts Unlimited (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Scribblenauts Unmasked - A DC Comics Adventure (Australia).png",
  "Named_Titles/Scribblenauts Unmasked - A DC Comics Adventure (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Shantae - Half-Genie Hero (USA) (En,Fr,Es).png",
  "Named_Titles/Shin Hokuto Musou (Japan).png",
  "Named_Titles/Shovel Knight (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Shovel Knight (USA).png",
  "Named_Titles/Simple Series for Wii U Vol. 1 - The Family Party (Japan).png",
  "Named_Titles/Skylanders - Giants (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Titles/Skylanders - Giants (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Skylanders - Imaginators (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Titles/Skylanders - Imaginators (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Skylanders - SuperChargers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Titles/Skylanders - SuperChargers (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Skylanders - Swap Force (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Titles/Skylanders - Swap Force (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Skylanders - Trap Team (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).png",
  "Named_Titles/Skylanders - Trap Team (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Sniper Elite V2 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Sniper Elite V2 (Japan).png",
  "Named_Titles/Sniper Elite V2 (USA) (En,Fr,Es).png",
  "Named_Titles/Snoopy's Grand Adventure (Europe) (En,Fr,De,Es,It,Nl,Sv).png",
  "Named_Titles/Snoopy's Grand Adventure (USA) (En,Fr).png",
  "Named_Titles/Sonic &amp; All-Stars Racing Transformed (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Sonic &amp; All-Stars Racing Transformed (Japan).png",
  "Named_Titles/Sonic &amp; All-Stars Racing Transformed (USA) (En,Fr,Es).png",
  "Named_Titles/Sonic Boom - Rise of Lyric (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Sonic Boom - Rise of Lyric (USA) (Beta).png",
  "Named_Titles/Sonic Boom - Rise of Lyric (USA) (En,Fr,Es).png",
  "Named_Titles/Sonic Lost World (Europe) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Sonic Lost World (Japan).png",
  "Named_Titles/Sonic Lost World (USA) (En,Ja,Fr,De,Es,It).png",
  "Named_Titles/Sonic Toon - Taiko no Hihou (Japan).png",
  "Named_Titles/Splatoon (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Splatoon (Japan) (Rev 2).png",
  "Named_Titles/Splatoon (USA) (En,Fr,Es).png",
  "Named_Titles/Star Fox Guard (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Star Fox Guard (Japan).png",
  "Named_Titles/Star Fox Guard (USA) (En,Fr,Es).png",
  "Named_Titles/Star Fox Zero (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Star Fox Zero (Japan).png",
  "Named_Titles/Star Fox Zero (USA) (En,Fr,Es).png",
  "Named_Titles/Super Mario 3D World (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Titles/Super Mario 3D World (Japan).png",
  "Named_Titles/Super Mario 3D World (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Titles/Super Mario 3D World (USA) (En,Fr,Es).png",
  "Named_Titles/Super Mario 3D World (USA).png",
  "Named_Titles/Super Mario Maker (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Super Mario Maker (Japan).png",
  "Named_Titles/Super Mario Maker (USA) (En,Fr,Es) (Rev 5).png",
  "Named_Titles/Super Mario Maker (USA) (En,Fr,Es).png",
  "Named_Titles/Super Smash Bros. for Wii U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 4).png",
  "Named_Titles/Super Smash Bros. for Wii U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Titles/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 4).png",
  "Named_Titles/Super Smash Bros. for Wii U (USA) (En,Fr,Es) (Rev 9).png",
  "Named_Titles/Super Smash Bros. for Wii U (USA) (En,Fr,Es).png",
  "Named_Titles/Susume! Kinopio Taicho (Japan).png",
  "Named_Titles/Susume! Kinopio Taichou (Japan).png",
  "Named_Titles/Taiko no Tatsujin - Tokumori! (Japan).png",
  "Named_Titles/Tank! Tank! Tank! (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Tank! Tank! Tank! (Japan).png",
  "Named_Titles/Tank! Tank! Tank! (USA) (En,Fr,Es).png",
  "Named_Titles/Tekken Tag Tournament 2 - Wii U Edition (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "Named_Titles/Tekken Tag Tournament 2 - Wii U Edition (Japan).png",
  "Named_Titles/Tekken Tag Tournament 2 - Wii U Edition (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Terraria (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Terraria (Japan).png",
  "Named_Titles/Terraria (USA) (En,Fr,Es).png",
  "Named_Titles/Teslagrad (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Tokyo Mirage Sessions FE (Europe).png",
  "Named_Titles/Tokyo Mirage Sessions FE (USA).png",
  "Named_Titles/Tom Clancy's Splinter Cell - Blacklist (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/Tom Clancy's Splinter Cell - Blacklist (Japan).png",
  "Named_Titles/Tom Clancy's Splinter Cell - Blacklist (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Touch! Kirby Super Rainbow (Japan).png",
  "Named_Titles/Walking Dead, The - Survival Instinct (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Walking Dead, The - Survival Instinct (USA).png",
  "Named_Titles/Warriors Orochi 3 Hyper (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Warriors Orochi 3 Hyper (USA).png",
  "Named_Titles/Watch Dogs (Japan).png",
  "Named_Titles/Watch_Dogs (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru).png",
  "Named_Titles/Watch_Dogs (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Wheel of Fortune (USA).png",
  "Named_Titles/Wii Fit U (Europe) (En,Fr,De,Es,It) (Rev 2).png",
  "Named_Titles/Wii Fit U (Japan) (Rev 3).png",
  "Named_Titles/Wii Fit U (USA) (En,Fr,Es) (Rev 2).png",
  "Named_Titles/Wii Party U (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Titles/Wii Party U (Japan) (Rev 2).png",
  "Named_Titles/Wii Party U (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Wii Sports Club (Europe) (En,Fr,De,Es,It,Nl,Pt,Ru) (Rev 1).png",
  "Named_Titles/Wii Sports Club (Japan) (Rev 1).png",
  "Named_Titles/Wii Sports Club (USA) (En,Fr,Es) (Rev 1).png",
  "Named_Titles/Wonderful 101, The (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Wonderful 101, The (Japan).png",
  "Named_Titles/Wonderful 101, The (USA) (En,Ja).png",
  "Named_Titles/Xenoblade Chronicles X (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Xenoblade Chronicles X (USA) (En,Fr,Es).png",
  "Named_Titles/Xenoblade X (Japan).png",
  "Named_Titles/Yoshi Wool World (Japan) (Rev 1).png",
  "Named_Titles/Yoshi's Woolly World (Europe) (En,Fr,De,Es,It,Nl).png",
  "Named_Titles/Yoshi's Woolly World (USA) (En,Fr,Es).png",
  "Named_Titles/Youkai Watch Dance - Just Dance Special Version (Japan).png",
  "Named_Titles/Your Shape - Fitness Evolved 2013 (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Your Shape - Fitness Evolved 2013 (USA) (En,Fr,Es).png",
  "Named_Titles/Zelda Musou (Japan) (Rev 1).png",
  "Named_Titles/Zelda no Densetsu - Breath of the Wild (Japan).png",
  "Named_Titles/Zelda no Densetsu - Kaze no Takuto HD (Japan).png",
  "Named_Titles/Zelda no Densetsu - Twilight Princess HD (Japan) (Rev 1).png",
  "Named_Titles/Zero - Nuregarasu no Miko (Japan).png",
  "Named_Titles/ZombiU (Europe) (En,Fr,De,Es,It,Nl,Ru).png",
  "Named_Titles/ZombiU (Germany) (En,De).png",
  "Named_Titles/ZombiU (Japan).png",
  "Named_Titles/ZombiU (USA) (En,Fr,Es,Pt).png",
  "Named_Titles/Zumba Fitness - World Party (Europe) (En,Fr,De,Es,It).png",
  "Named_Titles/Zumba Fitness - World Party (Japan) (En,Ja).png",
  "Named_Titles/Zumba Fitness - World Party (USA).png",
}
