return {
  "Named_Boxarts/2020 Super Baseball (set 1).png",
  "Named_Boxarts/2020 Super Baseball (set 2).png",
  "Named_Boxarts/2020 Super Baseball (set 3).png",
  "Named_Boxarts/3 Count Bout _ Fire Suplex (NGM-043)(NGH-043).png",
  "Named_Boxarts/Aero Fighters 2 _ Sonic Wings 2.png",
  "Named_Boxarts/Aero Fighters 3 _ Sonic Wings 3.png",
  "Named_Boxarts/Aggressors of Dark Kombat _ Tsuukai GANGAN Koushinkyoku (ADM-008)(ADH-008).png",
  "Named_Boxarts/Alpha Mission II _ ASO II - Last Guardian (NGM-007)(NGH-007).png",
  "Named_Boxarts/Alpha Mission II _ ASO II - Last Guardian (prototype).png",
  "Named_Boxarts/Andro Dunos (NGM-049)(NGH-049).png",
  "Named_Boxarts/Art of Fighting 2 _ Ryuuko no Ken 2 (NGH-056).png",
  "Named_Boxarts/Art of Fighting 2 _ Ryuuko no Ken 2 (NGM-056).png",
  "Named_Boxarts/Art of Fighting 3 - The Path of the Warrior (Korean release).png",
  "Named_Boxarts/Art of Fighting 3 - The Path of the Warrior _ Art of Fighting - Ryuuko no Ken Gaiden.png",
  "Named_Boxarts/Art of Fighting _ Ryuuko no Ken (NGM-044)(NGH-044).png",
  "Named_Boxarts/Bakatonosama Mahjong Manyuuki (MOM-002)(MOH-002).png",
  "Named_Boxarts/Bang Bang Busters (2010 NCI release).png",
  "Named_Boxarts/Bang Bead.png",
  "Named_Boxarts/Baseball Stars 2.png",
  "Named_Boxarts/Baseball Stars Professional (NGH-002).png",
  "Named_Boxarts/Baseball Stars Professional (NGM-002).png",
  "Named_Boxarts/Battle Flip Shot.png",
  "Named_Boxarts/Blazing Star.png",
  "Named_Boxarts/Blue's Journey _ Raguy (ALM-001)(ALH-001).png",
  "Named_Boxarts/Breakers Revenge.png",
  "Named_Boxarts/Breakers.png",
  "Named_Boxarts/Burning Fight (NGH-018)(US).png",
  "Named_Boxarts/Burning Fight (NGM-018)(NGH-018).png",
  "Named_Boxarts/Burning Fight (prototype, older) [Prototype].png",
  "Named_Boxarts/Burning Fight (prototype, ver 23.3, 910326) [Prototype].png",
  "Named_Boxarts/Captain Tomaday.png",
  "Named_Boxarts/Chibi Marukochan Deluxe Quiz.png",
  "Named_Boxarts/Choutetsu Brikin'ger - Iron Clad (prototype).png",
  "Named_Boxarts/Choutetsu Brikin'ger - Iron Clad (prototype, bootleg).png",
  "Named_Boxarts/Crossed Swords (ALM-002)(ALH-002).png",
  "Named_Boxarts/Crouching Tiger Hidden Dragon 2003 (set 1) [Bootleg, Hack of _The King of Fighters 2001_].png",
  "Named_Boxarts/Crouching Tiger Hidden Dragon 2003 Super Plus [Bootleg].png",
  "Named_Boxarts/Crouching Tiger Hidden Dragon 2003 Super Plus alternate [Bootleg].png",
  "Named_Boxarts/Cyber-Lip (NGM-010).png",
  "Named_Boxarts/Digger Man [Homebrew].png",
  "Named_Boxarts/Double Dragon (Neo-Geo).png",
  "Named_Boxarts/Eight Man (NGM-025)(NGH-025).png",
  "Named_Boxarts/Far East of Eden - Kabuki Klash _ Tengai Makyou - Shin Den.png",
  "Named_Boxarts/Fatal Fury - King of Fighters _ Garou Densetsu - shukumei no tatakai (NGM-033)(NGH-033).png",
  "Named_Boxarts/Fatal Fury 2 _ Garou Densetsu 2 - arata-naru tatakai (NGM-047)(NGH-047).png",
  "Named_Boxarts/Fatal Fury 3 - Road to the Final Victory _ Garou Densetsu 3 - haruka-naru tatakai (NGM-069)(NGH-069).png",
  "Named_Boxarts/Fatal Fury Special _ Garou Densetsu Special (set 1)(NGM-058)(NGH-058).png",
  "Named_Boxarts/Fatal Fury Special _ Garou Densetsu Special (set 2)(NGM-058)(NGH-058).png",
  "Named_Boxarts/Fight Fever (set 1).png",
  "Named_Boxarts/Fight Fever (set 2).png",
  "Named_Boxarts/Fighters Swords (Korean release of Samurai Shodown III).png",
  "Named_Boxarts/Football Frenzy (NGM-034)(NGH-034).png",
  "Named_Boxarts/Galaxy Fight - Universal Warriors.png",
  "Named_Boxarts/Ganryu _ Musashi Ganryuki.png",
  "Named_Boxarts/Garou - Mark of the Wolves (NGH-2530).png",
  "Named_Boxarts/Garou - Mark of the Wolves (NGM-2530) (NGH-2530).png",
  "Named_Boxarts/Garou - Mark of the Wolves (NGM-2530).png",
  "Named_Boxarts/Garou - Mark of the Wolves (bootleg).png",
  "Named_Boxarts/Garou - Mark of the Wolves (prototype).png",
  "Named_Boxarts/Ghost Pilots (NGH-020)(US).png",
  "Named_Boxarts/Ghost Pilots (NGM-020)(NGH-020).png",
  "Named_Boxarts/Ghostlop (prototype).png",
  "Named_Boxarts/Goal! Goal! Goal!.png",
  "Named_Boxarts/Gururin.png",
  "Named_Boxarts/Jockey Grand Prix (set 1).png",
  "Named_Boxarts/Jockey Grand Prix (set 2).png",
  "Named_Boxarts/Jyanshin Densetsu - Quest of Jongmaster.png",
  "Named_Boxarts/Karnov's Revenge _ Fighter's History Dynamite.png",
  "Named_Boxarts/King of Gladiator (The King of Fighters '97 bootleg).png",
  "Named_Boxarts/King of the Monsters (set 1).png",
  "Named_Boxarts/King of the Monsters (set 2).png",
  "Named_Boxarts/King of the Monsters 2 - The Next Thing (NGM-039)(NGH-039).png",
  "Named_Boxarts/King of the Monsters 2 - The Next Thing (prototype).png",
  "Named_Boxarts/Kizuna Encounter - Super Tag Battle _ Fu'un Super Tag Battle.png",
  "Named_Boxarts/Lansquenet 2004 (Shock Troopers - 2nd Squad bootleg).png",
  "Named_Boxarts/Last Resort (prototype).png",
  "Named_Boxarts/Last Resort.png",
  "Named_Boxarts/League Bowling (NGM-019)(NGH-019).png",
  "Named_Boxarts/Legend of Success Joe _ Ashitano Joe Densetsu.png",
  "Named_Boxarts/Magical Drop II.png",
  "Named_Boxarts/Magical Drop III.png",
  "Named_Boxarts/Magician Lord (NGH-005).png",
  "Named_Boxarts/Magician Lord (NGM-005).png",
  "Named_Boxarts/Mahjong Kyo Retsuden (NGM-004)(NGH-004).png",
  "Named_Boxarts/Matrimelee _ Shin Gouketsuji Ichizoku Toukon (NGM-2660) (NGH-2660).png",
  "Named_Boxarts/Matrimelee _ Shin Gouketsuji Ichizoku Toukon (bootleg) [Bootleg].png",
  "Named_Boxarts/Metal Slug - Super Vehicle-001.png",
  "Named_Boxarts/Metal Slug 2 - Super Vehicle-001_II (NGM-2410) (NGH-2410).png",
  "Named_Boxarts/Metal Slug 3 (NGH-2560).png",
  "Named_Boxarts/Metal Slug 3 (NGM-2560).png",
  "Named_Boxarts/Metal Slug 4 (NGH-2630).png",
  "Named_Boxarts/Metal Slug 4 (NGM-2630).png",
  "Named_Boxarts/Metal Slug 4 Plus (bootleg).png",
  "Named_Boxarts/Metal Slug 5 (NGH-2680).png",
  "Named_Boxarts/Metal Slug 5 (NGM-2680).png",
  "Named_Boxarts/Metal Slug 5 Plus (bootleg).png",
  "Named_Boxarts/Metal Slug 6 (Metal Slug 3 bootleg).png",
  "Named_Boxarts/Metal Slug X - Super Vehicle-001 (NGM-2500)(NGH-2500).png",
  "Named_Boxarts/Minasanno Okagesamadesu! Daisugorokutaikai (MOM-001)(MOH-001).png",
  "Named_Boxarts/Money Puzzle Exchanger _ Money Idol Exchanger.png",
  "Named_Boxarts/Mutation Nation (NGM-014)(NGH-014).png",
  "Named_Boxarts/NAM-1975 (NGM-001)(NGH-001).png",
  "Named_Boxarts/Neo Bomberman.png",
  "Named_Boxarts/Neo Drift Out - New Technology.png",
  "Named_Boxarts/Neo Mr. Do!.png",
  "Named_Boxarts/Neo Turf Masters _ Big Tournament Golf.png",
  "Named_Boxarts/Neo-Geo Cup '98 - The Road to the Victory.png",
  "Named_Boxarts/Nightmare in the Dark (bootleg).png",
  "Named_Boxarts/Nightmare in the Dark.png",
  "Named_Boxarts/Ninja Combat (NGH-009).png",
  "Named_Boxarts/Ninja Combat (NGM-009).png",
  "Named_Boxarts/Ninja Commando.png",
  "Named_Boxarts/Ninja Master's - haoh-ninpo-cho.png",
  "Named_Boxarts/Over Top.png",
  "Named_Boxarts/Pae Wang Jeon Seol _ Legend of a Warrior (Korean censored Samurai Shodown IV).png",
  "Named_Boxarts/Panic Bomber.png",
  "Named_Boxarts/Pleasure Goal _ Futsal - 5 on 5 Mini Soccer (NGM-219).png",
  "Named_Boxarts/Pochi and Nyaa (Ver 2.00).png",
  "Named_Boxarts/Pochi and Nyaa (Ver 2.02).png",
  "Named_Boxarts/Pop 'n Bounce _ Gapporin.png",
  "Named_Boxarts/Power Spikes II (NGM-068).png",
  "Named_Boxarts/Prehistoric Isle 2.png",
  "Named_Boxarts/Pulstar.png",
  "Named_Boxarts/Puzzle Bobble 2 _ Bust-A-Move Again (Neo-Geo).png",
  "Named_Boxarts/Puzzle Bobble _ Bust-A-Move (Neo-Geo) (NGM-083).png",
  "Named_Boxarts/Puzzle Bobble _ Bust-A-Move (Neo-Geo) (bootleg) [Bootleg].png",
  "Named_Boxarts/Puzzle De Pon! R!.png",
  "Named_Boxarts/Puzzle De Pon!.png",
  "Named_Boxarts/Puzzled _ Joy Joy Kid (NGM-021)(NGH-021).png",
  "Named_Boxarts/Quiz Daisousa Sen - The Last Count Down (Korean release).png",
  "Named_Boxarts/Quiz Daisousa Sen - The Last Count Down (NGM-023)(NGH-023).png",
  "Named_Boxarts/Quiz King of Fighters (Korean release).png",
  "Named_Boxarts/Quiz King of Fighters (SAM-080)(SAH-080).png",
  "Named_Boxarts/Quiz Meitantei Neo _ Geo - Quiz Daisousa Sen part 2 (NGM-042)(NGH-042).png",
  "Named_Boxarts/Rage of the Dragons (NGM-264_).png",
  "Named_Boxarts/Ragnagard _ Shin-Oh-Ken.png",
  "Named_Boxarts/Real Bout Fatal Fury 2 - The Newcomers (Korean release).png",
  "Named_Boxarts/Real Bout Fatal Fury 2 - The Newcomers _ Real Bout Garou Densetsu 2 - the newcomers (NGH-2400).png",
  "Named_Boxarts/Real Bout Fatal Fury 2 - The Newcomers _ Real Bout Garou Densetsu 2 - the newcomers (NGM-2400).png",
  "Named_Boxarts/Real Bout Fatal Fury Special _ Real Bout Garou Densetsu Special (Korean release).png",
  "Named_Boxarts/Real Bout Fatal Fury Special _ Real Bout Garou Densetsu Special.png",
  "Named_Boxarts/Real Bout Fatal Fury _ Real Bout Garou Densetsu (NGM-095)(NGH-095).png",
  "Named_Boxarts/Real Bout Fatal Fury _ Real Bout Garou Densetsu (bug fix revision).png",
  "Named_Boxarts/Riding Hero (NGM-006)(NGH-006).png",
  "Named_Boxarts/Riding Hero (set 2).png",
  "Named_Boxarts/Robo Army (set 1).png",
  "Named_Boxarts/SNK vs. Capcom - SVC Chaos (NGM-2690)(NGH-2690).png",
  "Named_Boxarts/SNK vs. Capcom - SVC Chaos (bootleg).png",
  "Named_Boxarts/SNK vs. Capcom - SVC Chaos Plus (bootleg set 1) [Bootleg].png",
  "Named_Boxarts/SNK vs. Capcom - SVC Chaos Plus (bootleg set 2) [Bootleg].png",
  "Named_Boxarts/SNK vs. Capcom - SVC Chaos Super Plus (bootleg).png",
  "Named_Boxarts/Samurai Shodown II _ Shin Samurai Spirits - Haohmaru jigokuhen (NGM-063)(NGH-063).png",
  "Named_Boxarts/Samurai Shodown III _ Samurai Spirits - Zankurou Musouken (NGH-087).png",
  "Named_Boxarts/Samurai Shodown III _ Samurai Spirits - Zankurou Musouken (NGM-087).png",
  "Named_Boxarts/Samurai Shodown IV - Amakusa's Revenge _ Samurai Spirits - Amakusa Kourin (NGM-222)(NGH-222).png",
  "Named_Boxarts/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGH-2720) (1st release, censored).png",
  "Named_Boxarts/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGH-2720) (2nd release, less censored).png",
  "Named_Boxarts/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGM-2720).png",
  "Named_Boxarts/Samurai Shodown V _ Samurai Spirits Zero (NGH-2700).png",
  "Named_Boxarts/Samurai Shodown V _ Samurai Spirits Zero (NGM-2700, set 1).png",
  "Named_Boxarts/Samurai Shodown V _ Samurai Spirits Zero (NGM-2700, set 2).png",
  "Named_Boxarts/Samurai Shodown V _ Samurai Spirits Zero (bootleg) [Bootleg].png",
  "Named_Boxarts/Samurai Shodown _ Samurai Spirits (NGH-045).png",
  "Named_Boxarts/Samurai Shodown _ Samurai Spirits (NGM-045).png",
  "Named_Boxarts/Saulabi Spirits _ Jin Saulabi Tu Hon (Korean release of Samurai Shodown II).png",
  "Named_Boxarts/Savage Reign _ Fu'un Mokushiroku - kakutou sousei.png",
  "Named_Boxarts/Sengoku 2 _ Sengoku Denshou 2.png",
  "Named_Boxarts/Sengoku 3 _ Sengoku Densho 2001 (Set 2).png",
  "Named_Boxarts/Sengoku 3 _ Sengoku Densho 2001 (set 1).png",
  "Named_Boxarts/Sengoku _ Sengoku Denshou (NGH-017)(US).png",
  "Named_Boxarts/Sengoku _ Sengoku Denshou (NGM-017)(NGH-017).png",
  "Named_Boxarts/Shock Troopers (set 1).png",
  "Named_Boxarts/Shock Troopers (set 2).png",
  "Named_Boxarts/Shock Troopers - 2nd Squad.png",
  "Named_Boxarts/Soccer Brawl (NGH-031).png",
  "Named_Boxarts/Soccer Brawl (NGM-031).png",
  "Named_Boxarts/Spin Master _ Miracle Adventure.png",
  "Named_Boxarts/Stakes Winner 2.png",
  "Named_Boxarts/Stakes Winner _ Stakes Winner - GI kinzen seiha e no michi.png",
  "Named_Boxarts/Street Hoop _ Street Slam _ Dunk Dream (DEM-004) (DEH-004).png",
  "Named_Boxarts/Strikers 1945 Plus.png",
  "Named_Boxarts/Super Dodge Ball _ Kunio no Nekketsu Toukyuu Densetsu.png",
  "Named_Boxarts/Super Sidekicks 2 - The World Championship _ Tokuten Ou 2 - real fight football (NGM-061)(NGH-061).png",
  "Named_Boxarts/Super Sidekicks 3 - The Next Glory _ Tokuten Ou 3 - eikou e no michi.png",
  "Named_Boxarts/Super Sidekicks _ Tokuten Ou.png",
  "Named_Boxarts/Syougi No Tatsujin - Master of Shougi.png",
  "Named_Boxarts/Tecmo World Soccer '96.png",
  "Named_Boxarts/The Irritating Maze _ Ultra Denryu Iraira Bou.png",
  "Named_Boxarts/The King of Fighters '94 (NGM-055)(NGH-055).png",
  "Named_Boxarts/The King of Fighters '95 (NGH-084).png",
  "Named_Boxarts/The King of Fighters '95 (NGH-084, alternate board).png",
  "Named_Boxarts/The King of Fighters '95 (NGM-084).png",
  "Named_Boxarts/The King of Fighters '96 (NGH-214).png",
  "Named_Boxarts/The King of Fighters '96 (NGM-214).png",
  "Named_Boxarts/The King of Fighters '97 (Korean release).png",
  "Named_Boxarts/The King of Fighters '97 (NGH-2320).png",
  "Named_Boxarts/The King of Fighters '97 (NGM-2320).png",
  "Named_Boxarts/The King of Fighters '97 Plus (bootleg).png",
  "Named_Boxarts/The King of Fighters '97 oroshi plus 2003 [Bootleg].png",
  "Named_Boxarts/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board, set 1).png",
  "Named_Boxarts/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board, set 2).png",
  "Named_Boxarts/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGH-2420).png",
  "Named_Boxarts/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGM-2420).png",
  "Named_Boxarts/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGM-2420, alternate board).png",
  "Named_Boxarts/The King of Fighters '99 - Millennium Battle (Korean release).png",
  "Named_Boxarts/The King of Fighters '99 - Millennium Battle (NGH-2510).png",
  "Named_Boxarts/The King of Fighters '99 - Millennium Battle (NGM-2510).png",
  "Named_Boxarts/The King of Fighters '99 - Millennium Battle (earlier).png",
  "Named_Boxarts/The King of Fighters '99 - Millennium Battle (prototype).png",
  "Named_Boxarts/The King of Fighters 10th Anniversary (bootleg) [Bootleg].png",
  "Named_Boxarts/The King of Fighters 10th Anniversary 2005 Unique (bootleg) [Bootleg].png",
  "Named_Boxarts/The King of Fighters 10th Anniversary Extra Plus (bootleg) [Bootleg].png",
  "Named_Boxarts/The King of Fighters 2000 (NGM-2570) (NGH-2570).png",
  "Named_Boxarts/The King of Fighters 2000 (not encrypted).png",
  "Named_Boxarts/The King of Fighters 2001 (NGH-2621).png",
  "Named_Boxarts/The King of Fighters 2001 (NGM-262_).png",
  "Named_Boxarts/The King of Fighters 2002 (NGM-2650)(NGH-2650).png",
  "Named_Boxarts/The King of Fighters 2002 (bootleg).png",
  "Named_Boxarts/The King of Fighters 2002 Magic Plus (bootleg).png",
  "Named_Boxarts/The King of Fighters 2002 Magic Plus II (bootleg).png",
  "Named_Boxarts/The King of Fighters 2002 Plus (bootleg set 1).png",
  "Named_Boxarts/The King of Fighters 2002 Plus (bootleg set 2).png",
  "Named_Boxarts/The King of Fighters 2003 (NGH-2710).png",
  "Named_Boxarts/The King of Fighters 2003 (NGM-2710).png",
  "Named_Boxarts/The King of Fighters 2003 (NGM-2710, Export).png",
  "Named_Boxarts/The King of Fighters 2003 (bootleg set 1) [Bootleg].png",
  "Named_Boxarts/The King of Fighters 2003 (bootleg set 2) [Bootleg].png",
  "Named_Boxarts/The King of Fighters 2004 Plus _ Hero (bootleg) [Bootleg].png",
  "Named_Boxarts/The King of Fighters 2004 Ultra Plus (bootleg) [Bootleg].png",
  "Named_Boxarts/The King of Fighters Special Edition 2004 (bootleg) [Bootleg].png",
  "Named_Boxarts/The Last Blade 2 _ Bakumatsu Roman - Dai Ni Maku Gekka no Kenshi (NGM-2430)(NGH-2430).png",
  "Named_Boxarts/The Last Blade _ Bakumatsu Roman - Gekka no Kenshi (NGH-2340).png",
  "Named_Boxarts/The Last Blade _ Bakumatsu Roman - Gekka no Kenshi (NGM-2340).png",
  "Named_Boxarts/The Last Soldier (Korean release of The Last Blade).png",
  "Named_Boxarts/The Super Spy (NGM-011)(NGH-011).png",
  "Named_Boxarts/The Ultimate 11 - The SNK Football Championship _ Tokuten Ou - Honoo no Libero.png",
  "Named_Boxarts/Thrash Rally (ALM-003)(ALH-003).png",
  "Named_Boxarts/Top Hunter - Roddy _ Cathy (NGH-046).png",
  "Named_Boxarts/Top Hunter - Roddy _ Cathy (NGM-046).png",
  "Named_Boxarts/Top Player's Golf (NGM-003)(NGH-003).png",
  "Named_Boxarts/Treasure of the Caribbean.png",
  "Named_Boxarts/Twinkle Star Sprites.png",
  "Named_Boxarts/V-Liner (set 1).png",
  "Named_Boxarts/V-Liner (set 2).png",
  "Named_Boxarts/Viewpoint.png",
  "Named_Boxarts/Voltage Fighter - Gowcaizer _ Choujin Gakuen Gowcaizer.png",
  "Named_Boxarts/Waku Waku 7.png",
  "Named_Boxarts/Windjammers _ Flying Power Disc.png",
  "Named_Boxarts/World Heroes (ALH-005).png",
  "Named_Boxarts/World Heroes (ALM-005).png",
  "Named_Boxarts/World Heroes (set 3).png",
  "Named_Boxarts/World Heroes 2 (ALM-006)(ALH-006).png",
  "Named_Boxarts/World Heroes 2 Jet (ADM-007)(ADH-007).png",
  "Named_Boxarts/World Heroes Perfect.png",
  "Named_Boxarts/Zed Blade _ Operation Ragnarok.png",
  "Named_Boxarts/Zintrick _ Oshidashi Zentrix (hack _ bootleg) [Bootleg].png",
  "Named_Boxarts/Zupapa!.png",
  "Named_Snaps/2020 Super Baseball (set 1).png",
  "Named_Snaps/2020 Super Baseball (set 2).png",
  "Named_Snaps/2020 Super Baseball (set 3).png",
  "Named_Snaps/3 Count Bout _ Fire Suplex (NGM-043)(NGH-043).png",
  "Named_Snaps/Aero Fighters 2 _ Sonic Wings 2.png",
  "Named_Snaps/Aero Fighters 3 _ Sonic Wings 3.png",
  "Named_Snaps/Aggressors of Dark Kombat _ Tsuukai GANGAN Koushinkyoku (ADM-008)(ADH-008).png",
  "Named_Snaps/Alpha Mission II _ ASO II - Last Guardian (NGM-007)(NGH-007).png",
  "Named_Snaps/Alpha Mission II _ ASO II - Last Guardian (prototype).png",
  "Named_Snaps/Andro Dunos (NGM-049)(NGH-049).png",
  "Named_Snaps/Art of Fighting 2 _ Ryuuko no Ken 2 (NGH-056).png",
  "Named_Snaps/Art of Fighting 2 _ Ryuuko no Ken 2 (NGM-056).png",
  "Named_Snaps/Art of Fighting 3 - The Path of the Warrior (Korean release).png",
  "Named_Snaps/Art of Fighting 3 - The Path of the Warrior _ Art of Fighting - Ryuuko no Ken Gaiden.png",
  "Named_Snaps/Art of Fighting _ Ryuuko no Ken (NGM-044)(NGH-044).png",
  "Named_Snaps/Bakatonosama Mahjong Manyuuki (MOM-002)(MOH-002).png",
  "Named_Snaps/Bang Bang Busters (2010 NCI release).png",
  "Named_Snaps/Bang Bead.png",
  "Named_Snaps/Baseball Stars 2.png",
  "Named_Snaps/Baseball Stars Professional (NGH-002).png",
  "Named_Snaps/Baseball Stars Professional (NGM-002).png",
  "Named_Snaps/Battle Flip Shot.png",
  "Named_Snaps/Blazing Star.png",
  "Named_Snaps/Blue's Journey _ Raguy (ALH-001).png",
  "Named_Snaps/Blue's Journey _ Raguy (ALM-001)(ALH-001).png",
  "Named_Snaps/Breakers Revenge.png",
  "Named_Snaps/Breakers.png",
  "Named_Snaps/Burning Fight (NGH-018)(US).png",
  "Named_Snaps/Burning Fight (NGM-018)(NGH-018).png",
  "Named_Snaps/Burning Fight (prototype, older) [Prototype].png",
  "Named_Snaps/Burning Fight (prototype, ver 23.3, 910326) [Prototype].png",
  "Named_Snaps/Captain Tomaday.png",
  "Named_Snaps/Chibi Marukochan Deluxe Quiz.png",
  "Named_Snaps/Choutetsu Brikin'ger _ Iron Clad (Prototype).png",
  "Named_Snaps/Choutetsu Brikin'ger _ Iron Clad (Prototype, bootleg).png",
  "Named_Snaps/Crossed Swords (ALM-002)(ALH-002).png",
  "Named_Snaps/Crossed Swords 2 (bootleg CD to cartridge conversion).png",
  "Named_Snaps/Crouching Tiger Hidden Dragon 2003 (set 1) [Bootleg, Hack of _The King of Fighters 2001_].png",
  "Named_Snaps/Crouching Tiger Hidden Dragon 2003 Super Plus [Bootleg].png",
  "Named_Snaps/Crouching Tiger Hidden Dragon 2003 Super Plus alternate [Bootleg].png",
  "Named_Snaps/Cyber-Lip (NGM-010).png",
  "Named_Snaps/Digger Man [Homebrew].png",
  "Named_Snaps/Double Dragon (Neo-Geo).png",
  "Named_Snaps/Dragon's Heaven (development board).png",
  "Named_Snaps/Eight Man (NGM-025)(NGH-025).png",
  "Named_Snaps/Far East of Eden - Kabuki Klash _ Tengai Makyou - Shin Den.png",
  "Named_Snaps/Fatal Fury - King of Fighters _ Garou Densetsu - shukumei no tatakai (NGM-033)(NGH-033).png",
  "Named_Snaps/Fatal Fury 2 _ Garou Densetsu 2 - arata-naru tatakai (NGM-047)(NGH-047).png",
  "Named_Snaps/Fatal Fury 3 - Road to the Final Victory _ Garou Densetsu 3 - haruka-naru tatakai (NGM-069)(NGH-069).png",
  "Named_Snaps/Fatal Fury Special _ Garou Densetsu Special (set 1)(NGM-058)(NGH-058).png",
  "Named_Snaps/Fatal Fury Special _ Garou Densetsu Special (set 2)(NGM-058)(NGH-058).png",
  "Named_Snaps/Fight Fever (set 1).png",
  "Named_Snaps/Fight Fever (set 2).png",
  "Named_Snaps/Fighters Swords (Korean release of Samurai Shodown III).png",
  "Named_Snaps/Football Frenzy (NGM-034)(NGH-034).png",
  "Named_Snaps/Galaxy Fight - Universal Warriors.png",
  "Named_Snaps/Ganryu _ Musashi Ganryuki.png",
  "Named_Snaps/Garou - Mark of the Wolves (NGH-2530).png",
  "Named_Snaps/Garou - Mark of the Wolves (NGM-2530) (NGH-2530).png",
  "Named_Snaps/Garou - Mark of the Wolves (NGM-2530).png",
  "Named_Snaps/Garou - Mark of the Wolves (bootleg).png",
  "Named_Snaps/Garou - Mark of the Wolves (prototype).png",
  "Named_Snaps/Ghost Pilots (NGH-020)(US).png",
  "Named_Snaps/Ghost Pilots (NGM-020)(NGH-020).png",
  "Named_Snaps/Ghost Pilots (prototype).png",
  "Named_Snaps/Ghostlop (prototype).png",
  "Named_Snaps/Goal! Goal! Goal!.png",
  "Named_Snaps/Gururin.png",
  "Named_Snaps/Idol Mahjong Final Romance 2 (Neo-Geo, bootleg of CD version).png",
  "Named_Snaps/Jockey Grand Prix (set 1).png",
  "Named_Snaps/Jockey Grand Prix (set 2).png",
  "Named_Snaps/Jyanshin Densetsu - Quest of Jongmaster.png",
  "Named_Snaps/Karnov's Revenge _ Fighter's History Dynamite.png",
  "Named_Snaps/King of Gladiator (The King of Fighters '97 bootleg).png",
  "Named_Snaps/King of the Monsters (set 1).png",
  "Named_Snaps/King of the Monsters (set 2).png",
  "Named_Snaps/King of the Monsters 2 - The Next Thing (NGM-039)(NGH-039).png",
  "Named_Snaps/King of the Monsters 2 - The Next Thing (older).png",
  "Named_Snaps/King of the Monsters 2 - The Next Thing (prototype).png",
  "Named_Snaps/Kizuna Encounter - Super Tag Battle _ Fu'un Super Tag Battle.png",
  "Named_Snaps/Lansquenet 2004 (Shock Troopers - 2nd Squad bootleg).png",
  "Named_Snaps/Last Hope.png",
  "Named_Snaps/Last Resort (prototype).png",
  "Named_Snaps/Last Resort.png",
  "Named_Snaps/League Bowling (NGM-019)(NGH-019).png",
  "Named_Snaps/Legend of Success Joe _ Ashitano Joe Densetsu.png",
  "Named_Snaps/Magical Drop II.png",
  "Named_Snaps/Magical Drop III.png",
  "Named_Snaps/Magician Lord (NGH-005).png",
  "Named_Snaps/Magician Lord (NGM-005).png",
  "Named_Snaps/Mahjong Kyo Retsuden (NGM-004)(NGH-004).png",
  "Named_Snaps/Matrimelee _ Shin Gouketsuji Ichizoku Toukon (NGM-2660) (NGH-2660).png",
  "Named_Snaps/Matrimelee _ Shin Gouketsuji Ichizoku Toukon (bootleg) [Bootleg].png",
  "Named_Snaps/Metal Slug - Super Vehicle-001.png",
  "Named_Snaps/Metal Slug 2 - Super Vehicle-001_II (NGM-2410) (NGH-2410).png",
  "Named_Snaps/Metal Slug 3 (NGH-2560).png",
  "Named_Snaps/Metal Slug 3 (NGM-2560).png",
  "Named_Snaps/Metal Slug 3 (NGM-2560, earlier).png",
  "Named_Snaps/Metal Slug 4 (NGH-2630).png",
  "Named_Snaps/Metal Slug 4 (NGM-2630).png",
  "Named_Snaps/Metal Slug 4 Plus (bootleg).png",
  "Named_Snaps/Metal Slug 5 (NGH-2680).png",
  "Named_Snaps/Metal Slug 5 (NGM-2680).png",
  "Named_Snaps/Metal Slug 5 Plus (bootleg).png",
  "Named_Snaps/Metal Slug 6 (Metal Slug 3 bootleg).png",
  "Named_Snaps/Metal Slug X - Super Vehicle-001 (NGM-2500)(NGH-2500).png",
  "Named_Snaps/Minasanno Okagesamadesu! Daisugorokutaikai (MOM-001)(MOH-001).png",
  "Named_Snaps/Money Puzzle Exchanger _ Money Idol Exchanger.png",
  "Named_Snaps/Mutation Nation (NGM-014)(NGH-014).png",
  "Named_Snaps/NAM-1975 (NGM-001)(NGH-001).png",
  "Named_Snaps/Neo Bomberman.png",
  "Named_Snaps/Neo Drift Out - New Technology.png",
  "Named_Snaps/Neo Mr. Do!.png",
  "Named_Snaps/Neo Turf Masters _ Big Tournament Golf.png",
  "Named_Snaps/Neo-Geo Cup '98 - The Road to the Victory.png",
  "Named_Snaps/Nightmare in the Dark (bootleg).png",
  "Named_Snaps/Nightmare in the Dark.png",
  "Named_Snaps/Ninja Combat (NGH-009).png",
  "Named_Snaps/Ninja Combat (NGM-009).png",
  "Named_Snaps/Ninja Commando.png",
  "Named_Snaps/Ninja Master's - haoh-ninpo-cho.png",
  "Named_Snaps/Over Top.png",
  "Named_Snaps/Pae Wang Jeon Seol _ Legend of a Warrior (Korean censored Samurai Shodown IV).png",
  "Named_Snaps/Panic Bomber.png",
  "Named_Snaps/Pleasure Goal _ Futsal - 5 on 5 Mini Soccer (NGM-219).png",
  "Named_Snaps/Pochi and Nyaa (Ver 2.00).png",
  "Named_Snaps/Pochi and Nyaa (Ver 2.02).png",
  "Named_Snaps/Pop 'n Bounce _ Gapporin.png",
  "Named_Snaps/Power Spikes II (NGM-068).png",
  "Named_Snaps/Prehistoric Isle 2.png",
  "Named_Snaps/Pulstar.png",
  "Named_Snaps/Puzzle Bobble 2 _ Bust-A-Move Again (Neo-Geo).png",
  "Named_Snaps/Puzzle Bobble _ Bust-A-Move (Neo-Geo) (NGM-083).png",
  "Named_Snaps/Puzzle Bobble _ Bust-A-Move (Neo-Geo) (bootleg) [Bootleg].png",
  "Named_Snaps/Puzzle De Pon! R!.png",
  "Named_Snaps/Puzzle De Pon!.png",
  "Named_Snaps/Puzzled _ Joy Joy Kid (NGM-021)(NGH-021).png",
  "Named_Snaps/Quiz Daisousa Sen - The Last Count Down (NGM-023)(NGH-023).png",
  "Named_Snaps/Quiz King of Fighters (Korea).png",
  "Named_Snaps/Quiz King of Fighters (SAM-080)(SAH-080).png",
  "Named_Snaps/Quiz Meitantei Neo _ Geo - Quiz Daisousa Sen part 2 (NGM-042)(NGH-042).png",
  "Named_Snaps/Quiz Salibtamjeong - The Last Count Down (Korean localized Quiz Daisousa Sen).png",
  "Named_Snaps/Rage of the Dragons (NGH-2640).png",
  "Named_Snaps/Rage of the Dragons (NGM-264_).png",
  "Named_Snaps/Ragnagard _ Shin-Oh-Ken.png",
  "Named_Snaps/Real Bout Fatal Fury 2 - The Newcomers (Korean release).png",
  "Named_Snaps/Real Bout Fatal Fury 2 - The Newcomers _ Real Bout Garou Densetsu 2 - the newcomers (NGH-2400).png",
  "Named_Snaps/Real Bout Fatal Fury 2 - The Newcomers _ Real Bout Garou Densetsu 2 - the newcomers (NGM-2400).png",
  "Named_Snaps/Real Bout Fatal Fury Special _ Real Bout Garou Densetsu Special (Korean release).png",
  "Named_Snaps/Real Bout Fatal Fury Special _ Real Bout Garou Densetsu Special.png",
  "Named_Snaps/Real Bout Fatal Fury _ Real Bout Garou Densetsu (Korean release).png",
  "Named_Snaps/Real Bout Fatal Fury _ Real Bout Garou Densetsu (NGM-095)(NGH-095).png",
  "Named_Snaps/Real Bout Fatal Fury _ Real Bout Garou Densetsu (bug fix revision).png",
  "Named_Snaps/Riding Hero (NGM-006)(NGH-006).png",
  "Named_Snaps/Riding Hero (set 2).png",
  "Named_Snaps/Robo Army (NGM-032)(NGH-032).png",
  "Named_Snaps/Robo Army (set 1).png",
  "Named_Snaps/SNK vs. Capcom - SVC Chaos (NGM-2690)(NGH-2690).png",
  "Named_Snaps/SNK vs. Capcom - SVC Chaos (bootleg).png",
  "Named_Snaps/SNK vs. Capcom - SVC Chaos Plus (bootleg set 1) [Bootleg].png",
  "Named_Snaps/SNK vs. Capcom - SVC Chaos Plus (bootleg set 2) [Bootleg].png",
  "Named_Snaps/SNK vs. Capcom - SVC Chaos Super Plus (bootleg).png",
  "Named_Snaps/Samurai Shodown II _ Shin Samurai Spirits - Haohmaru jigokuhen (NGM-063)(NGH-063).png",
  "Named_Snaps/Samurai Shodown III _ Samurai Spirits - Zankurou Musouken (NGH-087).png",
  "Named_Snaps/Samurai Shodown III _ Samurai Spirits - Zankurou Musouken (NGM-087).png",
  "Named_Snaps/Samurai Shodown IV - Amakusa's Revenge _ Samurai Spirits - Amakusa Kourin (NGM-222)(NGH-222).png",
  "Named_Snaps/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGH-2720) (1st release, censored).png",
  "Named_Snaps/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGH-2720) (2nd release, less censored).png",
  "Named_Snaps/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGM-2720).png",
  "Named_Snaps/Samurai Shodown V _ Samurai Spirits Zero (NGH-2700).png",
  "Named_Snaps/Samurai Shodown V _ Samurai Spirits Zero (NGM-2700, set 1).png",
  "Named_Snaps/Samurai Shodown V _ Samurai Spirits Zero (NGM-2700, set 2).png",
  "Named_Snaps/Samurai Shodown V _ Samurai Spirits Zero (bootleg) [Bootleg].png",
  "Named_Snaps/Samurai Shodown _ Samurai Spirits (NGH-045).png",
  "Named_Snaps/Samurai Shodown _ Samurai Spirits (NGM-045).png",
  "Named_Snaps/Saulabi Spirits _ Jin Saulabi Tu Hon (Korean release of Samurai Shodown II).png",
  "Named_Snaps/Saulabi Spirits _ Jin Saulabi Tu Hon (Korean release of Samurai Shodown II, set 2).png",
  "Named_Snaps/Savage Reign _ Fu'un Mokushiroku - kakutou sousei.png",
  "Named_Snaps/Sengoku 2 _ Sengoku Denshou 2.png",
  "Named_Snaps/Sengoku 3 _ Sengoku Densho 2001 (Set 2).png",
  "Named_Snaps/Sengoku 3 _ Sengoku Densho 2001 (set 1).png",
  "Named_Snaps/Sengoku _ Sengoku Denshou (NGH-017)(US).png",
  "Named_Snaps/Sengoku _ Sengoku Denshou (NGM-017)(NGH-017).png",
  "Named_Snaps/Shock Troopers (set 1).png",
  "Named_Snaps/Shock Troopers (set 2).png",
  "Named_Snaps/Shock Troopers - 2nd Squad.png",
  "Named_Snaps/Soccer Brawl (NGH-031).png",
  "Named_Snaps/Soccer Brawl (NGM-031).png",
  "Named_Snaps/Spin Master _ Miracle Adventure.png",
  "Named_Snaps/Stakes Winner 2.png",
  "Named_Snaps/Stakes Winner _ Stakes Winner - GI Kinzen  Seiha e no Michi (early development board).png",
  "Named_Snaps/Stakes Winner _ Stakes Winner - GI kinzen seiha e no michi.png",
  "Named_Snaps/Street Hoop _ Street Slam _ Dunk Dream (DEM-004) (DEH-004).png",
  "Named_Snaps/Strikers 1945 Plus.png",
  "Named_Snaps/Super Bubble Pop (MVS).png",
  "Named_Snaps/Super Dodge Ball _ Kunio no Nekketsu Toukyuu Densetsu.png",
  "Named_Snaps/Super Sidekicks 2 - The World Championship _ Tokuten Ou 2 - real fight football (NGM-061)(NGH-061).png",
  "Named_Snaps/Super Sidekicks 3 - The Next Glory _ Tokuten Ou 3 - eikou e no michi.png",
  "Named_Snaps/Super Sidekicks _ Tokuten Ou.png",
  "Named_Snaps/Syougi No Tatsujin - Master of Shougi.png",
  "Named_Snaps/Tecmo World Soccer '96.png",
  "Named_Snaps/The King of Fighters '94 (NGM-055)(NGH-055).png",
  "Named_Snaps/The King of Fighters '95 (NGH-084).png",
  "Named_Snaps/The King of Fighters '95 (NGH-084, alternate board).png",
  "Named_Snaps/The King of Fighters '95 (NGM-084).png",
  "Named_Snaps/The King of Fighters '96 (NGH-214).png",
  "Named_Snaps/The King of Fighters '96 (NGM-214).png",
  "Named_Snaps/The King of Fighters '97 (Korean release).png",
  "Named_Snaps/The King of Fighters '97 (NGH-2320).png",
  "Named_Snaps/The King of Fighters '97 (NGM-2320).png",
  "Named_Snaps/The King of Fighters '97 Plus (bootleg).png",
  "Named_Snaps/The King of Fighters '97 oroshi plus 2003 [Bootleg].png",
  "Named_Snaps/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board, set 1).png",
  "Named_Snaps/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board, set 2).png",
  "Named_Snaps/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGH-2420).png",
  "Named_Snaps/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGM-2420).png",
  "Named_Snaps/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGM-2420, alternate board).png",
  "Named_Snaps/The King of Fighters '99 - Millennium Battle (Korean release).png",
  "Named_Snaps/The King of Fighters '99 - Millennium Battle (Korean release, non-encrypted program).png",
  "Named_Snaps/The King of Fighters '99 - Millennium Battle (NGH-2510).png",
  "Named_Snaps/The King of Fighters '99 - Millennium Battle (NGM-2510).png",
  "Named_Snaps/The King of Fighters '99 - Millennium Battle (earlier).png",
  "Named_Snaps/The King of Fighters '99 - Millennium Battle (prototype).png",
  "Named_Snaps/The King of Fighters 10th Anniversary (bootleg) [Bootleg].png",
  "Named_Snaps/The King of Fighters 10th Anniversary 2005 Unique (bootleg) [Bootleg].png",
  "Named_Snaps/The King of Fighters 10th Anniversary Extra Plus (bootleg) [Bootleg].png",
  "Named_Snaps/The King of Fighters 2000 (NGM-2570) (NGH-2570).png",
  "Named_Snaps/The King of Fighters 2000 (not encrypted).png",
  "Named_Snaps/The King of Fighters 2001 (NGH-2621).png",
  "Named_Snaps/The King of Fighters 2001 (NGM-262_).png",
  "Named_Snaps/The King of Fighters 2002 (NGM-2650)(NGH-2650).png",
  "Named_Snaps/The King of Fighters 2002 (bootleg).png",
  "Named_Snaps/The King of Fighters 2002 Magic Plus (bootleg).png",
  "Named_Snaps/The King of Fighters 2002 Magic Plus II (bootleg).png",
  "Named_Snaps/The King of Fighters 2002 Plus (bootleg set 1).png",
  "Named_Snaps/The King of Fighters 2002 Plus (bootleg set 2).png",
  "Named_Snaps/The King of Fighters 2003 (NGH-2710).png",
  "Named_Snaps/The King of Fighters 2003 (NGM-2710).png",
  "Named_Snaps/The King of Fighters 2003 (NGM-2710, Export).png",
  "Named_Snaps/The King of Fighters 2003 (bootleg set 1) [Bootleg].png",
  "Named_Snaps/The King of Fighters 2003 (bootleg set 2) [Bootleg].png",
  "Named_Snaps/The King of Fighters 2004 Plus _ Hero (bootleg) [Bootleg].png",
  "Named_Snaps/The King of Fighters 2004 Ultra Plus (bootleg) [Bootleg].png",
  "Named_Snaps/The King of Fighters Special Edition 2004 (bootleg) [Bootleg].png",
  "Named_Snaps/The Last Blade 2 _ Bakumatsu Roman - Dai Ni Maku Gekka no Kenshi (NGM-2430)(NGH-2430).png",
  "Named_Snaps/The Last Blade _ Bakumatsu Roman - Gekka no Kenshi (NGH-2340).png",
  "Named_Snaps/The Last Blade _ Bakumatsu Roman - Gekka no Kenshi (NGM-2340).png",
  "Named_Snaps/The Last Soldier (Korean release of The Last Blade).png",
  "Named_Snaps/The Super Spy (NGM-011)(NGH-011).png",
  "Named_Snaps/The Ultimate 11 - The SNK Football Championship _ Tokuten Ou - Honoo no Libero.png",
  "Named_Snaps/Thrash Rally (ALM-003)(ALH-003).png",
  "Named_Snaps/Top Hunter - Roddy _ Cathy (NGH-046).png",
  "Named_Snaps/Top Hunter - Roddy _ Cathy (NGM-046).png",
  "Named_Snaps/Top Player's Golf (NGM-003)(NGH-003).png",
  "Named_Snaps/Treasure of the Caribbean.png",
  "Named_Snaps/Twinkle Star Sprites.png",
  "Named_Snaps/Viewpoint.png",
  "Named_Snaps/Voltage Fighter - Gowcaizer _ Choujin Gakuen Gowcaizer.png",
  "Named_Snaps/Waku Waku 7.png",
  "Named_Snaps/Windjammers _ Flying Power Disc.png",
  "Named_Snaps/World Heroes (ALH-005).png",
  "Named_Snaps/World Heroes (ALM-005).png",
  "Named_Snaps/World Heroes (set 3).png",
  "Named_Snaps/World Heroes 2 (ALH-006).png",
  "Named_Snaps/World Heroes 2 (ALM-006)(ALH-006).png",
  "Named_Snaps/World Heroes 2 Jet (ADM-007)(ADH-007).png",
  "Named_Snaps/World Heroes Perfect.png",
  "Named_Snaps/Zed Blade _ Operation Ragnarok.png",
  "Named_Snaps/Zintrick _ Oshidashi Zentrix (hack _ bootleg) [Bootleg].png",
  "Named_Snaps/Zupapa!.png",
  "Named_Titles/2020 Super Baseball (set 1).png",
  "Named_Titles/2020 Super Baseball (set 2).png",
  "Named_Titles/2020 Super Baseball (set 3).png",
  "Named_Titles/3 Count Bout _ Fire Suplex (NGM-043)(NGH-043).png",
  "Named_Titles/Aero Fighters 2 _ Sonic Wings 2.png",
  "Named_Titles/Aero Fighters 3 _ Sonic Wings 3.png",
  "Named_Titles/Aggressors of Dark Kombat _ Tsuukai GANGAN Koushinkyoku (ADM-008)(ADH-008).png",
  "Named_Titles/Alpha Mission II _ ASO II - Last Guardian (NGM-007)(NGH-007).png",
  "Named_Titles/Alpha Mission II _ ASO II - Last Guardian (prototype).png",
  "Named_Titles/Andro Dunos (NGM-049)(NGH-049).png",
  "Named_Titles/Art of Fighting 2 _ Ryuuko no Ken 2 (NGH-056).png",
  "Named_Titles/Art of Fighting 2 _ Ryuuko no Ken 2 (NGM-056).png",
  "Named_Titles/Art of Fighting 3 - The Path of the Warrior (Korean release).png",
  "Named_Titles/Art of Fighting 3 - The Path of the Warrior _ Art of Fighting - Ryuuko no Ken Gaiden.png",
  "Named_Titles/Art of Fighting _ Ryuuko no Ken (NGM-044)(NGH-044).png",
  "Named_Titles/Bakatonosama Mahjong Manyuuki (MOM-002)(MOH-002).png",
  "Named_Titles/Bang Bang Busters (2010 NCI release).png",
  "Named_Titles/Bang Bead.png",
  "Named_Titles/Baseball Stars 2.png",
  "Named_Titles/Baseball Stars Professional (NGH-002).png",
  "Named_Titles/Baseball Stars Professional (NGM-002).png",
  "Named_Titles/Battle Flip Shot.png",
  "Named_Titles/Blazing Star.png",
  "Named_Titles/Blue's Journey _ Raguy (ALH-001).png",
  "Named_Titles/Blue's Journey _ Raguy (ALM-001)(ALH-001).png",
  "Named_Titles/Breakers Revenge.png",
  "Named_Titles/Breakers.png",
  "Named_Titles/Burning Fight (NGH-018)(US).png",
  "Named_Titles/Burning Fight (NGM-018)(NGH-018).png",
  "Named_Titles/Burning Fight (prototype, older) [Prototype].png",
  "Named_Titles/Burning Fight (prototype, ver 23.3, 910326) [Prototype].png",
  "Named_Titles/Captain Tomaday.png",
  "Named_Titles/Chibi Marukochan Deluxe Quiz.png",
  "Named_Titles/Choutetsu Brikin'ger _ Iron Clad (Prototype).png",
  "Named_Titles/Choutetsu Brikin'ger _ Iron Clad (Prototype, bootleg).png",
  "Named_Titles/Crossed Swords (ALM-002)(ALH-002).png",
  "Named_Titles/Crossed Swords 2 (bootleg CD to cartridge conversion).png",
  "Named_Titles/Crouching Tiger Hidden Dragon 2003 (set 1) [Bootleg, Hack of _The King of Fighters 2001_].png",
  "Named_Titles/Crouching Tiger Hidden Dragon 2003 Super Plus [Bootleg].png",
  "Named_Titles/Crouching Tiger Hidden Dragon 2003 Super Plus alternate [Bootleg].png",
  "Named_Titles/Cyber-Lip (NGM-010).png",
  "Named_Titles/Digger Man [Homebrew].png",
  "Named_Titles/Double Dragon (Neo-Geo).png",
  "Named_Titles/Dragon's Heaven (development board).png",
  "Named_Titles/Eight Man (NGM-025)(NGH-025).png",
  "Named_Titles/Far East of Eden - Kabuki Klash _ Tengai Makyou - Shin Den.png",
  "Named_Titles/Fatal Fury - King of Fighters _ Garou Densetsu - shukumei no tatakai (NGM-033)(NGH-033).png",
  "Named_Titles/Fatal Fury 2 _ Garou Densetsu 2 - arata-naru tatakai (NGM-047)(NGH-047).png",
  "Named_Titles/Fatal Fury 3 - Road to the Final Victory _ Garou Densetsu 3 - haruka-naru tatakai (NGM-069)(NGH-069).png",
  "Named_Titles/Fatal Fury Special _ Garou Densetsu Special (set 1)(NGM-058)(NGH-058).png",
  "Named_Titles/Fatal Fury Special _ Garou Densetsu Special (set 2)(NGM-058)(NGH-058).png",
  "Named_Titles/Fight Fever (set 1).png",
  "Named_Titles/Fight Fever (set 2).png",
  "Named_Titles/Fighters Swords (Korean release of Samurai Shodown III).png",
  "Named_Titles/Football Frenzy (NGM-034)(NGH-034).png",
  "Named_Titles/Galaxy Fight - Universal Warriors.png",
  "Named_Titles/Ganryu _ Musashi Ganryuki.png",
  "Named_Titles/Garou - Mark of the Wolves (NGH-2530).png",
  "Named_Titles/Garou - Mark of the Wolves (NGM-2530) (NGH-2530).png",
  "Named_Titles/Garou - Mark of the Wolves (NGM-2530).png",
  "Named_Titles/Garou - Mark of the Wolves (bootleg).png",
  "Named_Titles/Garou - Mark of the Wolves (prototype).png",
  "Named_Titles/Ghost Pilots (NGH-020)(US).png",
  "Named_Titles/Ghost Pilots (NGM-020)(NGH-020).png",
  "Named_Titles/Ghost Pilots (prototype).png",
  "Named_Titles/Ghostlop (prototype).png",
  "Named_Titles/Goal! Goal! Goal!.png",
  "Named_Titles/Gururin.png",
  "Named_Titles/Idol Mahjong Final Romance 2 (Neo-Geo, bootleg of CD version).png",
  "Named_Titles/Jockey Grand Prix (set 1).png",
  "Named_Titles/Jockey Grand Prix (set 2).png",
  "Named_Titles/Jyanshin Densetsu - Quest of Jongmaster.png",
  "Named_Titles/Karnov's Revenge _ Fighter's History Dynamite.png",
  "Named_Titles/King of Gladiator (The King of Fighters '97 bootleg).png",
  "Named_Titles/King of the Monsters (set 1).png",
  "Named_Titles/King of the Monsters (set 2).png",
  "Named_Titles/King of the Monsters 2 - The Next Thing (NGM-039)(NGH-039).png",
  "Named_Titles/King of the Monsters 2 - The Next Thing (older).png",
  "Named_Titles/King of the Monsters 2 - The Next Thing (prototype).png",
  "Named_Titles/Kizuna Encounter - Super Tag Battle _ Fu'un Super Tag Battle.png",
  "Named_Titles/Lansquenet 2004 (Shock Troopers - 2nd Squad bootleg).png",
  "Named_Titles/Last Hope.png",
  "Named_Titles/Last Resort (prototype).png",
  "Named_Titles/Last Resort.png",
  "Named_Titles/League Bowling (NGM-019)(NGH-019).png",
  "Named_Titles/Legend of Success Joe _ Ashitano Joe Densetsu.png",
  "Named_Titles/Magical Drop II.png",
  "Named_Titles/Magical Drop III.png",
  "Named_Titles/Magician Lord (NGH-005).png",
  "Named_Titles/Magician Lord (NGM-005).png",
  "Named_Titles/Mahjong Kyo Retsuden (NGM-004)(NGH-004).png",
  "Named_Titles/Matrimelee _ Shin Gouketsuji Ichizoku Toukon (NGM-2660) (NGH-2660).png",
  "Named_Titles/Matrimelee _ Shin Gouketsuji Ichizoku Toukon (bootleg) [Bootleg].png",
  "Named_Titles/Metal Slug - Super Vehicle-001.png",
  "Named_Titles/Metal Slug 2 - Super Vehicle-001_II (NGM-2410) (NGH-2410).png",
  "Named_Titles/Metal Slug 3 (NGH-2560).png",
  "Named_Titles/Metal Slug 3 (NGM-2560).png",
  "Named_Titles/Metal Slug 3 (NGM-2560, earlier).png",
  "Named_Titles/Metal Slug 4 (NGH-2630).png",
  "Named_Titles/Metal Slug 4 (NGM-2630).png",
  "Named_Titles/Metal Slug 4 Plus (bootleg).png",
  "Named_Titles/Metal Slug 5 (NGH-2680).png",
  "Named_Titles/Metal Slug 5 (NGM-2680).png",
  "Named_Titles/Metal Slug 5 Plus (bootleg).png",
  "Named_Titles/Metal Slug 6 (Metal Slug 3 bootleg).png",
  "Named_Titles/Metal Slug X - Super Vehicle-001 (NGM-2500)(NGH-2500).png",
  "Named_Titles/Minasanno Okagesamadesu! Daisugorokutaikai (MOM-001)(MOH-001).png",
  "Named_Titles/Money Puzzle Exchanger _ Money Idol Exchanger.png",
  "Named_Titles/Mutation Nation (NGM-014)(NGH-014).png",
  "Named_Titles/NAM-1975 (NGM-001)(NGH-001).png",
  "Named_Titles/Neo Bomberman.png",
  "Named_Titles/Neo Drift Out - New Technology.png",
  "Named_Titles/Neo Mr. Do!.png",
  "Named_Titles/Neo Turf Masters _ Big Tournament Golf.png",
  "Named_Titles/Neo-Geo Cup '98 - The Road to the Victory.png",
  "Named_Titles/Nightmare in the Dark (bootleg).png",
  "Named_Titles/Nightmare in the Dark.png",
  "Named_Titles/Ninja Combat (NGH-009).png",
  "Named_Titles/Ninja Combat (NGM-009).png",
  "Named_Titles/Ninja Commando.png",
  "Named_Titles/Ninja Master's - haoh-ninpo-cho.png",
  "Named_Titles/Over Top.png",
  "Named_Titles/Pae Wang Jeon Seol _ Legend of a Warrior (Korean censored Samurai Shodown IV).png",
  "Named_Titles/Panic Bomber.png",
  "Named_Titles/Pleasure Goal _ Futsal - 5 on 5 Mini Soccer (NGM-219).png",
  "Named_Titles/Pochi and Nyaa (Ver 2.00).png",
  "Named_Titles/Pochi and Nyaa (Ver 2.02).png",
  "Named_Titles/Pop 'n Bounce _ Gapporin.png",
  "Named_Titles/Power Spikes II (NGM-068).png",
  "Named_Titles/Prehistoric Isle 2.png",
  "Named_Titles/Pulstar.png",
  "Named_Titles/Puzzle Bobble 2 _ Bust-A-Move Again (Neo-Geo).png",
  "Named_Titles/Puzzle Bobble _ Bust-A-Move (Neo-Geo) (NGM-083).png",
  "Named_Titles/Puzzle Bobble _ Bust-A-Move (Neo-Geo) (bootleg) [Bootleg].png",
  "Named_Titles/Puzzle De Pon! R!.png",
  "Named_Titles/Puzzle De Pon!.png",
  "Named_Titles/Puzzled _ Joy Joy Kid (NGM-021)(NGH-021).png",
  "Named_Titles/Quiz Daisousa Sen - The Last Count Down (NGM-023)(NGH-023).png",
  "Named_Titles/Quiz King of Fighters (Korea).png",
  "Named_Titles/Quiz King of Fighters (SAM-080)(SAH-080).png",
  "Named_Titles/Quiz Meitantei Neo _ Geo - Quiz Daisousa Sen part 2 (NGM-042)(NGH-042).png",
  "Named_Titles/Quiz Salibtamjeong - The Last Count Down (Korean localized Quiz Daisousa Sen).png",
  "Named_Titles/Rage of the Dragons (NGH-2640).png",
  "Named_Titles/Rage of the Dragons (NGM-264_).png",
  "Named_Titles/Ragnagard _ Shin-Oh-Ken.png",
  "Named_Titles/Real Bout Fatal Fury 2 - The Newcomers (Korean release).png",
  "Named_Titles/Real Bout Fatal Fury 2 - The Newcomers _ Real Bout Garou Densetsu 2 - the newcomers (NGH-2400).png",
  "Named_Titles/Real Bout Fatal Fury 2 - The Newcomers _ Real Bout Garou Densetsu 2 - the newcomers (NGM-2400).png",
  "Named_Titles/Real Bout Fatal Fury Special _ Real Bout Garou Densetsu Special (Korean release).png",
  "Named_Titles/Real Bout Fatal Fury Special _ Real Bout Garou Densetsu Special.png",
  "Named_Titles/Real Bout Fatal Fury _ Real Bout Garou Densetsu (Korean release).png",
  "Named_Titles/Real Bout Fatal Fury _ Real Bout Garou Densetsu (NGM-095)(NGH-095).png",
  "Named_Titles/Real Bout Fatal Fury _ Real Bout Garou Densetsu (bug fix revision).png",
  "Named_Titles/Riding Hero (NGM-006)(NGH-006).png",
  "Named_Titles/Riding Hero (set 2).png",
  "Named_Titles/Robo Army (NGM-032)(NGH-032).png",
  "Named_Titles/Robo Army (set 1).png",
  "Named_Titles/SNK vs. Capcom - SVC Chaos (NGM-2690)(NGH-2690).png",
  "Named_Titles/SNK vs. Capcom - SVC Chaos (bootleg).png",
  "Named_Titles/SNK vs. Capcom - SVC Chaos Plus (bootleg set 1) [Bootleg].png",
  "Named_Titles/SNK vs. Capcom - SVC Chaos Plus (bootleg set 2) [Bootleg].png",
  "Named_Titles/SNK vs. Capcom - SVC Chaos Super Plus (bootleg).png",
  "Named_Titles/Samurai Shodown II _ Shin Samurai Spirits - Haohmaru jigokuhen (NGM-063)(NGH-063).png",
  "Named_Titles/Samurai Shodown III _ Samurai Spirits - Zankurou Musouken (NGH-087).png",
  "Named_Titles/Samurai Shodown III _ Samurai Spirits - Zankurou Musouken (NGM-087).png",
  "Named_Titles/Samurai Shodown IV - Amakusa's Revenge _ Samurai Spirits - Amakusa Kourin (NGM-222)(NGH-222).png",
  "Named_Titles/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGH-2720) (1st release, censored).png",
  "Named_Titles/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGH-2720) (2nd release, less censored).png",
  "Named_Titles/Samurai Shodown V Special _ Samurai Spirits Zero Special (NGM-2720).png",
  "Named_Titles/Samurai Shodown V _ Samurai Spirits Zero (NGH-2700).png",
  "Named_Titles/Samurai Shodown V _ Samurai Spirits Zero (NGM-2700, set 1).png",
  "Named_Titles/Samurai Shodown V _ Samurai Spirits Zero (NGM-2700, set 2).png",
  "Named_Titles/Samurai Shodown V _ Samurai Spirits Zero (bootleg) [Bootleg].png",
  "Named_Titles/Samurai Shodown _ Samurai Spirits (NGH-045).png",
  "Named_Titles/Samurai Shodown _ Samurai Spirits (NGM-045).png",
  "Named_Titles/Saulabi Spirits _ Jin Saulabi Tu Hon (Korean release of Samurai Shodown II).png",
  "Named_Titles/Saulabi Spirits _ Jin Saulabi Tu Hon (Korean release of Samurai Shodown II, set 2).png",
  "Named_Titles/Savage Reign _ Fu'un Mokushiroku - kakutou sousei.png",
  "Named_Titles/Sengoku 2 _ Sengoku Denshou 2.png",
  "Named_Titles/Sengoku 3 _ Sengoku Densho 2001 (Set 2).png",
  "Named_Titles/Sengoku 3 _ Sengoku Densho 2001 (set 1).png",
  "Named_Titles/Sengoku _ Sengoku Denshou (NGH-017)(US).png",
  "Named_Titles/Sengoku _ Sengoku Denshou (NGM-017)(NGH-017).png",
  "Named_Titles/Shock Troopers (set 1).png",
  "Named_Titles/Shock Troopers (set 2).png",
  "Named_Titles/Shock Troopers - 2nd Squad.png",
  "Named_Titles/Soccer Brawl (NGH-031).png",
  "Named_Titles/Soccer Brawl (NGM-031).png",
  "Named_Titles/Spin Master _ Miracle Adventure.png",
  "Named_Titles/Stakes Winner 2.png",
  "Named_Titles/Stakes Winner _ Stakes Winner - GI Kinzen  Seiha e no Michi (early development board).png",
  "Named_Titles/Stakes Winner _ Stakes Winner - GI kinzen seiha e no michi.png",
  "Named_Titles/Street Hoop _ Street Slam _ Dunk Dream (DEM-004) (DEH-004).png",
  "Named_Titles/Strikers 1945 Plus.png",
  "Named_Titles/Super Bubble Pop (MVS).png",
  "Named_Titles/Super Dodge Ball _ Kunio no Nekketsu Toukyuu Densetsu.png",
  "Named_Titles/Super Sidekicks 2 - The World Championship _ Tokuten Ou 2 - real fight football (NGM-061)(NGH-061).png",
  "Named_Titles/Super Sidekicks 3 - The Next Glory _ Tokuten Ou 3 - eikou e no michi.png",
  "Named_Titles/Super Sidekicks _ Tokuten Ou.png",
  "Named_Titles/Syougi No Tatsujin - Master of Shougi.png",
  "Named_Titles/Tecmo World Soccer '96.png",
  "Named_Titles/The King of Fighters '94 (NGM-055)(NGH-055).png",
  "Named_Titles/The King of Fighters '95 (NGH-084).png",
  "Named_Titles/The King of Fighters '95 (NGH-084, alternate board).png",
  "Named_Titles/The King of Fighters '95 (NGM-084).png",
  "Named_Titles/The King of Fighters '96 (NGH-214).png",
  "Named_Titles/The King of Fighters '96 (NGM-214).png",
  "Named_Titles/The King of Fighters '97 (Korean release).png",
  "Named_Titles/The King of Fighters '97 (NGH-2320).png",
  "Named_Titles/The King of Fighters '97 (NGM-2320).png",
  "Named_Titles/The King of Fighters '97 Plus (bootleg).png",
  "Named_Titles/The King of Fighters '97 oroshi plus 2003 [Bootleg].png",
  "Named_Titles/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board, set 1).png",
  "Named_Titles/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board, set 2).png",
  "Named_Titles/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGH-2420).png",
  "Named_Titles/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGM-2420).png",
  "Named_Titles/The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (NGM-2420, alternate board).png",
  "Named_Titles/The King of Fighters '99 - Millennium Battle (Korean release).png",
  "Named_Titles/The King of Fighters '99 - Millennium Battle (Korean release, non-encrypted program).png",
  "Named_Titles/The King of Fighters '99 - Millennium Battle (NGH-2510).png",
  "Named_Titles/The King of Fighters '99 - Millennium Battle (NGM-2510).png",
  "Named_Titles/The King of Fighters '99 - Millennium Battle (earlier).png",
  "Named_Titles/The King of Fighters '99 - Millennium Battle (prototype).png",
  "Named_Titles/The King of Fighters 10th Anniversary (bootleg) [Bootleg].png",
  "Named_Titles/The King of Fighters 10th Anniversary 2005 Unique (bootleg) [Bootleg].png",
  "Named_Titles/The King of Fighters 10th Anniversary Extra Plus (bootleg) [Bootleg].png",
  "Named_Titles/The King of Fighters 2000 (NGM-2570) (NGH-2570).png",
  "Named_Titles/The King of Fighters 2000 (not encrypted).png",
  "Named_Titles/The King of Fighters 2001 (NGH-2621).png",
  "Named_Titles/The King of Fighters 2001 (NGM-262_).png",
  "Named_Titles/The King of Fighters 2002 (NGM-2650)(NGH-2650).png",
  "Named_Titles/The King of Fighters 2002 (bootleg).png",
  "Named_Titles/The King of Fighters 2002 Magic Plus (bootleg).png",
  "Named_Titles/The King of Fighters 2002 Magic Plus II (bootleg).png",
  "Named_Titles/The King of Fighters 2002 Plus (bootleg set 1).png",
  "Named_Titles/The King of Fighters 2002 Plus (bootleg set 2).png",
  "Named_Titles/The King of Fighters 2003 (NGH-2710).png",
  "Named_Titles/The King of Fighters 2003 (NGM-2710).png",
  "Named_Titles/The King of Fighters 2003 (NGM-2710, Export).png",
  "Named_Titles/The King of Fighters 2003 (bootleg set 1) [Bootleg].png",
  "Named_Titles/The King of Fighters 2003 (bootleg set 2) [Bootleg].png",
  "Named_Titles/The King of Fighters 2004 Plus _ Hero (bootleg) [Bootleg].png",
  "Named_Titles/The King of Fighters 2004 Ultra Plus (bootleg) [Bootleg].png",
  "Named_Titles/The King of Fighters Special Edition 2004 (bootleg) [Bootleg].png",
  "Named_Titles/The Last Blade 2 _ Bakumatsu Roman - Dai Ni Maku Gekka no Kenshi (NGM-2430)(NGH-2430).png",
  "Named_Titles/The Last Blade _ Bakumatsu Roman - Gekka no Kenshi (NGH-2340).png",
  "Named_Titles/The Last Blade _ Bakumatsu Roman - Gekka no Kenshi (NGM-2340).png",
  "Named_Titles/The Last Soldier (Korean release of The Last Blade).png",
  "Named_Titles/The Super Spy (NGM-011)(NGH-011).png",
  "Named_Titles/The Ultimate 11 - The SNK Football Championship _ Tokuten Ou - Honoo no Libero.png",
  "Named_Titles/Thrash Rally (ALM-003)(ALH-003).png",
  "Named_Titles/Top Hunter - Roddy _ Cathy (NGH-046).png",
  "Named_Titles/Top Hunter - Roddy _ Cathy (NGM-046).png",
  "Named_Titles/Top Player's Golf (NGM-003)(NGH-003).png",
  "Named_Titles/Treasure of the Caribbean.png",
  "Named_Titles/Twinkle Star Sprites.png",
  "Named_Titles/Viewpoint.png",
  "Named_Titles/Voltage Fighter - Gowcaizer _ Choujin Gakuen Gowcaizer.png",
  "Named_Titles/Waku Waku 7.png",
  "Named_Titles/Windjammers _ Flying Power Disc.png",
  "Named_Titles/World Heroes (ALH-005).png",
  "Named_Titles/World Heroes (ALM-005).png",
  "Named_Titles/World Heroes (set 3).png",
  "Named_Titles/World Heroes 2 (ALH-006).png",
  "Named_Titles/World Heroes 2 (ALM-006)(ALH-006).png",
  "Named_Titles/World Heroes 2 Jet (ADM-007)(ADH-007).png",
  "Named_Titles/World Heroes Perfect.png",
  "Named_Titles/Zed Blade _ Operation Ragnarok.png",
  "Named_Titles/Zintrick _ Oshidashi Zentrix (hack _ bootleg) [Bootleg].png",
  "Named_Titles/Zupapa!.png",
}
