return {
  "Named_Boxarts/Assault Suit Leynos (Japan).png",
  "Named_Boxarts/Biohazard 7 - Resident Evil (Japan).png",
  "Named_Boxarts/Dark Souls III (Japan).png",
  "Named_Boxarts/Dead or Alive Xtreme 3 - Fortune (Japan).png",
  "Named_Boxarts/Dragon Quest Builders (Japan).png",
  "Named_Boxarts/Final Fantasy Type-0 HD (Day One Edition) (USA).png",
  "Named_Boxarts/Final Fantasy X &amp; X-2 HD Remaster (Europe).png",
  "Named_Boxarts/Final Fantasy XIV Online - A Realm Reborn (Europe).png",
  "Named_Boxarts/Final Fantasy XV (Japan).png",
  "Named_Boxarts/Gravity Daze (Japan).png",
  "Named_Boxarts/Gravity Rush Remastered (Europe).png",
  "Named_Boxarts/NieR Automata (Japan).png",
  "Named_Boxarts/Nioh (Japan).png",
  "Named_Boxarts/Odin Sphere Leifthrasir (Japan).png",
  "Named_Boxarts/Persona 5 (Japan).png",
  "Named_Boxarts/Persona 5 (USA).png",
  "Named_Boxarts/Ryu ga Gotoku - Kiwami (Japan).png",
  "Named_Boxarts/Senjou no Valkyria Remaster (Japan).png",
  "Named_Boxarts/Tearaway (Japan).png",
  "Named_Boxarts/Yoru no Nai Kuni (Japan).png",
}
