return {
  "Named_Boxarts/Arkanoid (1986)(Taito)[CLOAD + RUN].png",
  "Named_Boxarts/Donkey Kong (1986)(Ocean Software)[h Buggy Software][CLOAD + RUN].png",
  "Named_Boxarts/Frantic Freddy (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Frantic Freddy (1983)(Spectravideo)[a][BLOAD'CAS-',R].png",
  "Named_Boxarts/International Karate (1986)(Endurance Games)[cr Darksloke][CLOAD + RUN].png",
  "Named_Boxarts/Kung Fu Master (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Mini Golf (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Boxarts/New York Bomb Blitz (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Boxarts/Nomis (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Boxarts/Pengwyn (1983)(Postern)[CLOAD + RUN].png",
  "Named_Boxarts/Planet Patrol (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Planet Patrol (1983)(Spectravideo)[a][BLOAD'CAS-',R].png",
  "Named_Boxarts/Sasa (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Spectron (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Boxarts/Super Cross Force (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Tele Bunnie (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Tetra Horror (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Turboat (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Boxarts/Zaxxon (1982)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Alien 8 (1985)(Ultimate Play The Game)[CLOAD + RUN].png",
  "Named_Snaps/Arkanoid (1986)(Taito)[CLOAD + RUN].png",
  "Named_Snaps/Armoured Assault (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Assiduity (1984)(Lars Lewejohann)(de)[CLOAD + RUN].png",
  "Named_Snaps/Basic Collection 01 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Basic Collection 02 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Basic Collection 04 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Basic Tutorial (1983)(Spectravideo)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Biorythm SVI (1983)(SIL)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 01 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 02 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 04 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 05 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 06 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 08 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 09 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 10 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 11 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 12 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 13 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 14 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 15 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 16 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 17 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 18 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 19 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 20 (19xx)(-)[CLOAD + RUN][code-103423].png",
  "Named_Snaps/Burken Soft Game Pac 21 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 22 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 23 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 24 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 25 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 26 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 27 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 28 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Burken Soft Game Pac 29 (19xx)(-)[CLOAD + RUN].png",
  "Named_Snaps/Cabbage Patch Kids (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Cabbage Patch Kids (1984)(Konami)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Candoo Ninja (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Circus Charlie (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Comic Bakery (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Compatability (1983)(SIL)[CLOAD + RUN].png",
  "Named_Snaps/Cosmic Avenger (1983)(Universal)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Crazy Teeth (1984)(Dan Haggren)[CLOAD + RUN].png",
  "Named_Snaps/Crunch (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Decathlon (1984)(Activision)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Deklarations-Program (1985)(Gite Sundberg)(sv)[CLOAD + RUN].png",
  "Named_Snaps/Diamond Luis Editor (1986)(Ikesoft)(sv)[CLOAD + RUN].png",
  "Named_Snaps/Diamond Luis I (1986)(Ikesoft)[cr Morgoth][CLOAD + RUN].png",
  "Named_Snaps/Donkey Kong (1986)(Ocean Software)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Emergency Landing (1984)(John McLachlan)[CLOAD + RUN].png",
  "Named_Snaps/Explorer III (1984)(Robert Lindh)(sv)[CLOAD + RUN].png",
  "Named_Snaps/Find It (1984)(Spectravideo Israel)[CLOAD + RUN].png",
  "Named_Snaps/First Steps (1983)(Softy)[CLOAD + RUN].png",
  "Named_Snaps/Flipper Man (1984)(Computerworld - Mikrodata)(no)[CLOAD + RUN].png",
  "Named_Snaps/Flipper Slipper (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Fluffy (1987)(JTM Software)[BLOAD'CAS-',R].png",
  "Named_Snaps/Frantic Freddy (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Frantic Freddy (1983)(Spectravideo)[a][BLOAD'CAS-',R].png",
  "Named_Snaps/Gateway to Apshai (1983)(US Gold)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Ghost Trap (1983)(Yoga Computing)[CLOAD + RUN].png",
  "Named_Snaps/Goonies, The (1986)(Konami)[h Lord Wezzex][CLOAD + RUN].png",
  "Named_Snaps/Goonies, The (1986)(Konami)[h Lord Wezzex][a][CLOAD + RUN].png",
  "Named_Snaps/Graph Master II (1984)(C.A.E.)[CLOAD + RUN].png",
  "Named_Snaps/Graphic Chess (1986)(JTM Software)[BLOAD'CAS-',R].png",
  "Named_Snaps/Grave Digger (1984)(J. Pullen)[CLOAD + RUN].png",
  "Named_Snaps/Gunfright (1986)(Ultimate Play The Game)[CLOAD + RUN].png",
  "Named_Snaps/H.E.R.O. (1984)(Activision)[BLOAD'CAS-',R].png",
  "Named_Snaps/Hobbit, The (1985)(Melbourne House)[CLOAD + RUN].png",
  "Named_Snaps/Hollow (1984)(Lars Lewejohann)(de)[CLOAD + RUN].png",
  "Named_Snaps/Horse Racing (1983)(SIL)[CLOAD + RUN].png",
  "Named_Snaps/Hyper Olympic 1 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Hyper Olympic 2 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Hyper Rally (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Hyper Sports 1 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Hyper Sports 2 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/International Karate (1986)(Endurance Games)[cr Darksloke][CLOAD + RUN].png",
  "Named_Snaps/Jack the Nipper II - In Coconut Capers (1987)(Gremlin Graphics Software)[t][CLOAD + RUN].png",
  "Named_Snaps/Jet Alf (1984)(ELS)[CLOAD + RUN].png",
  "Named_Snaps/Jet Alf and the Manic Masters Revenge (1984)(ELS)[CLOAD + RUN].png",
  "Named_Snaps/Joystick 01 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 02 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 04 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 05 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 06 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 07 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 09 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Joystick 15 (1987)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Jumping Jack (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Jungle Jim (1984)(T&amp;M Software)[CLOAD + RUN].png",
  "Named_Snaps/Juno Lander (1983)(SIL)[CLOAD + RUN].png",
  "Named_Snaps/Just Write Jr (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Killer Car (1983)(U. Sandberg)[CLOAD + RUN].png",
  "Named_Snaps/Kiwi Country - South Island (1984)(Waitaki Software)[CLOAD + RUN].png",
  "Named_Snaps/Knightmare. Majyo Densetsu (1986)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Konami's Baseball (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Konami's Boxing (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Konami's Ping Pong (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Konami's Soccer (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Konami's Tennis (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Kung Fu Master (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/LABYX (1985)(Hjemmedata Magazine)(no)[CLOAD + RUN].png",
  "Named_Snaps/Log It (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Looping (1983)(Venture Line)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 01 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 02 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 03 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 04 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 05 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 06 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 07 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 08 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 09 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 10 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 12 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 13 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 16 (19xx)(-)[position tape + BLOAD'CAS-',R].png",
  "Named_Snaps/MKOD Collection 17 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 18 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Snaps/MKOD Collection 19 (19xx)(-)[position tape + BLOAD'CAS-',R].png",
  "Named_Snaps/MSX Emulator (1983)(H. Klopper - P. Zevenhoven)[CLOAD + RUN].png",
  "Named_Snaps/Magical Tree (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Megalone (1986)(J&amp;D Team)[CLOAD + RUN].png",
  "Named_Snaps/Megalone (1986)(J&amp;D Team)[a][CLOAD + RUN].png",
  "Named_Snaps/Memory Trainer (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Snaps/Mini Golf (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Moon Lander (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Snaps/Mopi Ranger (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Mouse Trap (1983)(Exidy)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Mr. Do! (1984)(Nippon Columbia)[CLOAD + RUN].png",
  "Named_Snaps/Munch-A-Math (1984)(Spectravideo Israel)[CLOAD + RUN].png",
  "Named_Snaps/Music Composer (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Snaps/Music Demo 1 (1986)(Bach TP)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Music Demo 2 (1987)(Bach TP)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Music Demo 3 (1988)(Bach TP)[position tape + CLOAD + RUN].png",
  "Named_Snaps/Music Mentor (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Music Mentor (1983)(Spectravideo)[cr Hacke][BLOAD'CAS-',R].png",
  "Named_Snaps/New York Bomb Blitz (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Nomis (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/O'Mac Farmer (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Parachute Jumping (1984)(Leo Soft)[CLOAD + RUN].png",
  "Named_Snaps/Pengwyn (1983)(Postern)[CLOAD + RUN].png",
  "Named_Snaps/Pepper 2 (1983)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Perilous Journey (1984)(PM Programs)[CLOAD + RUN].png",
  "Named_Snaps/Planet Patrol (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Planet Patrol (1983)(Spectravideo)[a][BLOAD'CAS-',R].png",
  "Named_Snaps/Pogo Stick (1985)(Choice Software)(de)[CLOAD + RUN].png",
  "Named_Snaps/Punchy (1984)(Mr. Micro)[BLOAD'CAS-',R].png",
  "Named_Snaps/Rambo III Intro (19xx)(Mr. Haward)[RUN'CAS-'].png",
  "Named_Snaps/Rambo III Intro (19xx)(Mr. Haward)[a][RUN'CAS-'].png",
  "Named_Snaps/Rescue (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Road Fighter (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Robocop (1988)(Ocean Software)[cr Mr. Haward][RUN'CAS-'].png",
  "Named_Snaps/Robot Ball (1983)(Mirage Software)(sv)[CLOAD + RUN].png",
  "Named_Snaps/Roulette (1985)(Intersoft)[CLOAD + RUN].png",
  "Named_Snaps/Sasa (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Sector Alpha (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Sky Jaguar (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Smurf Rescue in Gargamel's Castle (1983)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Spectra Break (1983)(SIL)[CLOAD + RUN].png",
  "Named_Snaps/Spectra Cryptic Cube (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Spectra Diary (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Spectra File Cabinet (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Spectra Font Editor (1984)(Stephen Boal)[CLOAD + RUN].png",
  "Named_Snaps/Spectra Home Economist Coupon Management Program (1983)(Intellisoft)[CLOAD + RUN].png",
  "Named_Snaps/Spectra Trader (1984)(A.C. Hunt)[CLOAD + RUN].png",
  "Named_Snaps/Spectramind (1984)(C.A.E.)[CLOAD + RUN].png",
  "Named_Snaps/Spectravideo Address Book System (1983)(Greg L. Weinstein)[CLOAD + RUN].png",
  "Named_Snaps/Spectron (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Star Words (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Snaps/Struggle for Livelihood (1985)(Choice Software)(de)[CLOAD + RUN].png",
  "Named_Snaps/Super Cross Force (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Swing Man (1983)(Softy)[CLOAD + RUN].png",
  "Named_Snaps/Tele Bunnie (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Tetra Horror (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Three Wall Smash (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Snaps/Time Trax (1986)(Bug-Byte Software)[CLOAD + RUN].png",
  "Named_Snaps/Track &amp; Field 1. Hyper Olympic 1 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Treasure Chest (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Snaps/Turboat (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Snaps/Uncle Albert (1984)(A.C. Hunt)[CLOAD + RUN].png",
  "Named_Snaps/War Games (1984)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Snaps/Yie Ar Kung-Fu (1985)(Konami)[CLOAD + RUN].png",
  "Named_Snaps/Yie Ar Kung-Fu II - The Emperor Yie-Gah (1985)(Konami)[t][CLOAD + RUN].png",
  "Named_Snaps/Zakil Wood (1985)(Mr. Micro)[CLOAD + RUN].png",
  "Named_Snaps/Zaxxon (1982)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Alien 8 (1985)(Ultimate Play The Game)[CLOAD + RUN].png",
  "Named_Titles/Arkanoid (1986)(Taito)[CLOAD + RUN].png",
  "Named_Titles/Armoured Assault (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Basic Collection 01 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Basic Collection 02 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Basic Collection 04 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Basic Collection 05 (1985)(-)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Biorythm SVI (1983)(SIL)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 01 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 02 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 03 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 04 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 05 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 06 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 07 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 08 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 09 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 10 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 11 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 12 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 13 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 14 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 15 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 16 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 17 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 18 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 19 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 20 (19xx)(-)[CLOAD + RUN][code-103423].png",
  "Named_Titles/Burken Soft Game Pac 21 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 22 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 23 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 24 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 25 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 26 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 27 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 28 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Burken Soft Game Pac 29 (19xx)(-)[CLOAD + RUN].png",
  "Named_Titles/Cabbage Patch Kids (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Cabbage Patch Kids (1984)(Konami)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Candoo Ninja (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Circus Charlie (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Comic Bakery (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Compatability (1983)(SIL)[CLOAD + RUN].png",
  "Named_Titles/Cosmic Avenger (1983)(Universal)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Crazy Teeth (1984)(Dan Haggren)[CLOAD + RUN].png",
  "Named_Titles/Crunch (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Decathlon (1984)(Activision)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Deklarations-Program (1985)(Gite Sundberg)(sv)[CLOAD + RUN].png",
  "Named_Titles/Diamond Luis Editor (1986)(Ikesoft)(sv)[CLOAD + RUN].png",
  "Named_Titles/Donkey Kong (1986)(Ocean Software)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Emergency Landing (1984)(John McLachlan)[CLOAD + RUN].png",
  "Named_Titles/Explorer III (1984)(Robert Lindh)(sv)[CLOAD + RUN].png",
  "Named_Titles/Find It (1984)(Spectravideo Israel)[CLOAD + RUN].png",
  "Named_Titles/First Steps (1983)(Softy)[CLOAD + RUN].png",
  "Named_Titles/Flipper Man (1984)(Computerworld - Mikrodata)(no)[CLOAD + RUN].png",
  "Named_Titles/Flipper Slipper (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Fluffy (1987)(JTM Software)[BLOAD'CAS-',R].png",
  "Named_Titles/Frantic Freddy (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Frantic Freddy (1983)(Spectravideo)[a][BLOAD'CAS-',R].png",
  "Named_Titles/Gateway to Apshai (1983)(US Gold)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Ghost Trap (1983)(Yoga Computing)[CLOAD + RUN].png",
  "Named_Titles/Goonies, The (1986)(Konami)[h Lord Wezzex][CLOAD + RUN].png",
  "Named_Titles/Goonies, The (1986)(Konami)[h Lord Wezzex][a][CLOAD + RUN].png",
  "Named_Titles/Graph Master II (1984)(C.A.E.)[CLOAD + RUN].png",
  "Named_Titles/Graphic Chess (1986)(JTM Software)[BLOAD'CAS-',R].png",
  "Named_Titles/Grave Digger (1984)(J. Pullen)[CLOAD + RUN].png",
  "Named_Titles/Gunfright (1986)(Ultimate Play The Game)[CLOAD + RUN].png",
  "Named_Titles/H.E.R.O. (1984)(Activision)[BLOAD'CAS-',R].png",
  "Named_Titles/Hobbit, The (1985)(Melbourne House)[CLOAD + RUN].png",
  "Named_Titles/Hollow (1984)(Lars Lewejohann)(de)[CLOAD + RUN].png",
  "Named_Titles/Horse Racing (1983)(SIL)[CLOAD + RUN].png",
  "Named_Titles/Hyper Olympic 1 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Hyper Olympic 2 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Hyper Rally (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Hyper Sports 1 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Hyper Sports 2 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/International Karate (1986)(Endurance Games)[cr Darksloke][CLOAD + RUN].png",
  "Named_Titles/Jack the Nipper II - In Coconut Capers (1987)(Gremlin Graphics Software)[t][CLOAD + RUN].png",
  "Named_Titles/Jet Alf (1984)(ELS)[CLOAD + RUN].png",
  "Named_Titles/Jet Alf and the Manic Masters Revenge (1984)(ELS)[CLOAD + RUN].png",
  "Named_Titles/Joystick 01 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 02 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 03 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 04 (1985)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 05 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 06 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 07 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 09 (1986)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Joystick 15 (1987)(SAGA &amp; Joystick)(sv)[position tape + CLOAD + RUN].png",
  "Named_Titles/Jumping Jack (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Jungle Jim (1984)(T&amp;M Software)[CLOAD + RUN].png",
  "Named_Titles/Juno Lander (1983)(SIL)[CLOAD + RUN].png",
  "Named_Titles/Just Write Jr (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Killer Car (1983)(U. Sandberg)[CLOAD + RUN].png",
  "Named_Titles/Kiwi Country - South Island (1984)(Waitaki Software)[CLOAD + RUN].png",
  "Named_Titles/Knightmare. Majyo Densetsu (1986)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Konami's Baseball (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Konami's Boxing (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Konami's Ping Pong (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Konami's Soccer (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Konami's Tennis (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Kung Fu Master (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/LABYX (1985)(Hjemmedata Magazine)(no)[CLOAD + RUN].png",
  "Named_Titles/Log It (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Looping (1983)(Venture Line)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 01 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 02 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 03 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 04 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 05 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 06 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 07 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 08 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 09 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 10 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 12 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 13 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 14 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 16 (19xx)(-)[position tape + BLOAD'CAS-',R].png",
  "Named_Titles/MKOD Collection 17 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 18 (19xx)(-)[position tape + CLOAD + RUN].png",
  "Named_Titles/MKOD Collection 19 (19xx)(-)[position tape + BLOAD'CAS-',R].png",
  "Named_Titles/MSX Emulator (1983)(H. Klopper - P. Zevenhoven)[CLOAD + RUN].png",
  "Named_Titles/Magical Tree (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Megalone (1986)(J&amp;D Team)[CLOAD + RUN].png",
  "Named_Titles/Megalone (1986)(J&amp;D Team)[a][CLOAD + RUN].png",
  "Named_Titles/Memory Trainer (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Titles/Mini Golf (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Moon Lander (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Titles/Mopi Ranger (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Mouse Trap (1983)(Exidy)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Mr. Do! (1984)(Nippon Columbia)[CLOAD + RUN].png",
  "Named_Titles/Munch-A-Math (1984)(Spectravideo Israel)[CLOAD + RUN].png",
  "Named_Titles/Music Composer (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Titles/Music Demo 1 (1986)(Bach TP)[position tape + CLOAD + RUN].png",
  "Named_Titles/Music Demo 2 (1987)(Bach TP)[position tape + CLOAD + RUN].png",
  "Named_Titles/Music Demo 3 (1988)(Bach TP)[position tape + CLOAD + RUN].png",
  "Named_Titles/Music Mentor (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Music Mentor (1983)(Spectravideo)[cr Hacke][BLOAD'CAS-',R].png",
  "Named_Titles/New York Bomb Blitz (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Nomis (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/O'Mac Farmer (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Parachute Jumping (1984)(Leo Soft)[CLOAD + RUN].png",
  "Named_Titles/Pengwyn (1983)(Postern)[CLOAD + RUN].png",
  "Named_Titles/Pepper 2 (1983)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Perilous Journey (1984)(PM Programs)[CLOAD + RUN].png",
  "Named_Titles/Planet Patrol (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Planet Patrol (1983)(Spectravideo)[a][BLOAD'CAS-',R].png",
  "Named_Titles/Pogo Stick (1985)(Choice Software)(de)[CLOAD + RUN].png",
  "Named_Titles/Punchy (1984)(Mr. Micro)[BLOAD'CAS-',R].png",
  "Named_Titles/Rescue (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Road Fighter (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Roulette (1985)(Intersoft)[CLOAD + RUN].png",
  "Named_Titles/Sasa (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Sector Alpha (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Sky Jaguar (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Smurf Rescue in Gargamel's Castle (1983)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Spectra Break (1983)(SIL)[CLOAD + RUN]-231025-214710.png",
  "Named_Titles/Spectra Break (1983)(SIL)[CLOAD + RUN].png",
  "Named_Titles/Spectra Cryptic Cube (1984)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Spectra Diary (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Spectra File Cabinet (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Spectra Font Editor (1984)(Stephen Boal)[CLOAD + RUN].png",
  "Named_Titles/Spectra Home Economist Coupon Management Program (1983)(Intellisoft)[CLOAD + RUN].png",
  "Named_Titles/Spectra Home Economist Recipe Program (1983)(Intellisoft)[CLOAD + RUN].png",
  "Named_Titles/Spectra Trader (1984)(A.C. Hunt)[CLOAD + RUN].png",
  "Named_Titles/Spectramind (1984)(C.A.E.)[CLOAD + RUN].png",
  "Named_Titles/Spectravideo Address Book System (1983)(Greg L. Weinstein)[CLOAD + RUN].png",
  "Named_Titles/Spectron (1983)(Spectravideo)[CLOAD + RUN].png",
  "Named_Titles/Stockholm Adventure (1984)(J. Watte)(sv)[CLOAD + RUN].png",
  "Named_Titles/Struggle for Livelihood (1985)(Choice Software)(de)[CLOAD + RUN].png",
  "Named_Titles/Super Cross Force (1983)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Swing Man (1983)(Softy)[CLOAD + RUN].png",
  "Named_Titles/Tele Bunnie (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Tetra Horror (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Three Wall Smash (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Titles/Time Trax (1986)(Bug-Byte Software)[CLOAD + RUN].png",
  "Named_Titles/Track &amp; Field 1. Hyper Olympic 1 (1984)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Treasure Chest (1984)(Ian McLachlan)[CLOAD + RUN].png",
  "Named_Titles/Turboat (1984)(Spectravideo)[BLOAD'CAS-',R].png",
  "Named_Titles/Typing Tutor v1.1 (1983)(S.G. Bright)[CLOAD + RUN].png",
  "Named_Titles/Uncle Albert (1984)(A.C. Hunt)[CLOAD + RUN].png",
  "Named_Titles/War Games (1984)(Coleco)[h Buggy Software][CLOAD + RUN].png",
  "Named_Titles/Yie Ar Kung-Fu (1985)(Konami)[CLOAD + RUN].png",
  "Named_Titles/Yie Ar Kung-Fu II - The Emperor Yie-Gah (1985)(Konami)[t][CLOAD + RUN].png",
  "Named_Titles/Zakil Wood (1985)(Mr. Micro)[CLOAD + RUN].png",
  "Named_Titles/Zaxxon (1982)(Coleco)[h Buggy Software][CLOAD + RUN].png",
}
