return {
  "Named_Boxarts/2048.png",
  "Named_Boxarts/Basic Platformer.png",
  "Named_Boxarts/Blockdude.png",
  "Named_Boxarts/Chip-8 Emulator.png",
  "Named_Boxarts/Fierce Soldier.png",
  "Named_Boxarts/Formula1.png",
  "Named_Boxarts/JellyFish.png",
  "Named_Boxarts/Mahjong.png",
  "Named_Boxarts/Mazethingie.png",
  "Named_Boxarts/MineSweeper.png",
  "Named_Boxarts/One Skill.png",
  "Named_Boxarts/Party Man.png",
  "Named_Boxarts/Puztrix.png",
  "Named_Boxarts/Puzzle Land.png",
  "Named_Boxarts/RetroTime.png",
  "Named_Boxarts/Rubido.png",
  "Named_Boxarts/Simple Tennis.png",
  "Named_Boxarts/Solitaire.png",
  "Named_Boxarts/Tic Tac Toe.png",
  "Named_Boxarts/Triple Bubble (Demo).png",
  "Named_Boxarts/Vitris.png",
  "Named_Snaps/2048.png",
  "Named_Snaps/Basic Platformer.png",
  "Named_Snaps/Blockdude.png",
  "Named_Snaps/Bricks (Demo).png",
  "Named_Snaps/Chip-8 Emulator.png",
  "Named_Snaps/Fierce Soldier.png",
  "Named_Snaps/Formula1.png",
  "Named_Snaps/JellyFish.png",
  "Named_Snaps/Mahjong.png",
  "Named_Snaps/Mazethingie.png",
  "Named_Snaps/MineSweeper.png",
  "Named_Snaps/One Skill.png",
  "Named_Snaps/Party Man.png",
  "Named_Snaps/Pseudo-3D Racer (Demo).png",
  "Named_Snaps/Puztrix.png",
  "Named_Snaps/Puzzle Land.png",
  "Named_Snaps/RetroTime.png",
  "Named_Snaps/Rubido.png",
  "Named_Snaps/Simple Tennis.png",
  "Named_Snaps/Solitaire.png",
  "Named_Snaps/Test - Beat editor.png",
  "Named_Snaps/Test - Blending modes.png",
  "Named_Snaps/Test - Date and time.png",
  "Named_Snaps/Test - Gamepads.png",
  "Named_Snaps/Test - Large zoom.png",
  "Named_Snaps/Test - Math functions.png",
  "Named_Snaps/Test - Memory card.png",
  "Named_Snaps/Test - Minimal test.png",
  "Named_Snaps/Test - Random numbers.png",
  "Named_Snaps/Test - Rotozoom.png",
  "Named_Snaps/Test - Sound effects.png",
  "Named_Snaps/Test - Tile map.png",
  "Named_Snaps/Tic Tac Toe.png",
  "Named_Snaps/Triple Bubble (Demo).png",
  "Named_Snaps/Virconstein 3D (Demo).png",
  "Named_Snaps/Vitris.png",
  "Named_Titles/2048.png",
  "Named_Titles/Basic Platformer.png",
  "Named_Titles/Blockdude.png",
  "Named_Titles/Bricks (Demo).png",
  "Named_Titles/Chip-8 Emulator.png",
  "Named_Titles/Fierce Soldier.png",
  "Named_Titles/Formula1.png",
  "Named_Titles/JellyFish.png",
  "Named_Titles/Mahjong.png",
  "Named_Titles/Mazethingie.png",
  "Named_Titles/MineSweeper.png",
  "Named_Titles/One Skill.png",
  "Named_Titles/Party Man.png",
  "Named_Titles/Puztrix.png",
  "Named_Titles/Puzzle Land.png",
  "Named_Titles/RetroTime.png",
  "Named_Titles/Rubido.png",
  "Named_Titles/Simple Tennis.png",
  "Named_Titles/Solitaire.png",
  "Named_Titles/Tic Tac Toe.png",
  "Named_Titles/Triple Bubble (Demo).png",
  "Named_Titles/Vitris.png",
}
