return {
    advanced = {
        {
            name = "Gradient + Logo",
            values = {
                background = {
                    screenshot = "1/2",
                    mask = "gradient_1/2",
                    opacity = 50,
                },
                insert_1 = {
                    media_type = "wheel",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "middle_right",
                    anchor = "inner",
                },
            },
        },
        {
            name = "GradRad + 3:2Grid + Platform",
            values = {
                background = {
                    screenshot = "3/4",
                    mask = "gradient_1/2_rad",
                    opacity = 50,
                },
                insert_1 = {
                    media_type = "grid2x3",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "none",
                    position = "bottom_right",
                    anchor = "inner",
                },
                insert_2 = {
                    media_type = "platform_color",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "top_right",
                    anchor = "inner",
                },
            },
        },
        {
            name = "Fullscreen + box/wheel",
            values = {
                background = {
                    screenshot = "full",
                    mask = "none",
                    opacity = 50,
                },
                insert_1 = {
                    media_type = "box2d",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "bottom_right",
                    anchor = "inner",
                },
                insert_2 = {
                    media_type = "wheel",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "top_right",
                    anchor = "inner",
                },
            },
        },
        {
            name = "3/4 Gradient + platform/wheel",
            values = {
                background = {
                    screenshot = "3/4",
                    header_footer = true,
                    mask = "gradient_3/4",
                    opacity = 65,
                },
                insert_1 = {
                    media_type = "platform_white",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "none",
                    position = "top_right",
                    anchor = "inner",
                    offset_y = -10,
                },
                insert_2 = {
                    media_type = "wheel",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "bottom_right",
                    anchor = "inner",
                },
            },
        },
        {
            name = "Basic 3",
            values = {
                background = {
                    screenshot = "none",
                },
                insert_1 = {
                    media_type = "screenshot",
                    size = "xl",
                    size_ratio = "proportional",
                    fit = "cover",
                    stroke_color = "none",
                    position = "middle_right",
                    anchor = "inner",
                    z_index = 1,
                    offset_x = -5,
                    offset_y = 0,
                },
                insert_2 = {
                    media_type = "wheel",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "top_right",
                    anchor = "inner",
                    z_index = 2,
                    offset_x = 0,
                    offset_y = -8,
                },
                insert_3 = {
                    media_type = "box2d",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "bottom_right",
                    anchor = "inner",
                    z_index = 2,
                    offset_x = 6,
                    offset_y = 0,
                },
            },
        },
        {
            name = "3:2 Grid Only",
            values = {
                background = {
                    screenshot = "none",
                },
                insert_1 = {
                    media_type = "grid2x3",
                    size = "xxl",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "none",
                    position = "middle_right",
                    anchor = "edge",
                },
            },
        },
        {
            name = "Artbook",
            values = {
                background = {
                    screenshot = "top_1/4",
                    mask = "none",
                    opacity = 100,
                },
                insert_1 = {
                    media_type = "platform_white",
                    size = "m",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "none",
                    position = "top_left",
                    anchor = "inner",
                    offset_y = -15,
                },
                insert_2 = {
                    media_type = "wheel",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    z_index = 3,
                    stroke_color = "white",
                    position = "middle_right",
                    anchor = "inner",
                },
                insert_3 = {
                    media_type = "box3d",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "none",
                    position = "bottom_right",
                    anchor = "inner",
                },
            },
        },
        {
            name = "Artbook Halftone",
            values = {
                background = {
                    screenshot = "3/4",
                    mask = "halftone_1/2",
                    opacity = 60,
                },
                insert_1 = {
                    media_type = "platform_color",
                    size = "m",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "none",
                    position = "top_left",
                    anchor = "inner",
                    offset_y = -15,
                },
                insert_2 = {
                    media_type = "wheel",
                    size = "l",
                    size_ratio = "proportional",
                    fit = "contain",
                    stroke_color = "white",
                    position = "bottom_right",
                    anchor = "inner",
                },
            },
        },
    },
}
